miraheze/mw-config

GlobalExtensions.php

add Nuke, Gadgets, MassMessage, GlobalBlocking

---

LocalSettings.php

Add account creation rate limit

Account creation throttling

---

LocalSettings.php

Enable Translate extension on testwiki

enable testwiki translate

---

LocalSettings.php

Add autopatrolled, confirmed (possibly add/change permissions for this), and skipcaptcha.

Add some groups

---

LocalSettings.php

Configures autoconfirmed users, enables upload by URL on quantixwiki, quantix wiki bureaucrat protection

Various things

---

LocalSettings.php

add Scribunto per request

---

LocalSettings.php

add a few changes to testwiki

---

LocalSettings.php

Add namespaces to my wiki and duplicate #62

Quantix namespaces (and duplicate #62)

---

LocalSettings.php

disable anon edit on antiguabarbadoswiki

---

LocalSettings.php

add linuxwiki favicon per req

---

LocalSettings.php

Initial Settings for reviwiki

---

LocalSettings.php

add VE and scribunto to cbmediawiki per req

---

LocalSettings.php

add custom logo for wikifuture

---

LocalSettings.php

add VE for clicordiwiki per req

---

LocalSettings.php

Please someone else do the licence  CC-BY-SA license into Copyrighted Content(or All Rights Reserved) , as im not sure how to change licence

add favicon and skin to diavwiki

---

LocalSettings.php

add VE for genwiki per req

---

LocalSettings.php

Add diavwiki license

---

LocalSettings.php

I didn't remove diavwiki RightsUrl as it might be nice to have the full path. RightsPage overrides RightsUrl

RightsPage diavwiki+quantixwiki

---

LocalSettings.php

The rest are not downloaded/configured.

enable a few extensions for att per req

---

MissingWiki.php

Link for request wiki

---

LocalSettings.php

Add reviwiki logo

---

LocalSettings.php

Reverts miraheze/mw-config#116
Well I forgot to mark it [WIP].

Revert "Add reviwiki logo"

---

LocalSettings.php

For pages such as Request features/Archive 1

Enable subpages for mainspace on meta

---

LocalSettings.php

Per [[meta:RF]]. miraheze/puppet#16 first.

Add VE to unikumwiki

---

MissingWiki.php

Used http://www.html.am/html-editors/html-text-editor.cfm
can check what it looks like here or locally :p

update 404 page, include poweredbyimg etc

---

LocalSettings.php

finish setting up catbox namespaces

---

LocalSettings.php

requested on irc 
(might have to revoke some permissions from user, question wasn't answered)

cineama wiki changes

---

LocalSettings.php

Requested on [[meta:RF]].
Blocked by miraheze/puppet#22

Enable VE for permanentfuturelabwiki

---

LocalSettings.php

Its a wiki to test admin tools, very useful ext.

enable adminlinks for testwiki per req

---

LocalSettings.php

More security on testwiki to prevent vandalism.

revoke nuke from admin testwiki

---

LocalSettings.php

Waiting for #184 to be merged.

add Variables to szk wiki per req

---

LocalSettings.php

Due to complaints of poor performance and editing issues from community

remove VE from ATT

---

LocalSettings.php

VE for applebranchwiki

---

LocalSettings.php

Per request, blocked by miraheze/puppet#29

Add flow and VE to 8stationwiki

---

LocalSettings.php

Hi, this is the same as miraheze/mw-config#206, but with the addition of TitleKey, and no extraneous commits!

Configure extensions for walthamstowlabourwiki.

---

LocalSettings.php

To block changing password for Example

testwiki hook blocking password change for Example

---

LocalSettings.php

Reverts miraheze/mw-config#225
opens #224

Revert "testwiki hook blocking password change for Example"

---

LocalSettings.php

Reverts miraheze/mw-config#227

Revert "Revert "testwiki hook blocking password change for Example""

---

LocalSettings.php

https://meta.miraheze.org/wiki/Request_features#Development_Wiki_.28Status:_Open.29
pr 44 in puppet

developmentwiki, flow, visualeditor

---

LocalSettings.php

To be merged at 16:20 UTC (01:20 KST)
**DO NOT MERGE THIS UNLESS YOU ARE @revi OR HAS SIGNOFF FROM REVI OR SPF**

Readonly all wikis for 1.26

---

LocalExtensions.php

add FeaturedFeeds

---

LocalExtensions.php

Blocked by https://github.com/miraheze/mediawiki/pull/16

add VectorBeta

---

LocalExtensions.php

Mediawiki page says : "Run the update script which will automatically create the necessary database tables that this extension needs."

add WikiForum

---

LocalSettings.php

add WikiForum (to index+entropedia)

---

LocalSettings.php

DO NOT MERGE WITHOUT ASKING @Southparkfan

add SocialProfile to adnovumwiki per req

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php

change mobilefront end from globalextensions.php to localsettings.php default => true,
add MobileFrontend and MsUpload variables, enable msupload on izanagiwiki and disable mobilefrontend
enable VE on izanagiwiki

izanagiwiki changes

---

LocalSettings.php

Per : "7:36 PM <•SPF|Cloud> After the 9th it can be removed"

remove dormancy policy sitenotice

---

LocalSettings.php

add scribunto to tyrolmountainswiki per req

---

LocalSettings.php

enable VE for cssandjsschoolboard and do // for geshi if it comes back

---

LocalSettings.php

enable nuke for crats testwiki

---

LocalSettings.php

logo,
external link target,
enable VE,
disable anon editing
add "Teachers" group with edit right

vrgowiki changes

---

LocalSettings.php

DO NOT MERGE!!! (SKIN NOT CONFIGURED/INSTALLED)

enable monaco for extload

---

LocalExtensions.php

DO NOT MERGE!!! Also not 100% its done correctly

monaco variable

---

LocalSettings.php

BLOCKED by miraheze/puppet/issues/61

urho3dwiki settings + correct order

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/65

enable VE for luckandlogicwiki per req

---

LocalSettings.php

add NoTitle to extload

---

LocalExtensions.php

sorry for messing up the other req

add notitle variable

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/68

add VE and youtube to webflowwiki per req

---

LocalSettings.php

Passed in one commit. I'm getting better! :)

devwiki settings (groups+enable tabs)

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/71

enable VE on testwiki + make it optional

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/81

add VE to taylorwiki per req (in WikiQueue)

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/82

add VE to hobbieswiki per req

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/90

universebuildwiki settings

---

LocalExtensions.php

Reverts miraheze/mw-config#398

Revert "add ContactPage variable"

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/98

newtrendwiki VE

---

LocalSettings.php

make VisualEditor beta for ATT

---

LocalSettings.php

Per #399, sorry for not putting it in the other PR

add MSUpload to ATT

---

LocalExtensions.php

Do not merge until the extension gets installed.

add Poll variable

---

LocalSettings.php

Do not merge until extension is installed.

add Poll to extload

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/104

add VE to hftqmswiki per req

---

LocalSettings.php

Blocked by miraheze/puppet#111.
I originally intended to directly pushing it but I coincidentally started reinstalling OS.
Will be merged right away, no touch needed.

Add oyeavdelingenwiki for VE

---

LocalExtensions.php
LocalSettings.php

This is my first add of an extension, so it's review time.

Add Extension:HighlightLinksInCategory to extloadwiki

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/113

add VE to nidda23wiki per req

---

LocalSettings.php

add youtube to freecollegeprojectwiki per req

---

LocalSettings.php

Requested at https://meta.miraheze.org/wiki/Request_features#ErnaehrungsratHH_.28Status:_Open.29

Adding Visual Editor and Flow ernaehrungsrathh

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/120

add VE to foodsharinghamburgwiki per req

---

LocalSettings.php

https://meta.miraheze.org/wiki/Request_features#Diccionari_de_ficci.C3.B3_.28Status:_Open.29 (Flow is already enabled, so changes to Parsoid are not necessary I think)

Adding Visual Editor and logo for dicficwiki

---

.github/CONTRIBUTING.md
README.md

As per the IRC discussion.
Review please. :D

Add contributing guidelines

---

LocalSettings.php

https://meta.miraheze.org/wiki/Request_features#LittleBigPlanet_Wiki_.28Status:_Open.29
Parsoid should be configured before merging.

Adding Visual Editor for littlebigplanetwiki

---

LocalSettings.php

Re-done because there were conflicts

stellachronicawiki settings

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/126

add VE for aacenterpriselearningwiki

---

LocalSettings.php

BLOCKED BY miraheze/puppet/issues/127

touhouenginewiki VE, Flow, AdminLinks

---

LocalSettings.php

Parsoid config is already existent.

add Flow to ezdmfwiki per req

---

LocalSettings.php

blocked by miraheze/puppet/issues/134

snowthegamewiki settings

---

LocalExtensions.php

add RandomSelection

---

LocalSettings.php

blocked by miraheze/puppet/issues/137

VE, Flow, AdminLinks, logo for yggdrasilwiki

---

LocalSettings.php

mynametrix i have new account github and trypr

update my wiki

---

LocalSettings.php

Blocked by miraheze/puppet#141.
Will self-merge when ^ is merged.

Turn VE on

---

LocalSettings.php

Fixes T321.
Will self-merge when miraheze/puppet#146 is merged.

Enable VE for maiasongcontestwiki

---

LocalSettings.php

As is seems that bureaucrat can't add normal permissions, added per request.

studynotkrwiki settings

---

LocalSettings.php

blocked by miraheze/puppet/issues/147

add VE to civitaswiki per req

---

LocalSettings.php

add idwiki test

---

LocalSettings.php

imstswiki VE (WAITING FOR PUPPET)

---

LocalSettings.php

upload logo

---

LocalSettings.php

Setting usergroup for wikiid test

setting usergroup

---

LocalSettings.php

Enable Visual Editor for Cisowiki

enable VE for cisowiki

---

LocalSettings.php

upload logo for burnoutwiki

---

LocalSettings.php

add xof in sintax highligh

---

LocalSettings.php

VE for ofthevampirewiki

---

LocalSettings.php

This pull request has been done directly without opening a feature request. Should we open a feature request every time we want an extension to be enabled or is it OK to do a pull request like this one?
Thanks a lot.

Add visual editor to Wikihoyo

---

LocalSettings.php

blocked by miraheze/puppet/issues/161

add VE to inazumaelevenwiki

---

LocalSettings.php

Parsoid is already done (previously).

add Flow to soshomophobiewiki per req

---

LocalSettings.php

https://phabricator.miraheze.org/T430

Enable VE on skyfireflyff.mh.o

---

LocalSettings.php

Not sure if it's done correctly (place and settings)

add settings for WC for ATT

---

LocalExtensions.php

MSCalendar is installed on miraheze/mediawiki

add MSCalendar

---

LocalSettings.php

enable MSCalendar on wikis

---

LocalSettings.php

add CollapsibleVector and CharInsert to wisdomwiki per req

---

LocalSettings.php

https://phabricator.miraheze.org/T459

enable BetaFeatures for inazumaelevenwiki per req

---

LocalSettings.php

https://phabricator.miraheze.org/T456

add GeShi to sourcewiki per req

---

LocalSettings.php

https://phabricator.miraheze.org/T458

enable Metrolook on thelonsdalebattalionwiki per req

---

LocalSettings.php

activating 8 extenstions, 
enabling subpages for new namespaces

activate extensions and subpages for NS

---

LocalSettings.php

user shouldnt edit dditec per req

---

LocalSettings.php

change favicon for astrowiki per req

---

LocalSettings.php

T485
blocked by miraheze/puppet/issues/175

enable VE for gncwiki per req

---

LocalSettings.php

blocked by miraheze/puppet/issues/176

add SyntaxHighlight and VE to xdjibiwiki per req

---

LocalSettings.php

Change Metrolook settings and read-only. T479

change settings for thelonsdalebattalionwiki per req

---

LocalSettings.php

T490
blocked by miraheze/puppet/issues/177

add VE to 3dicxyzwiki per req

---

LocalSettings.php

subpages in NS_MAIN and NS_TEST

activating subpages in sandboxWW

---

LocalSettings.php

restrict admin/user editing on oncprojectwiki per req

---

LocalSettings.php

https://phabricator.miraheze.org/T442 . Founder confirmed on-wiki: https://wima.miraheze.org/w/index.php?title=Benutzer_Diskussion:Kruegerj&diff=173&oldid=169

add AccessControl to wimawiki per req

---

LocalSettings.php

Add a logo to plazmaburstwiki(FIXED)

Add plazmabusrtwiki logo(FIX)

---

LocalSettings.php

per miraheze/puppet/pull/178
T505

add VE and settings to frontdeskswiki per req

---

LocalSettings.php

add SyntaxHighlight to partupwiki per req

---

LocalSettings.php

hydrawikiwiki namespaces

---

LocalSettings.php

T514
blocked by miraheze/puppet/issues/179

ad VE to videogameswiki per req

---

LocalSettings.php

add VE to ageofimperialismwiki per req

---

LocalSettings.php

add VE to aurcusonlinewiki per req

---

LocalSettings.php

set WgExternalLink to _blank for yacresourceswiki per req

---

LocalSettings.php

added +imagemap, +popups and +title key,
turned off -admin links (not individually configurable) and -sectionhide, (irritating jump to top when hide) 
added uploadable filetypes according to IRC

tweaking of WW + WWsandbox

---

LocalSettings.php

add 'commentadmin' right to admins on studynotekrwiki per req

---

LocalSettings.php

This is written by @labster , just trying to speed things up a bit

add Global Sitenotice for Miraheze's anniversary

---

LocalExtensions.php
LocalSettings.php

blocked by https://github.com/miraheze/mediawiki/pull/31

enable LinkSuggest

---

LocalSettings.php

add VE to menufeedwiki per req

---

LocalSettings.php

T536
BLOCKED BY miraheze/puppet/pull/185

thehushhushsagawiki settings

---

LocalSettings.php

add Glossary namespace to thelonsdalebattalionwiki per req

---

LocalSettings.php

T542
blocked by miraheze/puppet/issues/187

BetaFeatures and VE for youtubewiki per req

---

LocalSettings.php

remove LinkSuggest and Translate from ATT per req

---

LocalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#622

Revert "add RelatedArticles"

---

LocalExtensions.php
LocalSettings.php

add RelatedArticles

---

LocalSettings.php

add BlogPage (and dependencies) to robloxscripterswiki per req

---

LocalSettings.php

add SyntaxHighlight to spacegamewiki per req

---

LocalSettings.php

add "Sprites" namespace to whentheycrywiki per req

---

LocalSettings.php

enable VE on opengovpioneerswiki per req

---

LocalSettings.php

add youtube to inazumaelevenwiki per req

---

LocalSettings.php

add thelonsdalebattalionwiki to Apex per req T458

---

LocalSettings.php

add VE to tcc6640wiki per req T574

---

LocalSettings.php

add VE to lingnlangwiki per req

---

LocalSettings.php

change stellachronicawiki skin back to Vector T579

---

LocalSettings.php

Enable WikiForum for starsetonline per [T578](https://phabricator.miraheze.org/T587)
'starsetonline' => true,

Add WikiForum to starsetonline

---

LocalSettings.php

Add VE to bmedwiki, need to now change parsoid

Add VE to bmedwiki

---

LocalSettings.php

add Apex, Metrlook and Foreground to inazumaelevenwiki per req T590

---

LocalSettings.php

Add AccessControl for mindgearwiki
https://phabricator.miraheze.org/T589#8580 - confirmation of responsibility
Founder may also need to post a note on their own wiki: https://mindgear.miraheze.org - please check before merging

Add AccessControl for mindgearwiki

---

LocalExtensions.php
LocalSettings.php

DO NOT MERGE until the extension is installed on /mediawiki

add LabledSectionTransclusion

---

LocalSettings.php

T606 
blocked by miraheze/puppet/pull/212

add dalarwiki to VE per req T606

---

LocalSettings.php

blocked by miraheze/puppet/issues/214

add VE to ageofimperialistswiki per req on RequestWikiQueue

---

LocalSettings.php

add VE to oncprojectwiki per req T618

---

LocalExtensions.php
LocalSettings.php

Wait for /mediawiki and LocalSettings.php !

add googleAnalytics

---

LocalSettings.php

Enable HeaderTabs on dtswiki 

---

LocalSettings.php

Change default skin to metrolook on dtswiki

---

LocalSettings.php

@NDKilla @Southparkfan Please confirm that this is done correctly.

add pagelang settings to spiralwiki per req T627

---

LocalSettings.php

is widgets now open for all? in that case id like the google-calendar and others...
customnavblocks seems to mess things up badly, and does not provide user-end customization as i though it would, hence deleted.
further pdfEmbed activated.
ty.

wisdomwiki + sandbox

---

LocalSettings.php

@NDKilla @labster Please confirm that I have the correct license (per T633).

change license on tamakiwiki per req T633

---

LocalSettings.php

add VE and Youtube to janesskillspackwiki per req

---

LocalSettings.php

pending miraheze/puppet/issues/231

add zenbuddhism.info 

---

LocalSettings.php

Reverts miraheze/mw-config#686
Wiki does not work. Possible cert error

Revert "add zenbuddhism.info "

---

LocalSettings.php

Reverts miraheze/mw-config#687

Revert "Revert "add zenbuddhism.info ""

---

LocalSettings.php

blocked by miraheze/puppet/issues/232

add VE to wthsapgovwiki per req T669

---

LocalExtensions.php
LocalSettings.php

waiting for /mediawiki repo approval and merge

add RSS extension

---

LocalSettings.php

waiting for @labster to check if okay

RSS settings

---

LocalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#696
Wikis down.

Revert "add 	$wgFlowEditorList = $wmgFlowEditorList"

---

LocalExtensions.php
LocalSettings.php

add Maps to localextensions

---

LocalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#723

Revert "add Maps to localextensions"

---

LocalExtensions.php
LocalSettings.php

add ContentTranslation

---

LocalSettings.php

Reverts miraheze/mw-config#799

Revert "Reenable MediaWikiChat on extloadwiki"

---

LocalSettings.php

enable VoteNY (espiralwiki) T885

---

LocalSettings.php

Redo #832 as the tabs aren't well done.

enable wgAllowCopyUploads (applewikiwiki) T791

---

LocalSettings.php

disable InstantCommons (pso2wiki) T883

---

LocalSettings.php

waiting for miraheze/puppet/issues/272 (parsoid)

enable VE + Blog page (wikidolphinhansenwiki) T899

---

LocalSettings.php

waiting for miraheze/puppet/issues/273

enable VE (corydoctorowwiki) T903

---

LocalSettings.php

waiting for miraheze/puppet/issues/274

enable VE (purpanrangueiluswiki) T904

---

ContactPage.php
LocalSettings.php

Hi here is my change for my wiki.
- VisualEditor
- ContactPage
- Feedback
Also how can we change the default language of the wiki? I accidently choose frc instead of fr.
Thanks!

Change to fablabesds

---

LocalSettings.php

waiting for miraheze/puppet/pull/277

enable VE + change logo + disable anon editing (karniarutheniawiki) T902

---

LocalExtensions.php
LocalSettings.php

add Nostalgia for T799

---

LocalSettings.php

waiting for miraheze/puppet/pull/280

enable VE (easywikiwiki) T928

---

LocalSettings.php

waiting for miraheze/puppet/pull/284

enable VE (mikrodevwiki) T936

---

LocalSettings.php

permission changes (trexwiki)

---

LocalSettings.php

Per labsters comment [here](https://phabricator.miraheze.org/T901)

Test refreshed on applewikiwiki

---

LocalSettings.php

Reverts miraheze/mw-config#868

Revert "Test refreshed on applewikiwiki"

---

LocalSettings.php

add "Portal" namespace (noalatalawiki) T958

---

LocalSettings.php

waiting for miraheze/puppet/pull/286 to be merged.

enable VE (apneuverenigingwiki) T962

---

LocalSettings.php

waiting for miraheze/puppet/pull/291

enable VE (gzewiki) T957

---

LocalSettings.php

waiting for miraheze/puppet/pull/289

enable VE (wabcwiki) T964

---

LocalSettings.php

Not entirely sure if everything is correctly done

settings for FlaggedRevs (pso2wiki) T970

---

LocalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#926

Revert "Change refreshed to wfload"

---

LocalSettings.php

Change rpgbrigadewiki logo

---

LocalSettings.php

Reverts miraheze/mw-config#938

Revert "Add namespaces for flaggedrevs for T1014"

---

LocalSettings.php

localsettings.php changed to reflect this

Enabling boilerplates and newestusers for muckhack

---

LocalSettings.php

localsettings edited for this to take place

newusermessage for muckhack

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php

Move Inputbox to global extensions.php

---

LocalExtensions.php

Checked for extension.json for all the extensions changed

change possible extensions to wfLoad

---

LocalExtensions.php

Reverts miraheze/mw-config#970

Revert "change possible extensions to wfLoad"

---

LocalSettings.php

Reverts miraheze/mw-config#989

Revert "Load ManageWiki on metawiki"

---

LocalSettings.php

Update trexwiki (please merged first)

---

LocalSettings.php

Waiting for miraheze/puppet/pull/316

enable VE + change logo (wikipucwiki) T1051 & T1052

---

LocalSettings.php

remove Variables enable VE (wikipucwiki) T1051

---

LocalSettings.php

Reverts miraheze/mw-config#991

Revert "Revert "Load ManageWiki on metawiki""

---

LocalSettings.php

add read permission to create founder group (wikicanadawiki)

---

LocalSettings.php

add Portal NS (ratanpirwiki) T1068

---

LocalSettings.php

Restore read access for non-logged in users per https://phabricator.miraheze.org/T1078

Read access for non-logged in users on wikicanadawiki per T1078

---

LocalSettings.php

Reverts miraheze/mw-config#1051

Revert "Change DB server to db2"

---

LocalExtensions.php
LocalSettings.php

add ProtectSite for T1064

---

LocalSettings.php

Userrights on wikicanadawiki

---

LocalSettings.php

rm sitenotice

---

LocalSettings.php

Update for ganesha wiki

---

LocalSettings.php

enable VE (trumpwiki) T1150

---

LocalSettings.php

Re-do request #1111 
I know that everything is supposed to be in alphabetical order, but does it really break anything if they aren't? Also, I have granted bureaucrat the ability to add founder so that I can add myself, but this will be removed after I am in the founder group.

Re-do request #1111

---

LocalSettings.php

Don't have a clue what this user right is supposed to do - seems nonexistent to me

Found another one

---

LocalWiki.php

Reverts miraheze/mw-config#1129

Revert "Bureaucrats can now manage a few user groups"

---

LocalSettings.php

I believe that there is more to do than this, but this is all I know how to do

Enable Flow on Elements wiki for T1207

---

LocalSettings.php

But it doesn't have access to any restricted interfaces, so....

Not exactly sure what this right is for

---

LocalSettings.php

Reverts miraheze/mw-config#1139

Revert "Not exactly sure what this right is for"

---

LocalWiki.php

Remove extra user group

---

LocalSettings.php

Added namespace and enabled extensions for calexitwiki

Calnation patch 3

---

LocalSettings.php

Scratch that - I changed my mind

Revert "Custom protection on elementswiki per T1226"

---

LocalWiki.php

fix brynda1231wiki (fix T1237 per 4f0285829e1e )

---

LocalWiki.php

Also removed whitespace from the elementswiki block

limit page creation on intpwiki per T1249

---

LocalExtensions.php

per note on T1310, at least someone needs this right to use the extension

allow sysops to create polls

---

LocalSettings.php

Adding VisualEditor for https://xdwxsty.miraheze.org/

---

LocalSettings.php

also includes requested template data

visual editor on titaniawiki per T1332

---

LocalSettings.php

bump ns numbers by 2

---

LocalSettings.php

Seems the first time i didn't put the pull request all the way through - so I've updated the [instructions](https://meta.miraheze.org/wiki/Tech:Change_a_wiki's_logo). 
The 2nd time i seem to have scrolled up and put the logo in the favourite icon section. Useful, but not quite what i meant to do.
Third time lucky: logo update in the wgLogo array.

change bchwiki logo

---

LocalSettings.php

restrict anon editing since emailconfimed is defunct to my knowledge

config on prfmukwiki per T1519

---

LocalSettings.php

Added FabLabESDS logo

---

LocalSettings.php

don't restrict user editing until emailconfirmed works as intented

begin reimplementation for T1568

---

LocalSettings.php

settings for bitcoindebateswiki T1568

add autopromotion settings and implicit groups

---

LocalSettings.php

emailconfirmed cannot be achieved when they need to edit to be able to edit :P

editing restrictions on bitcoindebateswiki per T1568

---

LocalSettings.php

Add new namespace to tmewiki

---

LocalSettings.php

Required for ImportBot to work properly

Add editinterface to bot on WikiCanada

---

LocalSettings.php

add VisualEditor per request T1687

---

LocalSettings.php

I've decided against using these extensions on second thought

Remove ABW and MediaWiki Chat extensions

---

LocalSettings.php

The only bot that needed this right is broken

Remove editinterface from bot on WikiCanada

---

LocalSettings.php

We wish to display external images and other media on our site as to comply with copyright law for copyrighted material. Our admin, Ithiloneth ahs spoken to a +JohnLewis on the Miraheze IRC about this to get a feel for whether it might be appropriate or not before asking for this pull.

Setting Westmarcheswiki to allow external images.

---

LocalSettings.php

Change <esctwiki> logo

---

LocalSettings.php

This is based on a previous pull request which was closed and unable to be re-opened.
Please see here for confirmation of leak responsibility denial notice on our Wiki: https://westmarches.miraheze.org/wiki/Main_Page

Enable AccessControl on Westmarches

---

LocalSettings.php

Reverts miraheze/mw-config#1422

Revert "Enable WikiBase on artificercreationswiki per T1725"

---

LocalWiki.php

if there is a simpler fix, let me know

prevent unintended override

---

LocalSettings.php

I have added some settings for "PruebaWiki", including the FlaggedRevs extension and the creation of the "test" group. I request that the changes be merged into the repository. Thanks.

Addition of More Settings for "PruebaWiki"

---

LocalSettings.php
LocalWiki.php

Allow all logged in users to read pages and unset restricted member group

Loosen private wiki read restriction

---

LocalSettings.php

**Please don't accept this pull request if this will make it the default theme!** I want to test it before.
Thanks!

Enable BootstrapMediawiki Skin on FabLabESDS

---

LocalSettings.php
LocalWiki.php

Reverts miraheze/mw-config#1454
Flow is not working properly

Revert "Convert WikiCanada talk pages to Flow"

---

LocalSettings.php

Kind of goes hand in hand with Special:UnwatchedPages

Enable WhoIsWatching on WikiCanada

---

LocalSettings.php

I made some adjustments with the extension FlaggedRevs in "PruebaWiki". Thanks.

Fix Settings of "PruebaWiki"

---

LocalSettings.php

Fix Settings for FlaggedRevs in "PruebaWiki". Thanks.

Fix Settings in "PruebaWiki"

---

LocalSettings.php

Fix Settings for FlaggedRevs Extension on "PruebaWiki". Sorry for the repeated pull requests, but I've needed to see live configurations to know what they consist of and see how well they are. Thanks,

Fix Settings for "PruebaWiki"

---

LocalSettings.php

Disabling PageNotice as it didn't do what I wanted
Disabling TorBlock as the most recent vandalism has not been from TOR

Disable extensions on WikiCanada

---

LocalSettings.php

Reverts miraheze/mw-config#1460

Revert "Enable WhoIsWatching on WikiCanada"

---

LocalSettings.php

Remove WhoIsWatching

---

LocalSettings.php

Addition of Logo for "breedersofthenephelymwiki" for Request by Simonh1 on IRC. Thanks.

Addition of Logo for "breedersofthenephelymwiki"

---

LocalSettings.php

Addition of Maps Extension on "jacksonheightswiki" for Phabricator Task [T1784](https://phabricator.miraheze.org/T1784). Thanks.

Addition of Maps Extension on "jacksonheightswiki" for T1784.

---

LocalSettings.php

Requires https://github.com/miraheze/parsoid/pull/34 to be merged first.

Enable VisualEditor/Main Namespace Subpages for raymanspeedrun

---

LocalWiki.php

Addition of Settings for "PruebaWiki" (Remotion of "nuke", "ipblock-exempt" and "globalblock-whitelist" for administrators and remotion of autoreview user permission). Thanks.

Addition of Settings for "PruebaWiki"

---

LocalSettings.php

Update Settings for "PruebaWiki" (Remotion of "autoreview user" permission and addition of possibility of add/remove permissions of the Education Program extension to the consuls). Thanks.

Update Settings for "PruebaWiki"

---

LocalSettings.php

Addition of Logo for "bootstrappingwiki" for Request in [T1819](https://phabricator.miraheze.org/T1819). Thanks.

Addition of Logo for "bootstrappingwiki" for T1819

---

LocalSettings.php

Remotion of "Autoreview User" Permission. Thanks.

Remotion of "Autoreview User" Permission

---

LocalSettings.php

Fixing an error on isvwiki (accuracy to status)

---

LocalSettings.php
LocalWiki.php

LocalSettings.php:
- Removed isvwiki from wmgFlaggedRevsProtection
- Added unreviewedpages to confirmed group at isvwiki
LocalWiki.php:
- Fixed alphabetic sorting
- Disabled $wgSimpleFlaggedRevsUI for isvwiki

Various fixes for isvwiki

---

LocalSettings.php

Addition of DynamicPageList and Labeled Section Transclusion extensions in "sidemwiki" for Request in [T1828](https://phabricator.miraheze.org/T1828). Thanks.

Addition of Extensions in "sidemwiki" for T1828

---

LocalSettings.php

Enable CharInsert Extension in "recentiawiki" for Request in [T1864](https://phabricator.miraheze.org/T1864). Thanks.

Enable CharInsert Extension in "recentiawiki" for T1864

---

LocalSettings.php

Addition of Logo for "sysexwiki" per Request in Phabricator Task [T1874](https://phabricator.miraheze.org/T1874). Thanks.

Addition of Logo for "sysexwiki" per Request in T1874

---

LocalSettings.php

Enable Translate Extension in "mikrodevdocswiki" for Request in Phabricator Task [T1876](https://phabricator.miraheze.org/T1876). Thanks.

Enable Translate Extension in "mikrodevdocswiki" for T1876

---

LocalSettings.php

Change <Embobadawiki> logo

---

LocalSettings.php

enable UNC links by adding updating '+wgUrlProtocols' section

add file:// to private wiki: bchwiki

---

LocalSettings.php

methru would like anons and regular users to be able to read the wiki, just not edit.

T1941 - Editing permissions

---

LocalSettings.php

Let's explain how these work a little bit more because it took me way too long to figure out..
...
Don't judge me.. ;-;

+ Explanation

---

LocalSettings.php

also remove redundancy from CategoryTree

wishwiki config per T1955

---

LocalExtensions.php
LocalSettings.php

**See also: https://github.com/miraheze/mediawiki/pull/87**
This pull request enables the following extensions on isv.miraheze.org:
- EventLogging
- GuidedTour

T1900 - Enable GuidedTours on isv.miraheze.org

---

LocalSettings.php

Just like described here: https://meta.miraheze.org/wiki/Tech:Change_a_wiki's_logo

Adding logo

---

LocalSettings.php

should be everything proxybot needs to function (besides generic bot group)

add proxybot group

---

LocalSettings.php

Is there anything else I have to add?

Enable ImageMap on tme.miraheze

---

LocalSettings.php

handles everything except AccessControl and SocialProfile

thebbwiki extensions per T1958

---

LocalSettings.php

I know this is going to need some proofreading.

Add second-year anniversary

---

LocalSettings.php

Added the ability to enable the VisualEditor Wikitext Editor on The Multilingual Encyclopedia.

TME update

---

LocalSettings.php

Addition of Logo for "girlsfrontlinewiki" (Phabricator Task: T2009). Thanks.

Addition of Logo for "girlsfrontlinewiki" (T2009)

---

LocalSettings.php

T2012: set refreshed off and make apex default

---

LocalSettings.php

Favicon change for Bemin wiki per request T2016. Could you please do a double check that I did it right? I have never changed a wikis logo before.

Favicon change for Bemin Wiki

---

LocalSettings.php

Please merge when everything is ready

anniversary sitenotice

---

LocalSettings.php

Added VisualEditor per request T2019. Just need to change parsoid.

VisualEditor enabling for NYCHousing Wiki

---

LocalSettings.php

Adding a customized logo to my musmyswiki.

Change musmyswiki logo

---

LocalSettings.php

Update local Setting for logo

---

LocalSettings.php

enable NS_TEMPLATE with wgNamespacesWithSubpages

---

LocalSettings.php

Enabling Tabber+Tabs and Youtube for Youtau.miraheze.org per request T2083.

Enabling extensions for youtauwiki

---

LocalSettings.php

Please remember to to replace [] with the time when it's getting upgraded (30 mins+ after the sitenotice is added should be fine IMO)

before 1.29 sitenotice

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#1605

Revert "REL1_29 changes"

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#1654

Revert "Revert "REL1_29 changes""

---

LocalSettings.php

Enabling feu.miraheze.org per request T2094

Enabling VisualEditor for feu

---

LocalSettings.php

Changing logo for lapeninsulewiki

---

LocalSettings.php

Adding Graph and Labelled Section Transclusion per request T2147

Update for unionnorteamericana.miraheze.org

---

LocalSettings.php

voidwiki conf

---

LocalSettings.php

Changing the aibowiki logo

---

LocalSettings.php

flow on oecumenewiki per T2225

---

LocalSettings.php

Change madgendersciencewiki favicon

---

LocalSettings.php

Enable RandomSelection for madgendersciencewiki

---

LocalSettings.php

Addition of "IDEA" Namespace in "revitwiki" for Phabricator Task [T2326](https://phabricator.miraheze.org/T2326).

Addition of "IDEA" Namespace in "revitwiki" for T2326

---

LocalSettings.php

Extension request for aristide.miraheze.org

---

LocalSettings.php

Adding YouTube extension to aristide.miraheze.org

---

LocalSettings.php

Adding Flow to puzzle.miraheze.org

---

LocalSettings.php

Adding logo for Florian Wiki per request T2354.

Updating logo for florianwiki.miraheze.org

---

LocalSettings.php

Please double check if I did it right.

Adding namespaces to tme.miraheze.org

---

LocalSettings.php

Adding extensions for ayurbooks.miraheze.org

---

LocalSettings.php

Adding Wikibase to ayurbooks.miraheze.org

---

LocalSettings.php

Updating logo for hexels.miraheze.org

---

LocalSettings.php

Adding name spaces to voting.miraheze.org

---

LocalSettings.php

I am going to move Wikibase over to my secondary wiki once the Wikibase issues are fixed

Disabling Wikibase on aeross wiki

---

LocalSettings.php

Adding VisualEditor to medicina.miraheze.org

---

LocalExtensions.php
LocalSettings.php
extension-list

Not sure which SQL files to use.

Add Cargo per T1538

---

LocalSettings.php

Adding VE to vicproject.miraheze.org

---

LocalSettings.php

to enable pageforms extension on scruffywiki

to enable pageforms extension on scruffywiki

---

LocalSettings.php

enable MultiBoilerplate for scruffywiki

enable MultiBoilerplate for scruffywiki

---

LocalSettings.php

Updating logo for furbyislandwiki

---

LocalSettings.php

Updating logo for travailcollaboratifwiki

---

LocalSettings.php

for bonobo, scruffy and sdiy wikis

define and add boilerplate namespace

---

LocalSettings.php

for bonobo, scruffy and sdiy wikis

add ExternalLinkTarget = '_blank'

---

LocalSettings.php

Enable Special:Boilerplates

---

LocalSettings.php

* Disable editing by anonymous users on lexiquewiki per request T2431
* Enable VisualEditor for modelshipreferencewiki per request T2432

two changes

---

LocalSettings.php

Updating extensions for enmarche.miraheze.org

---

LocalSettings.php

these are the defaults already

moderation permissions for sdiywiki

---

LocalSettings.php

rm skip-moderation, sdiywiki

---

LocalSettings.php

Enable CSS for firstroboticswikiwiki per request T2480
add AddHTMLMetaAndTitle for valentinaprojectwiki per request T2474

Enable two extensions for two wikis

---

LocalSettings.php

Change zendariwiki logo

---

LocalSettings.php

i just would like to change my wiki-logo

Change <jcswiki> logo

---

LocalSettings.php

I also moved this:
'test1wiki' => true,
...to the bottom of...
'sthomaspriwiki' => true,
...to sort the list of wikis alphabetically.

Use DPL3 on tmewiki

---

LocalSettings.php

small change to the visual editor

wgVisualEditorUseSingleEditTab @ jcswiki --> true

---

LocalSettings.php

This time done correctly.
Depends on miraheze/ssl#3

Custom domain for reviwbwiki

---

LocalSettings.php

Enable labeled section transclusion extension for madgendersciencewiki, please & thanks!

Enable extension for madgendersciencewiki.

---

LocalSettings.php

Add teamwizardrywiki to customdomain

---

LocalSettings.php

Add maktabawiki to customdomain

---

LocalSettings.php

pdfEmbed @ jcswiki

---

LocalSettings.php

i tried to change before, but made 2 changes to fast, so i got asked to made a new pull request!
add: UseNewUsersList
remove: SingleEditTab
Here i am!

UseNewUsersList & SingleEditTab @ jcswiki

---

LocalSettings.php

This reverts commit 709f304d2b787e76cfca5c33ec003ad7702c4ce9.

Revert "read-only all wikis and sitenotice"

---

LocalSettings.php

Sadly UseNewUsersList is only possible by using the extension "SocialProfile" (i dont want to)

remove wmgUseNewUsersList @ jcswiki

---

LocalSettings.php

Changing kirarafantasiawiki logo

Change kirarafantasiawiki logo

---

LocalSettings.php

Added logo for kbrprojectwiki.
Thank you,
Juan Telleria Ruiz de Aguirre

Added: wgLogo for kbrprojectwiki Wiki

---

LocalSettings.php

Disable InstantCommons on jcswiki

Disable InstantCommons on jcswiki

---

LocalSettings.php
LocalWiki.php

I am implementing miraheze phab task 2549. Please do not merge unless all your reviews have been done (obviously). Thank you

Implementing phabricator task T2549

---

LocalSettings.php

I no longer need this ability since consuls are not expected to voluntarily resign now. Thanks

Removing ability to remove consul from self

---

LocalSettings.php

New wgAppleTouchIcon for jcswiki with white background

New wgAppleTouchIcon for jcswiki

---

LocalSettings.php

add some FileExtensions @ jcswiki

wgFileExtensions @ jcswiki

---

LocalSettings.php

also actually enable multimediaviewer

tema ns for cristianopediawiki per T2557

---

LocalSettings.php

Phab Task 2557 asks for a favicon. This change implements it. Reception123 is probably going to handle the creation of a new namespace since I have no idea how to do so.

Add favicon by request

---

LocalWiki.php

doesn't seem to work on non-english versions for some reason

add variant of Special:CreateAccount

---

LocalSettings.php

Disable 'wmgUseMobileFrontend' for 'jawptestwiki'.
Requested by site owner

Update LocalSettings.php:  for jawptestwiki

---

LocalSettings.php

!DO NOT MERGE!
Only merge after 2018-01-25 09:30 UTC!

Enter READONLY

---

LocalSettings.php

Description of https://meta.miraheze.org/wiki/Special:RequestWikiQueue/4304

teatraywiki settings per request

---

LocalSettings.php

add cargo to templatewiki

---

LocalSettings.php
LocalWiki.php

This is a PR to set up a wiki I am bureaucrat on so that it is ready for use. All sysadmins have to do is merge this when ready and I'll take care of the config on wiki. This particular wiki is the LCARS47 wiki.

Wiki Setup

---

LocalSettings.php

Adding VisualEditor to harrypotter.miraheze.org

---

LocalSettings.php

Updating logo for anjuna.miraheze.org

---

LocalSettings.php

disable mobile front end for carmeiwiki

disable mobile front end for carmeiwiki

---

LocalSettings.php

Add logo for my wiki - carmeigat.miraheze.org

Add logo for my wiki - carmeigat.miraheze.org

---

LocalSettings.php

Enable youtube extension for madgendersciencewiki

---

LocalSettings.php

[Extension:Capiunto ](https://www.mediawiki.org/wiki/Extension:Capiunto ), if it has been installed already [T2614](https://phabricator.miraheze.org/T2614)?

enable extension Capiunto

---

LocalWiki.php

otherwise, you are basically just nesting the arrays

convert to array_merge(

---

LocalSettings.php

Requested in T2801. Please note that if possible this [pull request](https://github.com/miraheze/parsoid/pull/106) should be merged/synced before this one takes effect or else there may be wiki errors.

Apply wiki config

---

LocalSettings.php

To install Discord widget pertaining to T2802

Adding Widgets to harrypotter.miraheze.org

---

LocalSettings.php

I also sorted the list alphabetically by rearranging
`'test1wiki' => true,`
onto the spot under
`'speleowiki' => true,`

RSS extension on tmewiki and vandalismwikiwiki

---

LocalSettings.php

Change gupiewiki logo

---

GlobalExtensions.php
LocalSettings.php
extension-list

Reverts miraheze/mw-config#2043

Revert "GlobalUserPage + GlobalPreferences per T1681"

---

GlobalExtensions.php
LocalSettings.php
extension-list

Reverts miraheze/mw-config#2048

Revert "Revert "GlobalUserPage + GlobalPreferences per T1681""

---

GlobalExtensions.php
LocalSettings.php
extension-list

Reverts miraheze/mw-config#2050

Revert "Revert "Revert "GlobalUserPage + GlobalPreferences per T1681"""

---

GlobalExtensions.php
LocalSettings.php

Reverts miraheze/mw-config#2051

Revert "Revert "Revert "Revert "GlobalUserPage + GlobalPreferences per T1681""""

---

LocalSettings.php

Disabling QuizGame at allthetropes.org

---

LocalSettings.php

add new namespaces, correcting errors in namespaces on unionwiki and wiki1776wiki. per req T2853 and T2860

add newnamespaces, correcting errors on unionwiki and wiki1776wiki

---

LocalSettings.php

Updating logo for yokaiwatch.miraheze.org

---

LocalSettings.php

enable extensions on yourtechnicalservicewiki per req T2884 and T2883

---

LocalSettings.php

remove the extensions PageTriage and SiteScout, enable QuizGame and WikiForum.

Changes in extensions on allthetropeswiki per req T2710

---

LocalSettings.php

add VisualEditor for itspuglewiki

---

LocalSettings.php

Add Youtube extension for pieskysoftwiki

---

LocalSettings.php
LocalWiki.php

1. Moved flow-hide permission from all to autoconfirmed in isvwiki
2. Removed legacy forum talk namespace protection in isvwiki

Move flow-hide permission to autoconfirmed in isvwiki

---

LocalSettings.php

Changing logo for caracteremouwiki

Change caracteremouwiki logo

---

LocalSettings.php

YT on catacomb wiki

---

LocalSettings.php

Reverts miraheze/mw-config#2172

Revert "Set read only mode for all wiki's"

---

LocalSettings.php

ContributionScores on vandalismwiki

---

LocalSettings.php

I'm not sure if adding new lines is allowed but I wanted to configure the SocialProfile extension a bit.
default settings based of how it seems to be set

avalicearchiveswiki, SocialProfile configuration

---

LocalSettings.php

Change adminbuswiki logo

---

LocalSettings.php

Need to change my wiki's (gcp711wiki) logo.

Changing logo for gcp711wiki

---

LocalSettings.php

change default skin to monobook for gcp711wiki

---

LocalSettings.php

Also remove developmentwiki as it has been deleted.

remove NewUserMessage from wikis T2976

---

LocalSettings.php

translate on reservedurablewiki per T2924

---

LocalSettings.php

Logo change for bennubennuwiki

Change bennubennuwiki logo

---

LocalSettings.php

add SyntaxHighlight for unixhaterswiki

---

LocalSettings.php

Disallowing anonymous users from editing the jadtechwiki.

Anonymous users no edit rights on jadtechwiki

---

LocalSettings.php

We are preparing to import from another project, so I need an extra namespace to make this work.

Add an extra namespace to isvwiki

---

LocalSettings.php

please enable translate extension for my wiki "rxywiki" (rxy.miraheze.org)

LocalSettings.php: enable wmgUseTranslate @rxywiki

---

LocalSettings.php

delete block that shouldn't be used

remove sitenotice

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php

This is due to the gdpr comming into force on the 25 of may 2018.

Enable CookieWarning globally

---

LocalSettings.php

add anon, user, editor, sysop on SiteMatrix for ezidiawiki

---

LocalSettings.php

Reverts miraheze/mw-config#2262

Revert "Set read-only"

---

LocalSettings.php

Reverts miraheze/mw-config#2263

Revert "Revert "Set read-only""

---

LocalSettings.php

add DP exemption to marketingspecialswiki

---

LocalSettings.php

Per request T3335.
Also put namespace list for said wiki in alphabetical order.

Updating wikibookwiki namespaces

---

LocalWiki.php

Not sure why its making me do this as a separate PR

LocalWiki.php

---

LocalSettings.php
LocalWiki.php

On second thought/reconsideration, this group isn’t really going to be useful.

Remove Weather Wiki account creator group

---

LocalSettings.php

- Changed bad forum namespace, conflicting with extension namespace
- Replaced custom namespaces with polish names
- Added content namespaces

Fixes for Nonsensopedia custom namespaces

---

LocalSettings.php
ManageWiki.php

Add ScratchBlocks to ManageWiki

---

LocalExtensions.php
LocalSettings.php
ManageWiki.php
extension-list

Add GeoCrumbs to ManageWiki

---

LocalSettings.php

disable wgMSU_checkAutoCat on repositoriowiki

---

LocalWiki.php

Make repositoriowiki a repository for images like commons

---

LocalSettings.php

First change in my wiki configuration.

Allow external images on Sitradu Wiki

---

LocalSettings.php

Otherwise it will appear twice on commonswikiwiki

Exclude commonswikiwiki from shared image repo config

---

LocalExtensions.php
LocalSettings.php
ManageWiki.php
extension-list

chameleon depends on bootstrap

Add chameleon to manage wiki fixes T3388

---

LocalExtensions.php
LocalSettings.php
ManageWiki.php
extension-list

Reverts miraheze/mw-config#2351

Revert "Add chameleon to manage wiki fixes T3388"

---

LocalSettings.php

per email request to stewards@

exempt sawikiwiki from dormancy

---

ManageWiki.php

[Need review] add extension Moderation on Special:ManageWikiExtensions

---

ManageWiki.php

Reverts miraheze/mw-config#2383

Revert "[Need review] add extension Moderation on Special:ManageWikiExtensions"

---

LocalExtensions.php

Newsletters should be restricted to approved users - no random confirmed user should be able to manage newsletters

Remove newsletter-create from confirmed

---

LocalSettings.php

So, I think I disabled edit rights for users on enigma.miraheze.org? Then I tried to create a new user group called "scribe". I actually don't know if what I did was correct, so please correct me if I did anything wrong.

UserRights for enigmawiki

---

LocalSettings.php

Cleaning up groups that I carried over from WikiCanada during initial wiki setup, but are unlikely to be used until the wiki really delvelops and therefore for now are just cluttering things

rem researcher group from weatherwiki

---

LocalSettings.php

Reverts miraheze/mw-config#2410

Revert "piwik.miraheze.org -> matomo.miraheze.org"

---

LocalSettings.php

Reverts miraheze/mw-config#2411

Revert "Revert "piwik.miraheze.org -> matomo.miraheze.org""

---

LocalExtensions.php
LocalSettings.php
ManageWiki.php
extension-list

Not sure is all correct but normally is good :)
Task: T3492

Add WikimediaIncubator

---

LocalSettings.php

Redo #2442

---

LocalSettings.php

**[Needs Review Before Approval]**

[Needs Review Before Approval] add tallercentralwiki on wgExtraInterlanguageLinkPrefixes

---

LocalSettings.php

I'm not sure about how I exactly have add them in here

avalicearchiveswiki: Two extra namespaces

---

LocalWiki.php

based on  #[2340 ](https://github.com/miraheze/mw-config/pull/2340) y #[2505](https://github.com/miraheze/mw-config/pull/2505)

[Review] Make mediatecawiki a repository for images like commons per Ucronistaw

---

LocalSettings.php
ManageWiki.php

But only allow restricted users to enable it.

Move WikimediaIncubator to ManageWiki

---

LocalSettings.php

[Needs Review] add $wgWPBNamespaces on apunteswiki, centralwiki, destinoswiki, infowiki, mediatecawiki, privadowiki, tallerwiki, ucroníaswiki

---

Sitenotice.php

otherwise you risk having users miss later notices

maintain sitenotice id

---

LocalSettings.php

Reverts miraheze/mw-config#2553

Revert "Set all wikis to write to actor (no longer read and write to both)"

---

LocalSettings.php

Reverts miraheze/mw-config#2554

Revert "Revert "Set all wikis to write to actor (no longer read and write to both)""

---

LocalWiki.php

Remove new RC stuff

---

LocalSettings.php

add extensions file for cmgi wiki

update ls for cmgi wiki

---

LocalSettings.php

crazybloxianempireinfowiki namespace subpages

---

LocalSettings.php

Getting issues with SVG files. Same error as T3278, this hopefully will resolve the issue.

Upping SVGMetadataCutoff for magnaverse

---

LocalSettings.php

Update nonciclopediawiki namespaces ref T3754

---

LocalSettings.php

per discussion on CN
https://meta.miraheze.org/w/index.php?title=Community_noticeboard&oldid=63887#Add_a_few_interwiki_prefixes_to_Nonciclopedia

nonciclopediawiki wgExtraInterlanguageLinkPrefixes

---

LocalExtensions.php
LocalSettings.php
ManageWiki.php
extension-list

Add PortableInfobox to ManageWiki

---

GlobalExtensions.php
extension-list

Per Phabricator task [T3948](https://phabricator.miraheze.org/T3948)

Make MobileDetect available as a global extension

---

LocalSettings.php

Reverts miraheze/mw-config#2591

Revert "setup iwwiki"

---

LocalExtensions.php
LocalSettings.php
ManageWiki.php
extension-list

Allow Genealogy to be used as a local extension (T3881)

---

LocalSettings.php

revoke editothersprofiles

---

LocalSettings.php

Reverts miraheze/mw-config#2618

Revert "revoke editothersprofiles"

---

LocalSettings.php

the only alternative is to merge wgRestrictionLevels into wgAdditionalRights

add crat right to crats on hypopediawiki T4049

---

LocalSettings.php

Reverts miraheze/mw-config#2630

Revert "set a default for wgMobileUrlTemplate"

---

LocalExtensions.php

require captcha on wikiforum

---

LocalSettings.php

In addition I remove configuration, they are already enabled in ManageWikiStettings.

enable wgMSU_showAutoCat on anotheredenwiki and browndustwiki per T4209

---

LocalSettings.php
ManageWikiSettings.php

also do a whole bunch of spelling/grammar changes to the help messages

add WikiForum settings

---

ManageWikiExtensions.php

Reverts miraheze/mw-config#2693

Revert "Add missing sql to WikiForum"

---

LocalSettings.php

add editrepo protection for rf1botwiki

---

ManageWikiSettings.php

per IRC
@Reception123 / @paladox

Remove MobileFrontendAutoDetect

---

LocalSettings.php
ManageWikiExtensions.php
extension-list

Remove Extension:Poll

---

ManageWikiSettings.php

ManageWikiNamespaces --> ManageWiki/namespaces

Correction(s)

---

ManageWikiSettings.php

consistency

---

ManageWikiExtensions.php

as doesn't work as will always be in mobile view

// out tweeki

---

ManageWikiSettings.php

rmv duplicate

---

Database.php

not sure why last time Paladox tried to add db5 it caused errors so waiting for approval from @JohnFLewis and/or @paladox before merging.

enable db5 wikis and add testwiki to db5

---

LocalWiki.php

Remove config no longer needed per request

---

LocalSettings.php

make NS_MAIN index on horizonwiki

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

add 4 exts to test1

---

ManageWikiExtensions.php

a weak +1 from me
See IRC for why

enable stopforumspam in prod

---

ManageWikiExtensions.php

Reverts miraheze/mw-config#2742

Revert "enable stopforumspam in prod"

---

LocalSettings.php
ManageWikiExtensions.php

revert #2739

---

LocalSettings.php
ManageWikiExtensions.php

move SoftRedirector to prod (was test1)

---

LocalSettings.php

Reverts miraheze/mw-config#2754
Test done - Not fully sure what impact this has - Will look in detail later

Revert "test UserProfileDisplay"

---

LocalSettings.php
ManageWikiExtensions.php

move 3 extensions to prod

---

LocalSettings.php
ManageWikiExtensions.php

Reverts miraheze/mw-config#2759
Fixing i18n

Revert "move 3 extensions to prod"

---

LocalSettings.php

Put several wikis in read only mode for migration (T4724)

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Add HeaderFooter extension to MW

---

LocalSettings.php

Fix description url for commons.miraheze.org

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Extension now unmaintained and does not support 1.34+

Remove EducationProgram extension

---

ManageWikiSettings.php

Reverts miraheze/mw-config#2826
didn't know it was blocked on extra config

Revert "add wgPopupsGateway to ManageWiki; fixes T4855"

---

LocalSettings.php
ManageWikiSettings.php

It needs thorough revision! It may have errors.

wgMinervaEnableSiteNotice  on ManageWiki per T5057

---

LocalExtensions.php
LocalSettings.php
ManageWikiSettings.php

Support site notices under mobiles

---

LocalExtensions.php
LocalSettings.php
ManageWikiSettings.php

Reverts miraheze/mw-config#2849

Revert "Support site notices under mobiles"

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php

Collection already does this but we were duplicating things by allowing users to enable it separately.

Enable electron if collection is enabled

---

LocalSettings.php
ManageWikiSettings.php

Add wgDiscordNotificationNewUser to ManageWiki

---

GlobalExtensions.php
LocalSettings.php

Globally install SpamBlacklist

---

LocalSettings.php
LocalWiki.php

Add wgExtraSignatureNamespaces to managewiki

---

LocalSettings.php

Reverts miraheze/mw-config#2870

Revert "Fix wgManageWikiNamespacesAdditional"

---

GlobalLogging.php

We no longer want to set this.

Remove wgDebugLogFile

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php
LocalWiki.php

This is a workaround to disable the notice for misc3.

Put CookieWarning behind wmgCookieWarningEnabled

---

GlobalExtensions.php
LocalExtensions.php
LocalSettings.php
LocalWiki.php

Reverts miraheze/mw-config#2875

Revert "Put CookieWarning behind wmgCookieWarningEnabled"

---

LocalSettings.php

Fix wgExtraSignatureNamespaces

---

Database.php

db5 is no longer use, remove it.

database: Remove db5

---

LocalSettings.php

Reconfigurations on Hispanowiki, Privadowiki and Ucroniaswiki

---

LocalSettings.php

Adding restriction levels for wikitestwiki

---

LocalSettings.php

This reduces duplicated foreach.

Move finding wgDBname from wgServer to inside the main foreach

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Reverts miraheze/mw-config#3006

Revert "add CommentStreams and VEForAll T5183/T5184 "

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Adding the Bootstrap extension per phabricator item T5437. Take note that this is my first time doing this and there could be some errors.

add BootStrap Extension per T5437

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Reverts miraheze/mw-config#3041

Revert "Adding Calendar-Wikivoyage Extension"

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Reverts miraheze/mw-config#3042

Revert "Revert "Adding Calendar-Wikivoyage Extension""

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

adding DynamicSidebar extension per Phabricator item T5483

Adding DynamicSidebar extension per item T5483

---

LocalWiki.php

differenciate closing sitenotice for private wikis + fix style issues

---

LocalSettings.php

add wgAbuseFilterNotifications

---

ManageWikiSettings.php

make links clickable in ManageWiki (HTML)

---

LocalSettings.php

No changes to wiki, sole contributor is requester

change license to GFDL for freesoftwarepediawiki T5562

---

LocalSettings.php
ManageWikiSettings.php

ManageWikiSettings, LocalSettings: Add wgDisplayTitleHideSubtitle

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Add Femiwiki to ManageWiki

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

Install a skin per phabricator item T5574

Install Citizen skin

---

ManageWikiExtensions.php

Run Wikibase Site tables on client installs
Put client first in the ext-list

Fix order of wikibase extensions & run populateSites on install

---

LocalExtensions.php
LocalSettings.php
ManageWikiExtensions.php
extension-list

fix proposed by the developer.

re-add slacknotifications

---

LocalSettings.php
ManageWikiSettings.php

Add wgCategoryTreeCategoryPageMode to ManageWiki

---

LocalSettings.php

Making changes to the wikis of the Hispano projects
