miraheze/mw-config

- LocalSettings.php
static.miraheze.org is same as $wmgUploadHostname, so unnecessary.
> Minor cleanup

- LocalSettings.php
I want to test it out to see if it works, if yes it will be good so that the Example user's password cannot be changed on testwiki.
> add 'exampleuser' permission on testwiki

- LocalSettings.php
Per #169 no longer shows segfaults, SPF said the extension can be used again.
> re-enable Geshi for wikis already there + enable for datasciencewiki

- LocalSettings.php
They're designed for a completely different project entirely. A world where links to youtube are bad or Google shortened URLs. Welcome to the real world where if people don't uses them, people complain.
Source of many complaints.
> Remove spam blacklist sources from Wikimedia

- LocalSettings.php
Requested on IRC by founder: 
9:22 AM <go1111111> the wiki 'bitcoindebates' which I maintain is being flagged for inactivity. the wiki is a roughly finished reference which continues to be useful in its current form. How can I keep it from being closed without having to make a bunch of no-op edits?
9:51 AM <•labster> go1111111: We can mark that wiki with an exception to the dormancy policy
10:03 AM <go1111111> labster: that would be awesome
> add bitcoindebateswiki to DP exception per request on IRC

- LocalSettings.php
I think there is no Asia/Beijing and that's from where the wiki is getting an internal error
> change timezone name from cauarinawiki

- LocalSettings.php
VE for NS teaching and library and blank for wisdomwiki
> enabling VE in NS for WW -wisdomwiki

- LocalSettings.php
~ enabled FLOW and FORUM (needs parsoid enabled and run update.php manually)
~ more or less cloning most of the wisdomwiki-settings
~ all wisdomsandbox stuff is underneath wisdomwiki, for its a sub-wiki, and only appears when WW entry is present (seemed sensemaking). hope thats an acceptable exception of the alphanum-sortrule.
~ doublechecked the 'NS_TEST',1632 and TALK 1633 they are leftovers from an earlier shift and not in use as of now.
> configuration of wisdomsandboxwiki

- LocalSettings.php
mixup wisdomwikiwiki & wisdomsandboxwiki,
NS_TEST is to be sandbox. now corrected.
> correction

- LocalSettings.php
Hay guys, I thought this might be a good idea.
> Add $wgNamespacesToBeSearchedDefault to search Tech on metawiki default

- LocalSettings.php
Was accidentally set as `true` instead of `false`.
> disable InstantCommons for pso2wiki T883

- LocalSettings.php
This way I don't have to grant myself tagmanager rights every time I edit a tag
> Include tagmanager permissions in the sysop group

- LocalExtensions.php
- LocalWiki.php
I think that LocalWiki.php is a better place for the permission variables than LocalExtensions.php
> move permission variables to LocalWiki.php

- LocalSettings.php
Reverts miraheze/mw-config#1176
Thought parsoid config was done. @DeltaQuad-DQ This is not your fault but please always make a PR for parsoid config too and/or link it here.
> Revert "Enable VisualEditor on tsponiewiki per T1265"

- LocalSettings.php
also set up wgAutoblockExpiry with default at 86400 (24 hours - as it should be)
> 64 hour autoblocks on brynda1231 per T1318

- LocalExtensions.php
~~In it's current configuration, the group can only be added by Stewards. It may be better to just `unset( $wgGroupPermissions['staff'] );` and assign `$wgGroupPermissions['sysop']['editothersprofiles'] = true;`, but this is the least (possibly) controversial of the two actions.~~
See T1397 for reference.
> grant editothersprofiles to sysops

- LocalSettings.php
Rather than log an issue on phabricator - I've found this is what volunteers end up doing, so have simply added code to enable VisualEditor for bchwiki directly.
> Enable VisualEditor for bchwiki

- LocalWiki.php
Since the group cannot be deleted and since checkuser rights have been assigned to the steward group, removing all permissions from the CheckUser group should invalidate it.
> Removing all permissions from CheckUser group

- LocalSettings.php
I hope that setting [default = false] is correct. I have tried to verify that it is not being set elsewhere in this file and that false should be the defualt value.
https://www.mediawiki.org/wiki/Manual:%24wgAllowImageTag
> Enable <img> tag on Westmarches

- LocalSettings.php
remove exampleuser group
Steward should not need wgAddGroups or wgRemoveGroups as they have userrights
add redundancies on consul wgRemoveGroups
> update testwiki rights per IRC

- LocalSettings.php
Pointless, as only sysops can delete pages anyway
> Disable deletion protection on WikiCanada

- LocalSettings.php
Addition of Settings for [Spanish PublicTestWiki](https://es.publictestwiki.com) (PruebaWiki). See [T1740](https://phabricator.miraheze.org/T1740) and [T1741](https://phabricator.miraheze.org/T1741).
> Addition of Settings for "PruebaWiki"

- LocalSettings.php
I accidentally deleted the "Delete" protection level when I want to add another one. I ask that you add this configuration to the wiki. Thanks.
> Fix Error on Protect Levels for "PruebaWiki"

- LocalSettings.php
So I was playing around with the theme, created the template Bootstrap:Subnav and then nothing works! It always give me a 500 error and I don't wont to crash the server. Even if I want to go back to the settings page and change my theme to the default one, I can't! :cry: 
Here is the end of the story between my wiki and the skin :stuck_out_tongue_winking_eye:
> Disable BootstrapMediaWiki

- LocalSettings.php
I tried to go without it in order to reduce collateral chances, but a few days after turning it off there was vandalism again. There was little to no vandalism with it enabled, so if I had to guess, the vandal(s) are relying on Tor.
> Revert disabling of TorBlock on WikiCanada

- Database.php
c1 is default anyway. Attempt to fix: T1762
Made as a PR as I'm not sure what the consequences are and someone with DB access should merge, in case something happens.
> remove metawiki from c1 define

- GlobalExtensions.php
- LocalExtensions.php
- LocalSettings.php
TorBlock has been in LocalSettings with default = true for a while now, I disabled it on WikiCanada and then was immediately spammed. I think that it is something Miraheze should have globally
> Move TorBlock to GlobalExtensions

- LocalSettings.php
- LocalWiki.php
Revoking read automatically revokes creating and editing, so there is no reason to revoke them as well
> Cleanup WikiCanada permission revocations

- LocalSettings.php
- LocalWiki.php
Group permissions:
- Stop editing of CSS/JS by anons
- Remove default patrolling from pages
- Replace it with FlaggedRevs-based settings for same groups
- Move restrictions for users
FlaggedRevs:
- Articles/Files/Templates/Categories/Modules for review
- Protection-like settings
- One status setting
- No autopromotion
> Enable FlaggedRevs and change group permissions in isvwiki

- LocalSettings.php
- All levels added
- Comma in confirmed
Sorry again for being an inconvenience, looked into https://noc.wikimedia.org/conf/highlight.php?file=flaggedrevs.php again - there should have been all levels all along since they just modified theirs.
This again fixes #1508 / #1509.
> Fixed another error in isvwiki config

- LocalSettings.php
- LocalWiki.php
Seeing as Amanda has had her ban reinstated, and has also repeatedly made it clear that she doesn't want anyone to adopt wikicanada, this simply removes all wikicanada configuration from our site.  If stewards decide to deleted wikicanadawiki, this PR can be merged.
> Remove configuration for wikicanadawiki

- LocalSettings.php
Don't really know why it isn't enabled by default, but.
> Enable TemplateSandbox on isvwiki

- LocalSettings.php
Enable SyntaxHighlight Extension in "sysexwiki" for Request in [T1863](https://phabricator.miraheze.org/T1863). Thanks.
> Enable SyntaxHighlight in "sysexwiki" for T1863

- LocalSettings.php
Enable YouTube Extension in "mikrodevdocswiki" for Request in Phabricator Task [T1877](https://phabricator.miraheze.org/T1877). Thanks.
> Enable YouTube Extension in "mikrodevdocswiki" for T1877

- LocalSettings.php
Enable $wgAllowExternalImages in "mikrodevdocswiki" for Phabricator Task [T1882](https://phabricator.miraheze.org/T1882). Thanks.
> Enable $wgAllowExternalImages in "mikrodevdocswiki" for T1882

- LocalSettings.php
- Minor style changes ("defualt", 828 changed to WMG_NS_MODULE)
- Added DPLForum with configuration to stop editing forum talks (namespace 111).
- Added VisualEditor with config settings (UseSingleEditTab = true, ShowBetaWelcome = false). Standard config for ShowBetaVelcome: https://www.mediawiki.org/wiki/Extension:VisualEditor#Complete_list_of_configuration_options
- Added Module namespace to be globally in wgTemplateSandboxEditNamespaces since Scribunto is used globally, see https://noc.wikimedia.org/conf/CommonSettings.php.txt for the same configuration in Wikimedia projects.
Before approving this request please go into Parsoid repository and add "isv" there (I hope it is not an inconvenience, I just don't want to make another fork).
> 2 extensions (isvwiki) & global setting for TemplateSandbox

- LocalWiki.php
Let's explain how these work a little bit more because it took me way too long to figure out.. 
Also, let's allow bureaucrats to add/remove the group in the very rare case of a bureaucrat not having the sysop group.
> + Explanation (Part Two)

- LocalSettings.php
Changed the logo for https://ashenswiki.miraheze.org per request T2015.
> Logo change for Ashens Wiki

- LocalSettings.php
Enabling Loops for sysex.miraheze.org per request T2035.
> Enabling Loops for sysexwiki

- Database.php
db3 free space is ~37GB. In order to save more space on db2, I propose moving the two wikis (top 10 list) to db3 as well.
@NDKilla
> Propose moving 3 more wikis to db3

- LocalExtensions.php
Translate has changed plenty since we installed it. Translate-proofr was removed as seen in https://github.com/wikimedia/mediawiki-extensions-Translate/commit/2b1dc092f00380bfc0c07ba3118391c86df8e6cf . With the current config, it just creates an empty translate-proofr user group.
> Remove old translate config

- LocalSettings.php
Reverts miraheze/mw-config#1761
404 Not Found so reverting for now. Will test out later and see why it isn't working.
> Revert "$wgArticlePath on oecumenewiki per T2256"

- LocalSettings.php
Enable Comments Extension in "paddelnwiki" for Phabricator Task [T2325](https://phabricator.miraheze.org/T2325). Thanks.
> Enable Comments Extension in "paddelnwiki" for T2325

- LocalSettings.php
Enable YouTube Extension in "lexiquewiki" for Phabricator Task [T2327](https://phabricator.miraheze.org/T2327). Thanks.
> Enable YouTube Extension in "lexiquewiki" for T2327

- LocalSettings.php
This PR is to implement the activation of visualeditor on the new "tema" namespace as requested in phab task T2557.
> Implement task T2557

- LocalSettings.php
but leave the rest of moderation config available for if required later.
> Turn off moderation on sdiywiki

- LocalWiki.php
> remove MediaWiki:Common.css from whitelist

- .travis.yml
No point in checking PHP 5.5 as it's not supported in MediaWiki 1.30 anyway.
> Remove php 5.5 check

- LocalSettings.php
**I noticed** that the name **Project** in English translated is **Proyecto** that is enabled, **See** [2071](https://github.com/miraheze/mw-config/pull/2071). It is to enable **namespace 4**
> enable VisualEditor on namespaces in unionwiki and wiki1776wiki

- LocalSettings.php
On request in T2710 : 
> $wgRelatedArticlesFooterWhitelistedSkins = ['vector'];
Is the format correct?
> settings relatedarticles on allthetropeswiki per req T2710

- LocalExtensions.php
- LocalSettings.php
- extension-list
This skin is ancient and also does not work with at least mediawiki 1.30
see example url https://allthetropes.org/w/index.php?title=Main_Page&action=edit&useskin=monaco
It is a white screen with no content thus meaning the skin is broken.
> Remove skin Monaco

- LocalWiki.php
I've read documentation and decided to experiment with this approach to language customization.
1. Add custom `isv` language, so I could change the language from Canadian English as it is now: https://www.mediawiki.org/wiki/Manual:$wgExtraLanguageNames
1. Add `d` to interwiki links list so we could display and set Wikidata items in "In other languages" section: https://www.mediawiki.org/wiki/Manual:$wgExtraInterlanguageLinkPrefixes
Both changes should not affect other projects.
> Extra language name/prefix for isvwiki

- LocalSettings.php
Forgot about this when adding a new namespace, sorry.
> Enable visual editor in new namespace of isvwiki

- LocalSettings.php
I’m not currently using ProtectSite nor project namespace protection, so these rights are redundant
> Remove redundant userrights

- LocalSettings.php
This allows stewards to access Special:Log/abusefilterprivatedetails, which is a new log that logs each time the abusefilter-private permission is executed. I believe (haven’t actually seen what the log looks like) that the log works similarly to the CheckUser log.
> Add abusefilter-private-log for stewards

- LocalSettings.php
No longer needed per the creation of the interwiki-admins global group
> Remove interwiki from stewards

- LocalWiki.php
Redundant since anonymous users can no longer read the wiki
> Remove “allow only logged in users” protection level

- LocalSettings.php
The descBaseUrl should be "https://commonswiki.miraheze.org/wiki/File:" not "https://commonswikiwiki.miraheze.org/wiki/File:"
> Fix $wgForeignFileRepos

- LocalSettings.php
Usually I want to block everything locally, but given the amount of vandalism/spam today, I’ll re-enable global blocks as a temporary measure
> Temporarily re-enable global blocks on weatherwiki

- LocalSettings.php
Way, way, way too many global blocks are being made, some of which even overlap each other
> Disable global blocks on Weather Wiki again

- LocalWiki.php
All edits, regardless if bot or not, or if minor or not, should always trigger the new messages prompt
> Remove nominornewtalk from bots

- LocalSettings.php
The image doesn't appear on my wiki but one line below " is used and works fine there.
> Replace ' with " in rights icon url of jadtechwiki

- LocalSettings.php
So that it does not appear in the results of external search engines
> add destinoswiki on wgDefaultRobotPolicy

- LocalSettings.php
Not all pages in project namespace are going to be official policies, and therefore this will have collateral damage in the future
> Revert #2377

- LocalSettings.php
A week is more than enough time for a user to be considered “active” IMHO
> Add $wgActiveUserDays

- LocalSettings.php
I don’t like not being able to close the global site notice, and I haven’t needed to use a local sitenotice yet
> Re-enable DSN on weatherwiki

- LocalSettings.php
No longer needed thanks to ProtectSite’s ability to lock the entire wiki indefinitely
> rem siteadmin from weatherwiki stewards

- LocalSettings.php
The checkuser and oversight rights are grandfathered into the steward group on Weather Wiki and therefore should not exist separately
> Override default, not add to default

- LocalSettings.php
To try the shortcuts as in enwikipedia and AllTheTropesWiki
> enable wgNamespaceAliases on apunteswiki, destinoswiki, centralwiki, mexicopediawiki, repositoriowiki, tallercentralwiki, ucroniawiki

- LocalSettings.php
Reverts miraheze/mw-config#2442
Somehow that removed the $wgAutopromote configuration for the extendedconfirmed group
> Revert "Restrict editing of sensitive namespaces on weatherwiki"

- LocalWiki.php
These are both extensions that I’m interested in using, and by default it seems that nobody has the necessary rights to use the extensions.
> Add ApprovedRevs and Purge to MWP on weatherwiki

- LocalSettings.php
For whatever reason DismissableSiteNotice doesn’t seem to be working with the current global sitenotice (it keeps reappearing even after I’ve dismissed it)
> Add sitenotice opt out for weatherwiki

- LocalSettings.php
Per the installation of UserMerge in #2583 however because of CentralAuth and SUL limitations I do not believe that I am allowed to have this right for myself
> Add UserMerge to local weatherwiki stewards

- LocalSettings.php
If centralauth-merge is removed from the * group it can screw up SUL stuff (when a user creates a global account by creating an account on one wiki, if they then visit another wiki where this right has been removed, their local account won’t be automatically merged in to their global account)
> Add another blacklist right

- LocalSettings.php
> Disable “page creation log” for weatherwiki

- LocalSettings.php
- ManageWikiSettings.php
extension uses eg prefix instead of wg prefix
> wgApprovedRevs -> egApprovedRevs

- LocalExtensions.php
This is uneeded as it uses the wiki dbname rather then a shared db and duplicates things.
> Unset cargo db variable

- LocalExtensions.php
This doesn't include the actual file so no copyright concerns. It only includes the log.
> Include "--logs --uploads" in the DataDump dumps

- LocalSettings.php
- LocalWiki.php
As I don't have time or the motivation to continue maintaining it, Weather Wiki is going to be deleted within the coming days. This change removes all configuration that I could find in LocalSettings.php pertaining to weather wiki - most of it is "leftover" things that couldn't go in ManageWiki. However, DO NOT MERGE this change right now as I'm still working with DataDump and figuring out how it works, and as such the wiki should NOT be deleted yet.
> remove weatherwiki config

- LocalSettings.php
MangeWiki should set it by default for new wikis and existing wikis will have it set to allow them to disable it if they want.
Bug: T4683
> Set wmgUseMobileFrontend to false

- LocalSettings.php
Because configurations of $wgRightsIcon for `incubatorwiki` and `isvwiki` are exactly same as `default`, they don't need to be defined per-wiki.
> Remove unnecessary configurations of $wgRightsIcon

- LocalSettings.php
No need to do an extra foreach when we can use $name.
Also fix an issue with custom wiki domains that use *.m.*.
> Remove duplicate foreach

- LocalSettings.php
This will ensure some functionaility like globally renaming a user should work if a wiki is deleted.
> Foreach over deleted.dblist

- LocalSettings.php
Current a wiki bureaucrat can use manage wiki to modify the local interwiki admin group because it is not blacklisted. Due the frankly ridiculous requirements currently in place for getting the interwiki permission I assume this is not desired. Now I don't see why this permission is restricted in the first place when editinterface already allows adding malicious content if desired, but here is the fix anyway because even though I don't agree with the rules I am never one to abuse exploits or break rules and I gueuely care for miraheze and want to see it continue to thrive for years to come. Note while I did add myself to the group on my wiki I only did it as a test, I did not change the interwiki table at all and I removed the group as soon as I confirmed it could be done, the logs should …
> Prevent crat from editing interwiki admin group

- LocalSettings.php
- ManageWikiExtensions.php
this right no longer provides access to private information since the introduction of editothersprofiles-private
> restore access to editothersprofiles

- LocalSettings.php
Avoid indexing pages that are not content. In addition to forcing the indexing of a namespace
> wgNamespaceRobotPolicies on hispanowiki and ucronias

- LocalSettings.php
* It makes sense to sort protection levels by hierarchy, lower to higher like `""`->`autoconfirmed`(->`extendedconfirmed`)->`sysop`, as MediaWiki core (and Wikimedia wikis in case of using `extendedconfirmed` protection level) does. As such, I adjusted [`$wgRestrictionLevels`](https://www.mediawiki.org/wiki/Manual:$wgRestrictionLevels) to display `user` protection level ("Allow only logged in users") before `autoconfirmed` and `sysop` protection levels.
* I also reordered `'create'` in [`$wgRestrictionTypes`](https://www.mediawiki.org/wiki/Manual:$wgRestrictionTypes) to be before other options since it matches better to default settings and "creating" a page is done before "editing", and enabled protecting pages from changing protection settings by default.
> Adjust protection settings

- LocalSettings.php
- LocalWiki.php
- ManageWikiSettings.php
We will no longer set mobile domains, instead it will auto detect whether to display the mobile ui and allow users to view the desktop site if they want.
> Remove wgMobileUrlTemplate in ManageWiki

- ManageWikiExtensions.php
runcargoqueries governs access to the special pages Special:Drilldown and Special:ViewData, which allow for viewing/querying of stored Cargo table data using visual forms.
By default, this permission should be enabled for all users: https://github.com/wikimedia/mediawiki-extensions-Cargo/blob/2d48935037fa8626b6365019878d044a9fa52970/extension.json#L20
> Add runcargoqueries as all user perm on Cargo install

- LocalSettings.php
Going to see how things are handled by letting the default be used.
> Remove wgJobRunRate - leaving to the default as 1

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
Adding Calendar-Wikivoyage extension per phab item T5137. Submodule has not yet been added. I will add comment when it is.
> Adding Calendar-Wikivoyage Extension

- ManageWikiExtensions.php
The extension is tested and stable and therefore should not be restricted.
> Remove restriction on DynamicSidebar extension

- LocalSettings.php
Can be merged any time (preferably ASAP).
1.35 allows for checking 2FA status via the oathauth-verify-user right. This must be blacklisted to avoid a privacy leak.
Bug: T5498 (Part 1/2)
> Blacklist oathauth-verify-user

- Database.php
Since day 1 Miraheze has been relying on passwords (PSKs) to authenticate the mediawiki and wikiadmin users for database connections. As such, there is no point in setting the certificate and key paths here, since we don't use two-way authentication. Avoids log spam, extra traffic, more usage of the wildcard certificate (ideally only used on the cache proxies!) and avoids the impression of using one-way authentication where we don't.
Two-way authentication has its benefits and may be considered in the future, but is not relevant right now.
> Remove TLS cert and key from Database.php

- LocalSettings.php
CreateWiki/RequestWiki will now throw an error when a wiki with the exact name of "wikiwiki", "wwwwiki", or "wikiswiki" is requested.
> blacklist subdomains

- LocalSettings.php
Not currently used but is added in a newer CU update and also is behind a flag.
> Blacklist "investigate" perm

- LocalSettings.php
Prevent users from using 'subdomain' as their dbname in wiki requests per a suggestion from @Amanda-Catherine.
> Blacklist subdomain.miraheze

- ManageWikiExtensions.php
TODO: Revert this when https://gerrit.wikimedia.org/r/#/c/mediawiki/extensions/CommentStreams/+/606820/ is merged
> Comments conflicts with CommentStream and vice versa

- LocalSettings.php
The local page is pulled by default, and there is nothing on meta's MediaWiki:Titleblacklist that isn't already on the global page.
Use all sources as potential username blacklists.
Log TitleBlacklist hits
Do not block automatic account creation
> reconfigure TitleBlacklist

- LocalSettings.php
Re-adding a few steward rights that were lost while overriding CU and OS groups
Grant all 2FA-related rights to stewards, just in case
Create banned group to remove read access from registered users (only to be used in extreme cases)
> Userrights config for simcitywiki

- LocalSettings.php
We're draining db9, so we do not want any new wikis on it.
> Switch wgCreateWikiDatabaseClusters to db12 (c3)

- LocalSettings.php
Adding "sandbox" to restricted subdomains list because we've had a couple wiki request declines in the past month ([Wiki Request 12598](https://meta.miraheze.org/wiki/Special:RequestWikiQueue/12598) and [Wiki Request 13380](https://meta.miraheze.org/wiki/Special:RequestWikiQueue/13380)), and I don't want to see it inadvertently get created. Also, adding "noc" as a restricted subdomain as I didn't see it in this list, and it's highly conceivable Miraheze may want to use it for technical coordination purposes, either as a wiki or some other website. Finally, though I don't want to create it now, I was talking with @Reception123 on Discord about ways we can (a) increase Meta participation and (b) community volunteerism, and one of the ways in which I think this would be helpful would be …
> Fix regex for wgCreateWikiBlacklistedSubdomains

- LocalSettings.php
Otherwise bots can't edit pages protected to allow only logged in users if they use BotPasswords or OAuth
> add user right to basic grant permissions

- LocalSettings.php
One of the wiki requests in the queue is categorized as 'electronics'. We don't have any sufficient categories for this type of wiki. Additionally, we have a number of automotive- and automobile-related wikis that could possibly be categorized, if so desired by the local bureaucrats on those wikis, with this added category. Also, fixing a modest typo in 'eletronics' to 'electronics', which likely doesn't require further updates. Pinging @paladox or @NDKilla to see if they can approve and merge. If not, @Reception123 can likely do in the morning when he's awake and caffeinated.
> Update LocalSettings.php to add 'automotive' category to CreateWiki and fix typo in 'eletronics' category

- ManageWikiSettings.php
Moved wgHAWelcomeWelcomeUsername to restricted due to if you use your own account, it'll turn it into a system account and lock you out of it
> move wgHAWelcomeWelcomeUsername to restricted

- LocalSettings.php
We have a lot of potential, and existing, uses for such a category, such as wikis that propose to teach a language (or language(s)), translation wikis, MediaWiki support wikis in languages in other than English, and dictionary wikis
> Adding a Language and Linguistics category

- LocalSettings.php
Adding much needed humour/satire category to CreateWiki/RequestWiki. Based on the number of approved wikis, and recent requests, I conservatively estimate 100+ existing Miraheze wikis could be recategorised in this way, and expect a minimum of 1 humour/satire wiki request per week will be approved, on average, for the foreseeable future. In short, lots of potential use cases
> Add Humour/Satire category to CreateWiki/RequestWiki categories

- LocalSettings.php
This adds the `$wgTimelessWordmark` configuration variable for closinglogosgroupwiki per T6352.
In addition, I removed the quote encapsulation from `$wgMedikLogoWidth` default value as the `null` should not be a string literal.
> Add $wgTimelessWordmark config

- LocalExtensions.php
- ManageWikiExtensions.php
- extension-list
Extension not supported by 1.35 and also extension is severally unmaintained.
> Remove CrossReference

- LocalSettings.php
- ManageWikiSettings.php
`$wmgFederatedPropertiesEnabled` should default to false, as that is the default Wikibase configuration value.
> $wmgFederatedPropertiesEnabled default to false

- LocalSettings.php
Actor and a few other tables were put into tables-generated.sql, it seems to be because of the new abstract schema system.
> Also install tables-generated.sql for new wikis

- LocalExtensions.php
- ManageWikiExtensions.php
For consistency with other extension requirements.
> kartographer require jsonconfig instead of enable it with it

- ContactPage.php
- LocalSettings.php
- LocalWiki.php
Removes configurstion for deleted wikis, from the files, ContactPage.php, LocalSettings.php, and LocalWiki.php
Also:
* Fixes database name for `hrfwiki2wiki`, which was previously set as `hrfwiki2`
* Cleans up formatting
* Sets default for `$egApprovedRevsEnabledNamespaces` and `$wgPivotFeatures`
* Changes default for `$wgVisualEditorEnableVisualSectionEditing` to `mobile` (https://github.com/wikimedia/mediawiki-extensions-VisualEditor/blob/9f9966d1cda186086f74c8d810b081b4d189fe8c/extension.json#L93)
> Remove deleted wikis

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
Extension:Bootstrap is only useful for Skin:Chameleon. If we ever end up installing that, then this extension can just be enabled with it, not through MWE as that gets confusing. https://phabricator.miraheze.org/T2841#65856
> Remove Extension:Bootstrap from ManageWikiExtensions

- LocalSettings.php
This:
* Adds static.miraheze.org as a default allowed value of `$wgTemplateStylesAllowedUrls`.
* Fixes the previous default config for wikimedia, to be back in sync with their configuration, and the default configuration of TemplateStyles.
* Removes the comment, which says to remove that when a patch on Gerrit is merged, this is removed, because that mentioned patch has been abandoned.
> Add static.miraheze.org as a default allowed value of $wgTemplateStylesAllowedUrls

- LocalSettings.php
If the test is successful, I will propose a second PR for @Reception123 to review that will add `simple` to the default setting
> Adding `simple` interlanguage prefix to TestWiki

- LocalSettings.php
Following this successful test PR (https://github.com/miraheze/mw-config/pull/3383) and test (https://publictestwiki.com/wiki/Special:Log/interwiki), we are now good to add `simple` as an interlanguage prefix across all interwiki tables
> Add simple interlanguage prefix to default

- LocalSettings.php
Unused as the regex was broken anyways and test* has access to the cdn including jobrunners.
> Remove setting wgUseCdn to false on some servers

- LocalSettings.php
Done because this is set in MWS through `$wmgVisualEditorEnableDefault`.
> Remove visualeditor-enable from defaultuseroptions

- LocalSettings.php
Both configs removed in previous MW versions.
> Remove wgActorTableSchemaMigrationStage and wgCommentTableSchemaMigrationStage

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
Done because it has other uses besides just the popups extension, such as external api's that use it, like Discord Wiki-Bot. (https://phabricator.miraheze.org/T6480)
> Migrate PageImages to ManageWikiExtensions

- LocalSettings.php
With `wikitestwiki` now added to the list of deleted wikis, it seems prudent to add `wikitest` (and `testwiki`) to the list of CreateWiki blacklisted subdomains, since any TestWiki forks will require local community consensus first. This will prevent accidental creation, and I have I followed Void's regex. As well, I have also added the `community` subdomain, which never should've been created in the first place, at least not without a successful community noticeboard discussion, and a typographical error for `gazeteer` (`gazetteer` is already blacklisted). Thanks.
> Adding "community," "testwiki," "wikitest," and "gazeteer" to the CreateWiki blacklist

- LocalSettings.php
- ManageWikiSettings.php
Seems since MediaWiki 1.35 that `$wgMFDefaultSkinClass` was renamed to `$wgDefaultMobileSkin`
https://github.com/wikimedia/mediawiki-extensions-MobileFrontend/blob/1421405c1fe4f3dbafe0cd18f43aa9054b974c4e/extension.json#L937
> add $wgDefaultMobileSkin to ManageWikiSettings (T6488)

- ManageWikiExtensions.php
No change to name in database table, so no DB update should be needed. Thanks
> Fix typo for Extension:UrlGetParameters in ManageWiki/extensions link

- LocalSettings.php
c1 is the same as c2. But lets add c1 to wgCreateWikiDatabaseClustersInactive to prevent wikis changing db clusters.
> Add c1 to wgCreateWikiDatabaseClustersInactive

- LocalSettings.php
We create a new wmgDefaultUserOptions config which is local and then we add wmgDefaultUserOptions onto wgDefaultUserOptions by doing:
wgDefaultUserOptions = array_merge( $wgDefaultUserOptions, $wmgDefaultUserOptions );
Using + with wgDefaultUserOptions didn't appear to apply the overrides we had set in wgConf thus this change is necessary for this to work again.
> Fix setting overrides for wgDefaultUserOptions

- LocalSettings.php
With Spanish Public Test Wiki finally hitting Special:DeletedWikis this morning, `prueba` should be added to the CreateWiki subdomain blacklist similar to `wikitest`, to prevent accidental creation of an unauthorized Public Test Wiki fork that did not have either (a) the local consensus of the TestWiki community or (b) consensus of the global Miraheze community on community noticeboard. Incorporates standard regex for other subdomains to prevent numerical digits being included in the subdomain.
> Add prueba to the CreateWiki subdomain blacklist

- Redis.php
Not really needed as we use nutcracker thus doesn't make a connection to redis on each request.
> Redis: Remove persistent

- LocalWiki.php
Please see T6604 for more information. I also changed the message to say that you must be a bureaucrat to uncheck "inactive" to be consistent with the closed wiki sitenotice.
> Show Different Sitenotice for Inactive Private Wikis (Fixes T6604)

- ManageWikiSettings.php
should be moved outside of MWS since there's no reason to change that link, temporarily restricting until that's done
> restrict wgCookieWarningMoreUrl

- LocalSettings.php
We use a global table, do not need it to be installed on each wiki.
> Stop installing globalblocking sql for each wiki

- LocalSettings.php
@Universal-Omega, would you mind merging this for me? I'd like to potentially reserve the `beta` and `betameta` subdomains for separate wiki usages in 2021, mainly relating to Miraheze. Thanks!
> Adding betameta and beta to CreateWiki blacklist

- ManageWikiSettings.php
It was pointed out by @The-Voidwalker that the value of restricted for ``wmgUseYandexTranslate`` was set to a string instead of a boolean. This caused the setting's textbox to appear restricted. I also fixed a minor punctuation mistake.
> Fix value of restricted being a string and a minor punctuation mistake

- ManageWikiExtensions.php
Both of their names got changed and it is probably a good idea to update them in ManageWiki, too.
> Change HTML Meta and Title and SnapProjectEmbed's display name

- LocalSettings.php
This PR does a couple things. Firstly, it adds `loginwiki` to the `default` import sources, essential for transwiki importation from Loginwiki. Contemplated adding only to Meta Wiki's import sources, but given the global nature of Loginwiki and the high likelihood imports will want to be done across multiple wikis, it makes sense to add it globally. Secondly, this PR also migrates `wikipedia` from local sources to `default` given nearly every wiki commonly imports pages and templates from Wikipedia.
> Add `loginwiki` & migrate `wikipedia` to default import source

- LocalSettings.php
https://doc.wikimedia.org/mediawiki-core/REL1_35/php/LocalisationCache_8php_source.html uses this anyway so why not just set to this instead?
> Change wgLocalisationCacheConf to use storeClass

- LocalSettings.php
Similar to the examples of `subdomain`, `sandbox`, `test`, and `prueba` (Spanish for "test"), `example` is another subdomain that turns up time and again wiki requests, and should be disallowed.
> Add `example` to CreateWiki blacklisted subdomains

- LocalSettings.php
We have a quite a number of wikis related to science-related topics, including astronomy, physics, physical and environmental sciences. We have _Education_, yes, but we also have _Medical/Medicine_, which describes topically the wiki. Education tells only _who_ uses it, not what the wiki is about.
> Add Science category to CreateWiki

- ManageWikiExtensions.php
Based on https://github.com/wikimedia/Wikibase/blob/REL1_35/extension-repo.json#L104, these user rights should be installed for Wikibase Repository.
> Install user rights for Wikibase Repository

- Sitenotice.php
Several announcements on Discord together with this short sitenotice and the fact that actually uploading files will make it clear that uploads are again available. No need for more than a few hour sitenotice.
> Remove short term sitenotice that uploading is available

- LocalSettings.php
- ManageWikiSettings.php
Adds ``wgWatchlistExpiry`` to ManageWiki which is no longer marked as experimental since 1.35.1.
> Add wgWatchlistExpiry to ManageWiki

- MissingWiki.php
Adds a missing full stop to ``MissingWiki.php`` even though it is a really minor issue.
> Add missing full stop

- LocalSettings.php
@paladox I have confirmed that `mem` and `mem1` through `mem10` are not in active use by any existing Miraheze wikis, so we should be safe to blacklist this subdomain from CreateWiki
> Add `mem` to CreateWiki blacklist

- LocalSettings.php
People just keep making requests with ``miraheze.miraheze.org`` as the domain.
> Add "miraheze" to CW blacklist

- LocalSettings.php
Due to a bug in the Matomo extension, we've accidentally deleted the default id.
So we change it to the new one so we have a centralised analytics.
> Change default matomo id

- LocalSettings.php
We do get quite a few wikis that propose to create either a wiki about buildings and other real world infrastructure. Combining with "Art", as is common, also means this could potentially be used for the many artist repository wikis or even fan-made original character repositories/catalogues, too. It's also a common categorization
> Add Art & Architecture category to CreateWiki

- LocalSettings.php
It is a very bad idea to assume we have all possible purposes for wikis.
> Add "None of the above" to CreateWiki Purposes

- LocalSettings.php
The current configuration introduced in https://github.com/miraheze/mw-config/commit/1a899d9d5ee879b06cf8d622b3fa4dcf9fc6754c makes the language display as `isv - Array` or `isv - isv`. [mediawiki.org says](https://www.mediawiki.org/wiki/Manual:$wgExtraLanguageNames) that a string is needed.
> Change wgExtraLanguageNames for isvwiki

- LocalSettings.php
Missed a variable in #3814, oops (per [T7094](https://phabricator.miraheze.org/T7094))
> Configure LinkTitles for simulatorwiki per T7094

- LocalSettings.php
Requested by WikiJS (Justin) on IRC, #miraheze channel
I can actually see this added as a `default` source, but for now, will add it here. Let me know if you'd prefer I change it to `default`.
> Add MediaWiki as transwiki import source to memeswiki

- LocalSettings.php
Requested by R4356th on the Cosmos Discord server.
> Disable wgCosmosEnabledRailModules['recentchanges'] on some wikis

- ManageWikiExtensions.php
The permissions were never configured for the DataTransfer extension which caused the issue mentioned in T7149.
> Configure permissions for DataTransfer (T7149)

- LocalSettings.php
Per request (https://meta.miraheze.org/w/index.php?diff=171784&oldid=171783&rcid=614715)
> Add extendedconfirmedprotected restriction level to famepediawiki

- LocalExtensions.php
- extension-list
Per my own now-merged upstream patches and backports to REL1_36 branches.
> Convert more extensions to ExtensionRegistry

- LocalSettings.php
Per request (https://meta.miraheze.org/w/index.php?diff=171790&oldid=171789&rcid=614721)
> Add editextendedconfirmedprotected restrict. level to documentcontrolwiki

- Sitenotice.php
This ensures Google does not use the sitenotice as a snippet for their search result for Miraheze wikis who has not set one via extensions like WikiSEO. [Plaintexts here will be impacted](https://phabricator.miraheze.org/F1430638). Please ensure all future sitenotices and centralnotices has this value.
Cf. https://revi.kr/6bFF ( https://developers.google.com/search/docs/advanced/robots/robots_meta_tag?hl=en#data-nosnippet-attr )
> Change html attributes to prevent Google crawling sitenotice

- LocalSettings.php
- LocalWiki.php
- ManageWikiSettings.php
The feature has been broken for a long time because Miraheze's verification key got expired. I have made miraheze/puppet#1746 to remove the key from Puppet.
> Remove wmgUseYandexTranslate 

- LocalSettings.php
Per [#T7368](https://phabricator.miraheze.org/T7368), adding `editextendedconfirmedprotected` restriction/protection level to `extendedconfirmed` user group on `hypopediawiki`
> Add protection/restriction level to hypopediawiki

- LocalSettings.php
I am a bureaucrat on that wiki and can confirm that we want to import pages from ``snapwikiwiki`` there.
> Add ``snapwikiwiki`` as an Import Source For ``snapdatawiki``

- LocalSettings.php
`smerge.imp.fu-berlin.de` and `www.hinkler.com.au` are way too slow in responding to requests.
> Configure wgRottenLinksExcludeWebsites for snapwikiwiki

- LocalSettings.php
Deprecation warnings are sent to the mediawiki error channel in logging, and given the prevalence of some extensions using deprecated hooks (HideSection, Variables, DiscordNotifications), these warnings flood our logging infrastructure beyond what is reasonable.
> silence mediawiki deprecation warnings post 1.35

- LocalSettings.php
This pull request should enable Advanced Mobile Contributions by default for registered users in isvwiki. It would not affect anonymous users since they cannot use.
Code link:
https://github.com/wikimedia/mediawiki-extensions-MobileFrontend/blob/master/includes/Amc/UserMode.php
I also wonder whether it is possible to set `wgMinervaTalkAtTop` in isvwiki for mobile readers here, but since that variable it does not exist in the file at the moment, I did not do it in this request. Link for this (look for wgMinervaTalkAtTop, like in svwiki): https://noc.wikimedia.org/conf/InitialiseSettings.php.txt.
> Make AMC mode default for registered users on isvwiki

- LocalSettings.php
Previous method did not work (apparently `mf_amc_optin` option does not do what it is supposed to do for logged-in users), so we decided to enable Advanced Mobile Contributions features for everyone. This has to be done through a lot of configuration changes for Minerva and MobileFrontend.
Documentation:
- https://github.com/wikimedia/mediawiki-extensions-MobileFrontend#mobilefrontend
- https://github.com/wikimedia/mediawiki-skins-minervaNeue#config
Maybe these should be available in ManageWiki.
> Enable advanced options of Minerva/mobile interface in isvwiki

- LocalSettings.php
Since 1.36, this no longer works, extension previously using this, like Timeline now have to specify the path within the extension themselves in order to access this. This is due to changes with shell restrictions in 1.36.
> Remove ENV for GDFONTPATH

- LocalSettings.php
Filters are still way above so let's hope no one edits them. Warnings have been given.
https://meta.miraheze.org/wiki/Spam_blacklist exists for a reason as a replacement for most of 18 but is rarely edited anyway and 19 doesn't need editing outside of a mediawiki upgrade so shouldn't be an issue.
> [REVERT: EMERGENCY] remove emergency measure

- LocalWiki.php
I was unable to enable shared image repository via ManageWiki for `polandballwikisongcontestwiki` to use `polcomwiki` as an image repo as `$wmgSharedUploadClientDBname` was already filled on `polcomwiki` by another wiki thus making it impossible to allow multiple wikis to use a single shared repository. I am proposing this manual change to allow the wiki in question to use the `polcomwiki` as an image repository.
> Setting image repository for polandballwikisongcontestwiki

- LocalSettings.php
I added some import sources (`$wgImportSources`) to `polcomwiki` and `polandballstaffwiki`, as requested by the admins of these wikis on Discord.
> Adding Import Sources for wikis

- GlobalCache.php
We have limited amount of memory so lets use the db where we have more space to store the cache longer.
> Set $wgParserCacheType to cache in the DB

- GlobalCache.php
Reverts miraheze/mw-config#4082
Caused high load on the db servers consequently causing it to also become high on the MW servers.
> Revert "Experiment switching main cache to the DB"

- Defines.php
For some reason it seems that it's faster without this.
> Stop setting apiThumbCacheExpiry for commons

- ManageWikiSettings.php
Requested on Discord; adding $wgDiscordNotificationAfterImportPage to ManageWiki Settings which controls whether a notification is generated when a page is imported or not
> Adding wgDiscordNotificationAfterImportPage to settings

- LocalSettings.php
For the former, per the wiki's requested deletion (https://meta.miraheze.org/w/index.php?title=Stewards%27_noticeboard&oldid=210656#Request_for_wiki_deletion). For the latter, this is clean up following the wiki's deletion last winter per Dormancy Policy
> Remove references to quircwiki and rf1botwiki

- ManageWikiExtensions.php
If I'm not mistaken, it seems that commenting needs cs-comment to work. The other additions are what the defaults are.
> Set default rights for CommentStreams and SpriteSheet

- Defines.php
- LocalSettings.php
Also adds `X-Miraheze-Debug` to `$wgAllowedCorsHeaders`.
> Set `$wgCrossSiteAJAXdomains` to loginwiki and metawiki

- LocalSettings.php
Per [this](https://meta.miraheze.org/wiki/Requests_for_Comment/Changing_the_Powered_by_Miraheze_footer_button) recently closed RfC, the community has chosen this image to replace the current web badge.
> Update "Hosted by Miraheze" web badge

- LocalSettings.php
`$wgImportSources` doesn't seem to be in any of the ManageWiki pages
> Allow zealandiawiki to import templates from wikia:adoriasim

- LocalSettings.php
Doesn't seem needed, spotted while auditing config in prep for future projects.
Anyone know why not? It has no effect.
This follows up 920d4b31844416a872c605979fabc8a0cc5e0385 and effectively reverts a01c7af
> LS: remove wgSharedDB

- LocalSettings.php
Only allows Special:RemovePII to be used from `metawiki` and `test3wiki`, but it still runs jobs on all wikis.
> Configure `$wgRemovePIIAllowedWikis`

- Database.php
On test3:
* `$wgEchoSharedTrackingDB` is set to `test3wiki`.
* `$wgEchoSharedTrackingCluster` is set to the `beta` cluster. This tells what cluster for `$wgEchoSharedTrackingDB` to look for the database on.
* the `beta` cluster is set to c1, which is db11, while the `test3wiki` database is located on db12/c3, so it can't find it on db11.
This is resulting in continuous database errors on test3.
> Set `beta` cluster to c3 / db12, where `test3wiki` is located

- LocalSettings.php
Per request (https://meta.miraheze.org/w/index.php?title=Stewards%27_noticeboard&diff=214165&oldid=214148&diffmode=source) at stewards' noticeboard, mainly to allow the user to edit previously protected pages as `editextendedconfirmedprotected`. The user //may// subsequently request to re-remove this protection level, or they may just keep it as an unused protection level
> Re-add extendedconfirmed protection level to lhmnwiki

- LocalSettings.php
- ManageWikiSettings.php
1) This is wrongly named
2) This is set as the default for `$AbuseFilterActionRestrictions`, the new configuration name. No need to explicitly set.
> LS: remove `$wgAbuseFilterRestrictions`

- LocalSettings.php
Raises global groups password requirements from 10 to 12.
Also adds `globalsysop` to be the same as other global groups, and `interwiki-admin` to be the same as the requirement for local bureaucrats and administrators.
> T7713: raise password requirements for global groups

- Defines.php
To fix issues like [T8504](https://phabricator.miraheze.org/T8504).
If these defaults were set like normal via LS then until changes they would not be on any namespaces. This sets defaults to disable on all namespaces, if they are disabled on every namespace via ManageWikiNamespaces, to prevent that from reverting them to the extension-set defaults.
> set ManageWikiNamespaces' variable defaults

- LocalSettings.php
- ManageWikiSettings.php
- **Motivation**: It makes the admin be able to avoid https://phabricator.wikimedia.org/T297353 (DarkMode toggle as a personal tool on new Vector is misaligned) by setting the value to `'footer'`.
- **Attachment**:
> Add `$wgDarkModeTogglePosition` to ManageWikiSettings

- Sitenotice.php
Just had a few wiki users on Discord think that their individual wiki admins were migrating their wiki to a new server, not that Miraheze as a whole would be migrating servers so this'll change the initial We to Miraheze so users know who's behind this.
> We -> Miraheze

- GlobalCache.php
To use nutcracker it only supports MemcachedPeclBagOStuff class. Doesn't work with MemcachedPhpBagOStuff.
> Use nutcracker on new mediawiki servers

- Sitenotice.php
This adds a sitenotice for all wikis that have $wgUseCategoryBrowser telling them to let us know what they think and to comment on the CN thread.
> Sitenotice for feedback on Category Browser removal

- Sitenotice.php
Changes $ to &#36; to properly escape the character and fix the sitenotice not displaying the link properly
> Fix sitenotice; escape $

- GlobalCache.php
DO NOT MERGE!
* use `$wgMemCachedServers`, and `memcached-pecl` for main cache
* use `db-replicated` for parser cache, and raise expiry to 10 days
* use `CACHE_ACCEL` for language converter cache
> Redo caching configuration

- GlobalCache.php
- LocalSettings.php
* set `$wgResourceLoaderMaxage` to default (by removing it being declared here)
* set `$wgRevisionCacheExpiry` to 2 days
* set `$wgPreprocessorCacheThreshold` to 2000
> Enable more caching

- LocalSettings.php
- ManageWikiSettings.php
This is for Wordle Hub's related articles (https://wordles.miraheze.org/wiki/Wordle#mw-data-after-content)
Thank you!
> Add RelatedActicles configurations to ManageWikiSettings.php

- LocalSettings.php
Should I set the defaults? (I didn't because it's not available from managewiki) or It is better this way (setting it per wiki)?
> T8932: ApprovedRevs configs

- LocalSettings.php
This reverts commit 08f0e1d.
* Likely causes https://phabricator.miraheze.org/T8962.
* `$wgMFDisplayWikibaseDescriptions`, `$wgMFMobileFormatterOptions`, and `$wgMFNamespacesWithLeadParagraphs` defaults are wrong.
* Support for geodata is likely not even possible with Miraheze, and if it does actually work I still have concerns about it.
* `pageprops` still needs to be present for `$wgMFQueryPropModules` for `gratisdatawiki` likely.
* `'ppprop' => 'displaytitle',` still needs to be present for `$wgMFSearchAPIParams` for `gratisdatawiki` likely.
* The defaults for `$wgMFSearchGenerator` still need to be present for `gratisdatawiki` likely.
* `$wmgUseMobileApp` doesn't even exist.
> Revert "Adding missing Mobilefrontend configs (#4499)"

- LocalSettings.php
Renamed from centralauth-oversight in 1.38, this can be done whenever, even before 1.38.
> Disallow `centralauth-suppress` right in ManageWiki

- Wikibase.php
Per my comment [here](https://phabricator.miraheze.org/T8874#182273), an empty or non-existent otherProjectsLinks variable suppresses the Other projects section on the sidebar.
If this works as intended then we have to tweak it in a way that it will be able to show all site IDs in the `miraheze` `siteLinkGroups ` without needing to list a thousand wikis.
> T8874: Add the otherProjectsLink on gratispaideiawiki

- Defines.php
* miraheze/ManageWiki#348 should move this to ManageWiki; this prepares for supporting both ways, until after that is deployed.
> Only explode if string

- Wikibase.php
There is a lot of explanation for this, actually. So, I'm going to try and see if I can explain them concisely.
After this is merged there are two more variables that needs to be set; `languageLinkSiteGroup` and  `languageLinkAllowedSiteGroups`, but before then:
This gratispaidea siteLinkGroup would be the site group for the various language wikis, currently two (gratispaideiawiki (English) and benpediawiki (Spanish)).
So, when we now have the gratispaideia site group, we will be able to set `languageLinkSiteGroup` with a `gratispaideia` value. 
Currently you'd observe that, in the `Languages` sidebar section, we have all the site listed in the `miraheze` site group. Let me explain that behaviour, The reason that happens is that the default value for `languageLinkSiteGroup` is `null`, …
> Update Wikibase.php with siteLinkGroups for gratisdatawiki

- Wikibase.php
I'm setting this to `gratisdatawiki` value, because I just realised that the default value for this is to assume both client and repo are the same, or if for example we set `siteGlobalID`, either ways, it returns `gratispaideiawiki` (self) instead of the original repo global ID.
> Update Wikibase.php with repoSiteName for gratispaideiawiki

- ManageWikiSettings.php
- composer.json
- tests/ManageWiki/ManageWikiTestCase.php
- tests/ManageWiki/SettingsTest.php
This adds two classes:
- **SettingsTest**
- is a subclass of TestCase,
- contains a schema for `$wgManageWikiSettings`,
- and tests:
- Whether ManageWikiSettings.php file is valid.
- Whether the given schema works against short configuration examples.
- **ManageWikiTestCase** is an abstract class and is split from SettingsTest for the future implementation of the validation of ManageWikiExtensions.php, etc.
This includes two new dependencies:
- `phpunit/phpunit`
- `justinrainbow/json-schema` which is the package used by WMF for the [maintenance/validateRegistrationFile.php script](https://mediawiki.org/wiki/Special:MyLanguage/Manual:ValidateRegistrationFile.php).
Thank you!
> test: Validate ManageWikiSettings.php file

- LocalSettings.php
These variables aren't available from ManageWiki, and If it should be added to managewiki, it is going to be possible to add more than one value?
So, please review and merge appropriately.
> WBQuality constraint configs for gratisdatawiki

- ManageWikiNamespaces.php
- ManageWikiSettings.php
- tests/ManageWiki/SettingsTest.php
Namespace configs are set via ManageWikiNamespaces, these types are unused, and will soon be removed from ManageWiki itself.
> Remove unused namespace(s) types

- LocalSettings.php
Since there is clearly no progress on ReCaptcha enterprise or investigating into detail, I propose we set the score to 0.3 for 12 hours and observe what the effects are - are spambots getting in? are there no more form entries? etc. I feel that most users getting turned away get 0.3 while spambots get 0.1
@RhinosF1 @MacFan4000 @Universal-Omega thoughts?
> set recaptcha v3 minimum score to 0.3 from 0.5 [TRIAL]

- LocalSettings.php
The addition of `userrights` and `userrights-interwiki` was an unauthorized additional access/access elevation request that required the public approval of either one of or both of the Engineering Managers. Reverting per discussion with @Universal-Omega on IRC
> Remove user rights sysadmin did not have

- LocalSettings.php
This so-called "security change" has very little change to security and only sees to make some interface admins unable to do their job. In addition, there was not consensus for this change which absolutely must have been obtained first
> revert unauthorized changes made without consensus

- LocalSettings.php
Set `default` to `true`, as this would be useless to us otherwise. Individual wikis would still be able to control who has access to the spam blacklist log by setting `spamblacklist` to a group other than `user`
> Set spamblacklist to true on all wikis

- LocalSettings.php
Per [SN request](https://meta.miraheze.org/w/index.php?title=Stewards%27_noticeboard&diff=next&oldid=246492&diffmode=source#I_have_a_question). This has created the scenario where these rights where these rights were blacklisted from being removed from `*`, but on wikis that already removed them, they cannot be re-added, by local bureaucrats or Stewards. This was an unfortunate oversight as these _should've_ been made default `*` rights, locked down from being removed in ManageWiki
> Add essential special pages to `*`

- Wikibase.php
This is practically not needed, the default for this config is siteGlobalID, although siteGlobalID isn't set but the default for siteGlobalID is $wgDBname, which makes repoSiteId ends up at $wgDBname.
> removing repoSiteId from gratispaideiawiki and benpediawiki

- LocalSettings.php
Quoting the doc on the extension page "If true, this configuration will not be shared across the cluster, but rather each wiki would have a local config"
and I presume that is why we still don't have the data namespace on gpcommonswiki.
> setting JsonConfig "isLocal" to true for gpcommonswiki

- LocalSettings.php
Added `editextendedsemiprotected` protection level for `collegecitoyenwiki` and `knightnwiki`. Requested on T9145.
> T9145: Add protection level for collegecitoyenwiki and knightnwiki

- GlobalCache.php
This is only used to vary config between beta/prod. It shouldn't be used outside of this file.
> GlobalCache: don't use wg for redis ip

- LocalSettings.php
and set wgULSWebfontsEnabled to true for gratispaideiawiki
> set wgExtraLanguageNames to "qqq" for gpcommonswiki and gratisdatawiki

- initialise/MirahezeFunctions.php
Additional forcing of other types where necessary.
I noticed this in Nginx error logs:
```st
[error] 579906#579906: *3888176 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_match() expects parameter 2 to be string, array given in /srv/mediawiki/config/GlobalCache.php on line 32"
```
this means that if a user were to visit a second-level non-existent subdomain like www.example.example.miraheze.org, since it is still miraheze.org it tries to find a server there, when it can't, it returns all of them for the server, since the current database returns `null`.
> Guarantee that server is always a string

- Wikibase.php
this is how it should look.
gratispaideia (standing as the client's interwiki prefix on gratisdata's interwiki table); and
gratispaideiawiki (standing as the client dbname).
> fixing localClientDatabases config for gratisdatawiki

- LocalSettings.php
Requested on TestWiki, don't see why this can't be available for everyone.
> PageImages: make MediaWiki:Pageimages-denylist work everywhere

- LocalWiki.php
Reverts miraheze/mw-config#4692
Please merge this back, I think there's a conflict with the way WikiSEO works with wikibase, I had to disable it, as we actually don't need it at all for gratisdata.
So this should be set back.
> Revert "Revert "Set meta tags on entity pages gratisdatawiki""

- initialise/MirahezeFunctions.php
These are no longer accessible in MediaWiki 1.38 from LocalSettings.php, and therefore here, as they have been moved to be set later.
> Remove usage of `$wgExtensionDirectory` and `$wgStyleDirectory`

- LocalSettings.php
This means it'll use SHA rather then ssha for the password
> Set wgPasswordHash to []

- initialise/MirahezeFunctions.php
Prevents ever loading/reading ManageWiki cache file if config cache is already generated.
> Only check if cache file exists in loadExtensions

- Sitenotice.php
This sitenotice is to be displayed during the upgrade and should be merged as soon as wikis are put into read-only mode.
> Sitenotice for upgrade

- initialise/MirahezeFunctions.php
Prevents calling the functions more times, providing minor performance improvement.
> use properties for setting globals

- LocalSettings.php
- ManageWikiSettings.php
It is deprecated in the Citizen skin in `5ccfbcfdeb39b8b3543457fda5d913c02276ddab`
Currently Miraheze is on an older version, please merge when the skin is updated next time.
> Remove `$wgCitizenEnableDrawerSubSearch` from ManageWikiSettings

- LocalSettings.php
- ManageWikiSettings.php
* `$wgCitizenEnableSearch` - Enable or disable Citizen search module. Useful for unbreaking and also wikis with custom search suggestions (e.g. Wikidata)
* `$wgCitizenSearchGateway` - Default API to use for search, some wikis might prefer REST API
* `$wgCitizenSearchDescriptionSource` - MH supports ShortDescription, Wikidata, Description2, and WikiSEO, so it is better to let the user pick where they get the search suggestion description from.
* `$wgCitizenMaxSearchResults` - Max search result in suggestions
Note that `$wgCitizenSearchDescriptionSource` has both prerequisites:
* `$wgCitizenEnableSearch` has to be `true`
* `$wgCitizenSearchGateway` has to be `mwActionApi`
But I am not sure whether `requires` support multiple items so I have only put `$wgCitizenSearchDescriptionSource`.
> Add search-related Citizen config to ManageWikiSettings

- LocalSettings.php
Not necessary, there is no overlap between ManageWiki and `+wg` globals.
Avoids unnecessary reading additional ManageWiki cache file.
> Remove extra check for getManageWikiConfigCache

- LocalSettings.php
- ManageWikiSettings.php
Removed from Cosmos in https://gerrit.wikimedia.org/r/c/mediawiki/skins/Cosmos/+/810127
`mwscript extensions/ManageWiki/populateWikiSettings.php skin --skin=cosmos --wgsetting=wgCosmosUseWVUISearch --sourcelist=false --remove` needs to be ran.
> Remove the `$wgCosmosUseWVUISearch` config

- LocalSettings.php
Following a discussion with 2 other Stewards, we have decided that it would be beneficial to add the `abusefilter-privatedetails` and `abusefilter-privatedetails-log` to the `checkuser` group as this would aid in abuse investigations when checking thwarted actions in the AbuseLog which are not in CheckUser. Wikimedia also has these two rights assigned to their `checkuser` group to aid in abuse investigations.
> Add AbuseFilter rights to CheckUser group

- LocalSettings.php
Temporarily swapping out the web badge for a special version while the anniversary goes on, to be reverted once the anniversary is done
> Change web badge for anniversary

- LocalSettings.php
Anniversary celebration is over so the web badge can be reverted to normal; reverts miraheze/mw-config#4824
> Revert special web badge

- GlobalCache.php
Fixed upstream. To be done once GroupsSidebar is updated.
Per https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GroupsSidebar/+/756003.
> Enable sidebar cache even if using GroupsSidebar

- LocalSettings.php
Also, remove `$wgUploadSizeWarning`, there is no reason to set the warning to the same as the max upload size.
> T9673: set `$wgMaxUploadSize` to 10MB for dragdownwiki

- LocalSettings.php
Autocreation is not needed on internal wikis and having accounts not be created automatically would provide more clarity for users that X wiki is not meant for help, as people have been confused before on the purpose of some of these wikis if they can't access them
> Prevent autocreation on internal wikis

- LocalSettings.php
(Maybe this should be an option in ManageWiki.)
> Make CodeMirror default for isvwiki

- LocalSettings.php
Adds 2FA requirements to Steward, GS, CU/OS groups (per RfC) and restricts some very sensitive rights from being used without 2FA regardless of group membership
> Require 2FA for certain groups/rights

- Sitenotice.php
Per title, this updates the sitenotice to inform users why they might not be able to do certain things
> Update sitenotice to inform users of ongoing maintenance

- GlobalSettings.php
To be able to use commons wiki under swift, they have to use the static.miraheze.org for now until it's migrated.
> Fix commons wiki static url for swift hosts

- LocalSettings.php
To-do once ImportDump is updated. With miraheze/ImportDump#28 it no longer uses the UploadPath, so this is now necessary to give the full file path.
> Add upload path for ImportDump on metawiki

- LocalSettings.php
Per [community proposal](https://meta.miraheze.org/wiki/Special:PermaLink/276371#Request_for_Feedback:_making_syntax_highlighting_enabled_by_default).
> Enable CodeEditor and CodeMirror extensions by default

- FileBackend.php
Not just for those that enable wmgPrivateUploads as we don't pass the cookies on thus when a thumb swift side 404's we call out to thumb_handler but the cookies aren't passed. Thus you get a 404 error.
> Call thumb_handler for thumbs on private wikis

- FileBackend.php
levels being zero seems to be equivalent to nothing at all. Anything other than levels being zero broke everything, and this is not needed for us unless we have very massive wikis, which none of our wikis needs to use container sharding, and also I believe it requires additional configuration to support it.
> FileBackend: remove shardViaHashLevels

- LocalSettings.php
- initialise/MirahezeFunctions.php
Additionally, this was added to `/srv/mediawiki/w/extensions/CentralAuth/includes/User/CentralAuthUser.php` on line 2623
```php
if ( !in_array( $row->lu_wiki, $GLOBALS['wgLocalDatabases'] ) ) {
continue;
}
```
> Apply local hacks

- LocalSettings.php
- ManageWikiSettings.php
Citizen added Noto Sans CJK fonts support recently in [9b9b361](https://github.com/StarCitizenTools/mediawiki-skins-Citizen/commit/b89873d99cf92beca64bf4c0c4ba2c0f9161f8a2).
This PR will add the config to ManageWiki.
> Add Citizen Enable CJK fonts config

- LocalSettings.php
This is to see if we get more info on why it has issues sometimes.
> Set redis logging channel to info as a experiment

- Sitenotice.php
Don't enable on originally migrated wikis, only newly migrated wikis.
> Re-enable Swift site notice for migration

- LocalSettings.php
- ManageWikiSettings.php
This setting is useful for private wikis which would like to make a large proportion of pages public (e.g. an entire namespace).
See https://www.mediawiki.org/wiki/Manual:$wgWhitelistReadRegexp
> Add `$wgWhitelistReadRegexp`

- FileBackend.php
Otherwise `$wgUploadThumbnailRenderMethod` does nothing.
> Set thumbnail configs

- LocalSettings.php
Add it to wgCreateWikiDatabaseClustersInactive in preparation for the migration tomorrow.
> Remove c2 from wgCreateWikiDatabaseClusters

- LocalSettings.php
This pull request adds a new grant, (usedatadumpapi). This grant contains all the DataDump extension rights, allowing usage of the DataDump API via OAuth and bot passwords.
> Add the DataDump rights to a new grant

- LocalSettings.php
Assigning some of these rights to the `*` and `user` groups bypasses our AbuseFilters and is dangerous overall so we should blacklist these.
> Add rights to ManageWiki blacklist

- LocalWiki.php
- ManageWikiSettings.php
https://phabricator.miraheze.org/T10440
The Pivot skin has an uncommon approach to settings: it doesn't register any configuration variables in skin.json, instead, it accesses an unregistered $wgPivotFeatures global array, and compares it with an internal variable to see if there are any new settings (https://github.com/wikimedia/mediawiki-skins-Pivot/blob/994a682983f867964e0486eb65a79aa2c410bab9/Pivot.skin.php#L13).
The idea here is to make them available through a ManageWiki "list-multi-bool" setting. If not possible due to the way the extension handles configuration, then just add the settings requested there to that wiki's section on LocalWiki.php.
> T10440: Add some Pivot settings to ManageWiki

- LocalWiki.php
Requested on Phabricator: https://phabricator.miraheze.org/T10496
sagan4betawiki is a rename of sagan4wiki (https://phabricator.miraheze.org/T10375), which is now a new wiki.
> T10496: Allow RAND in Cargo for sagan4beta

- LocalWiki.php
- Special:UploadFile doesn't exist, change to Special:Upload
- Explicitly set namespace for the link to Draft:Portal. I'm not sure if AdminLinks honors namespaces
> T10323: Fix errors with previous commits

- LocalSettings.php
i18n has been updated and the global group's name has also been changed to match all other groups names so this is the final step in renaming the group.
> Rename globalsysop to global-sysop

- LocalSettings.php
seems to be a bug in MW 1.39 that suppressrevision no longer allows one to view (or modify the suppressed status of) suppressed revisions.
> add viewsuppressed to oversight

- LocalWiki.php
This adds support in the form to contact CVT if someone is globally blocked via the form instead of via email
> Modify metawiki Special:Contact

- GlobalCache.php
Leave only session cache on memcached-mem-2, as my idea for the reason session loss is happening lately (T10456) is that memcached usage has increased, leading to key evictions and loss of session cache.
> Move main cache and message cache to memcached-mem-1

- ManageWikiExtensions.php
PR to install the Splash skin on Miraheze following the security review and approval of T9853.
> T9853: Install Skin:Splash in ManageWiki

- LocalSettings.php
Same case on hkrailwiki with leborkwiki and bluepageswiki ([T10430](https://phabricator.miraheze.org/T10430), [T10445](https://phabricator.miraheze.org/T10445), [T10547](https://phabricator.miraheze.org/T10547)), Kartographer default settings by default causes 400 errors.
Also reordering import options for hkrailwiki in the order of common usage.
> Fix Kartographer configurations for hkrailwiki

- LocalSettings.php
This configuration should probably be the default if Kartographer maps do not work without it.
> Fix Kartographer in isvwiki

- LocalSettings.php
This is to add custom protection levels to the Scratchpad Wiki. Usually, I would request this on Phabricator, but it is not working correctly, at least at the time I submitted this. I also modified Hypopedia's too as relevant.
> Modifying $wgAvailableRights and $wgRestrictionLevels

- LocalSettings.php
- LocalWiki.php
- ManageWikiExtensions.php
Includes configuration of $wgCargoDBname to be equal to `$wgDBname . 'cargo'`
Intended for use with https://github.com/miraheze/MirahezeMagic/pull/413
> add new createCargoDB.php to cargo install

- LocalSettings.php
Following a discussion with Reception123 and due to technical issues with CentralAuth and accounts being attached to too many wikis loading slowly, this group is created for Stewards only to assign to their alts
> Create global-renamer group on Meta

- LocalSettings.php
This PR has removed old CentralAuth configurations which have been removed for a while like wgCentralAuthSilentLogin and wgCentralAuthAutoNew (compare with https://github.com/wikimedia/mediawiki-extensions-CentralAuth/blob/REL1_39/extension.json).
This PR also sets wgCentralAuthGlobalBlockInterwikiPrefix to to the "meta" interwiki prefix to link global blocker user page links to Meta and also sets wgCentralAuthOldNameAntiSpoofWiki to "metawiki" to check Meta's AntiSpoof database instead of the local database for possible impersonations following renames.
Also enables a global rename denylist.
> Changes to CentralAuth config

- LocalSettings.php
I want to modify these restriction levels for the Scratchpad Wiki here on Miraheze and show them in order. I am also adding templateeditor, extendedconfirmed, moderator, and bureaucrat permissions to $wgAvailableRights. I understand that the '', 'user', 'autoconfirmed', and 'sysop' groups are already defined by default, but I want them to be in order on the wiki I'm administrating. Thank you.
> Modify $wgAvailableRights and $wgRestrictionLevels

- ManageWikiExtensions.php
This commit changes the description of SMW so that, instead of saying to run setupStore on all mw* servers, it recommends following the instructions at https://meta.miraheze.org/wiki/Tech:Semantic_MediaWiki.
> Update Semantic MediaWiki's description on ManageWiki

- LocalSettings.php
- Removes metawiki autopatrolled protection level, will be assigned via ManageWiki instead for easy controlling
- Renames autopatrolled level to editautopatrolprotected
- Renames consul and bureaucrat protection level to editconsulprotected and editbureaucratprotected, per wmfphab:T230103
> Remove metawiki autopatrol protection level + rename

- LocalSettings.php
Currently, you can only login with your security key to the wiki you registered on. This change will allow your security key to work on all *.miraheze.org domains (but still not custom domains). i18n should be updated accordingly. I will test this out tomorrow.
> Set WebAuthn configuration to allow security key login on all *.miraheze.org

- LocalSettings.php
Reverts miraheze/mw-config#5232
This is temporarily reverted to allow the small subset of users with this enabled to switch to TOTP temporarily or disable it.
> Revert "Set WebAuthn configuration to allow security key login on all *.miraheze.org"

- GlobalExtensions.php
- LocalWiki.php
They should only be loaded on Meta as that's where they're used exclusively.
> Remove ImportDump and IncidentReports as global extensions

- GlobalExtensions.php
- GlobalSettings.php
Eventually, this will be our main parser. In preparation, let's make it available for everyone.
For now, this will have little impact apart from making the rest API open to all wikis. (Although you shouldn't be rest.php for bots as it isn't stable). In future, wikis will be able to start testing Parsoid for reads which will be coming to Miraheze in about 7 months time.
> Enable the Parsoid extension on all wikis

- GlobalSettings.php
- LocalSettings.php
- ManageWikiSettings.php
Remove wgSVGConverter from ManageWiki as we only want one option and to default to it as well.
> Change wgSVGConverter to use rsvg

- LocalSettings.php
Large wikis can cause problems when this value is set to 0 (default).
> Set wgExportMaxHistory to 1000

- GlobalSettings.php
- LocalSettings.php
Only set wgSkinMetaTags if WikiSeo isn't enabled as the extension provides similar functionality.
> Set wgSkinMetaTags

- GlobalExtensions.php
> Don't use Renameuser on mw 1.40+ as it's bundled into core now

- GlobalSettings.php
- LocalWiki.php
Fix "Universal sign-on may be broken in newer Google Chrome versions due to SameSite cookie policy" by setting wgCookieSameSite and wgUseSameSiteLegacyCookies.
> Set wgCookieSameSite and wgUseSameSiteLegacyCookies

- LocalSettings.php
$wgCentralAuthCreateOnView has been removed in 1.40 and thus now does nothing.
> Remove $wgCentralAuthCreateOnView (T9913)

- LocalSettings.php
Does not do it on cli and MediaWiki will override it where appropriate.
> Send "Cache-control: no-cache" header by default

- robots.txt
It's set in the php version as we need access to wgServer
> Remove sitemap from robots.txt

- LocalSettings.php
Disable PageProperties globally due to issues and pending a security review.
> Disable PageProperties globally

- GlobalSettings.php
- LocalSettings.php
- ManageWikiSettings.php
This variable is used for a hook that adds a link to the wiki's Special:Contact page to the footer.
While in ManageWiki it is set as a variable from the ContactPage extension, it is not. It's set like that so that it will only appear if ContactPage is enabled
As of writing, I'm not sure of the naming convention or where the hook should be, so I set it to wmgMirahezeContactPageFooter and added it to LocalSettings.php, respectively. I don't see any examples to go off by anyway.
> T11040: Create $wmgMirahezeContactPageFooter

- LocalSettings.php
- ManageWikiSettings.php
See https://phabricator.miraheze.org/T11673
wgCitizenPortalAttach was removed from Citizen. Default value for wgCitizenGlobalToolsPortlet and the help string are from https://github.com/StarCitizenTools/mediawiki-skins-Citizen/blob/e985f863bc00c2158fc87f45884efc13a3b92478/skin.json#L619-L620
> T11673: Add wgCitizenGlobalToolsPortlet & remove wgCitizenPortalAttach

- LocalSettings.php
Extension does not work on MW 1.41
> Disable RatePage Temorarily

- GlobalSettings.php
Jobrunner croaks on log messages so only log error messages rather than notices and deprecated messages.
> Only show errors when running runJobs from inside jobrunner

- GlobalExtensions.php
> Remove logic that disables Renameuser extension

- LocalSettings.php
https://operations.osmfoundation.org/policies/tiles/.
Setting it to `osm-intl` will never work
> Set wgKartographerDfltStyle to .

- LocalSettings.php
So CreateWiki's cacbe can still be reset so that this loads after CreateWiki (and other extensions) are loaded and if a wiki is undeleted it may know that (T11888)
> Delay DeletedWiki.php until after everything else is loaded

- LocalSettings.php
With the new static URL for footer icon and removal of the old configs from lhmnwiki and snxyzincubator (now defunct)
> Update LocalSettings.php for lhmnwiki

- ManageWikiExtensions.php
Adding semantic drilldown. Semantic drilldown is already in mediawiki-repos.yaml, so I assume that no more work is required to add it other than putting it in the managewikiextensions thing.
> Adding semantic drilldown

- LocalWiki.php
Does not provide any useful data at the moment and just creates more code that has to be loaded by the user's browser. I might enable it in the future if I have any use for it.
> Disable Matomo for genshinimpactwiki

- LocalSettings.php
They're currently malfunctioning, so we'll have to go back to doing the imports manually for now
> Disable the automated ImportDump jobs temporarily

- LocalSettings.php
- ManageWikiSettings.php
Following on from https://github.com/Universal-Omega/PortableInfobox/pull/122, a friend and I are hoping to use [`PortableInfobox`](https://github.com/Universal-Omega/PortableInfobox) in [a wiki](https://rainverse.wiki) we help maintain, but we want image anchor `href`s to link not to the file source, but to the File: namespaced page instead. The new config option has merged, and now I guess we need a way to change it from default. My friend wrote the patch, but GitHub prevented her creating an account so I'm helping with the PR (hence the log: "**BlankEclair** authored and **AverageHelper** committed"). I have no means of testing this code myself.
This PR should allow maintainers to set the new `PortableInfobox` config option to change where image links go, keeping the previous behavior …
> Add `wgPortableInfoboxUseFileDescriptionPage`

- GlobalSettings.php
https://kinsta.com/blog/svg-vs-png/
Also the svg on MH Commons has a way smaller file size than the svg on Wikimedia Commons so that's why I'm linking to MH Commons instead
> Change the license image to be an svg

- ManageWikiExtensions.php
Flow is a fairly problematic extension, and WMF is officially dropping support for it.
https://www.mediawiki.org/wiki/Structured_Discussions/Deprecation
Make the extension restricted, as we really shouldn't be moving new wikis into Flow.
> Move StructuredDiscussions (Flow) to managewiki-restricted

- LocalSettings.php
A task has not been made for this, since I'm guessing I don't need to for configuration changes like these. I'm happy to make one if I have to though,
Chain of permission: [User:BlankEclair on rainversewiki has bureaucrat and sysop](https://rainverse.wiki/wiki/Special:UserRights/BlankEclair), and both that account's [user page](https://login.miraheze.org/wiki/User:BlankEclair) and its [corrosponding account on Phorge](https://issue-tracker.miraheze.org/p/BlankEclair/) lists BlankEclair on Github as her (my) account
Reason for change: Those two domains flood RottenLinks with 403s, causing it to be useless from all the noise
> Exclude www.deviantart.com and jocelynsamara.deviantart.com from RottenLinks testing on rainversewiki

- LocalSettings.php
Also, this removes the long-gone `hypopediawiki` from the config and replaces it with `hypotheticalweatherwiki` that is now present. If there are any problems with this request please let me know. Thanks!
> add custom restriction levels to hypotheticalweatherwiki

- ManageWikiSettings.php
Here's how it looks like right now:
> $wgRSSAllowLinkTag: Escape HTML

- LocalSettings.php
Reverts miraheze/mw-config#5617
Done debugging, reverting to prevent log spam.
> Revert "Turn on debug logging for Math"

- LocalWiki.php
turns out configuring short-title is also needed, otherwise FeaturedFeeds will call wfMessage(NULL)
> add short-title to metawikibeta's FeaturedFeeds

- LocalWiki.php
I requested this a code be added in #5541, but the code never actually worked (it only worked on my test wiki), and now all of spacewiki is being rewritten, so the code isn't needed anymore.
It doesn't actually affect the wiki if the code isn't removed, so you can close and ignore this if you find it unnecessary.
> Remove spacewiki code in LocalWiki.php

- LocalSettings.php
Evelution now supports MediaWiki 1.42 in version [156.0.0](https://github.com/AWikia/SkinEvelution/releases/tag/156.0.0) and above. I have also tested locally, and it doesn't fail immediately (the missing icons are due to my browser):
> Reenable Evelution for MediaWiki 1.42

- LocalSettings.php
After this is merged, someone will need to do an in-place reindex of the database to unbreak prefix searching (per [$wgCirrusSearchPrefixSearchStartsWithAnyWord documentation](https://gerrit.wikimedia.org/g/mediawiki/extensions/CirrusSearch/+/fb3853fd0439aa1f0763fabd21c921d3c538c763/docs/settings.txt#464)). CirrusSearch's README has [examples](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/CirrusSearch/+/fb3853fd0439aa1f0763fabd21c921d3c538c763/README#153).
> T12195: Enable $wgCirrusSearchPrefixSearchStartsWithAnyWord on rainversewiki

- GlobalSettings.php
Since we only need host, we can just use simple parse_url, since we can't use the UrlUtils service from this config instance. Services won't be loaded yet.
> Replace deprecated wfParseUrl

- initialise/entrypoints/index.php
Reverts miraheze/mw-config#5598
Didn't do anything. I think this may need done in decode.php instead.
> Revert "T12214: Avoid redirects if action=raw is set"

- LocalWiki.php
We have some problems on UploadWizard.
We want to use more simple choices.
We are expecting to these choices.
These are our old version wiki before transporting in Miraheze.
So, we want to disable some choices if we can.
I created some message pages like below, but these seems to be not working.
- https://kagaga.jp/wiki/MediaWiki:Wm-license-cc-free
- https://kagaga.jp/wiki/MediaWiki:Wm-license-cc-free-to-share-header
- https://kagaga.jp/wiki/MediaWiki:Wm-license-cc-free-to-share-text
I know this is template error, but I couldn't find any solutions so please let me know them.
This template was imported from Wikipedia and not any changes.
https://kagaga.jp/wiki/テンプレート:Cc-by-sa-4.0
> Update UploadWizard settings for kagagawiki

- LocalSettings.php
Turns out that you can't give the edittemplateprotected right using ManageWiki, I'm hoping that adding it to $wgAvailableRights will make it automatically pop up on there.
> Add edittemplateprotected to $wgAvailableRights on cricketnepalwiki

- ManageWikiExtensions.php
If I understand right, this and https://github.com/miraheze/mediawiki-repos/pull/30 together should add the GoogleForms extension to `Special:ManageWiki/extensions`.
> T12447: Add GoogleForms

- LocalWiki.php
$wgEnableTranscode should, in theory, disable transcoding. However, there is (probably) a bug upstream that makes it not fully honor that setting. For now, we'll just do a workaround to make the extension chill out, and perhaps revert this commit once the extension is fixed.
Miraheze issue tracker task: https://issue-tracker.miraheze.org/T12565
Relevant upstream task: https://phabricator.wikimedia.org/T374433
> T12565: Fully disable transcodes for hommwiki

- LocalSettings.php
Adding new protection level and Turns out that you can't give the editbureaucratprotected right using ManageWiki, I'm hoping that adding it to $wgAvailableRights will make it automatically pop up on there.
> Add editbureaucratprotected to cricketnepalwiki and $wgAvailableRights

- LocalSettings.php
Currently, /w/img_auth.php URLs cannot be used for TemplateStyles, which is problematic for private wikis (example: #general in Discord/#miraheze-offtopic on IRC, at 2024-09-17 10:17:35 UTC).
We allow `[a-zA-Z0-9\-]\.(miraheze|wikitide)\.org/w/img_auth.php` for Miraheze controlled domains, and `{$wi->server}/w/img_auth.php` for custom domains. In the event that the wiki is not a custom domain, it will fallback to the Miraheze domain and would effectively be a no-op.
> Allow *.{miraheze,wikitide}.org and the custom domain for TemplateStyles

- LocalSettings.php
Adding new protection level and Turns out that you can't give the editconsulprotected right using ManageWiki, I'm hoping that adding it to $wgAvailableRights will make it automatically pop up on there.
> Add editconsulprotected to cricketnepalwiki and $wgAvailableRights

- LocalSettings.php
On wikis that don't have cargo enabled, it would throw a "wgCargoAllowedSQLFunctions" is undefined warning.
> Fix "wgCargoAllowedSQLFunctions" being undefined

- LocalSettings.php
- LocalWiki.php
It would be an empty array otherwise, which makes every function unusable
> Set $wgCargoAllowedSQLFunctions in LocalWiki.php

- LocalSettings.php
Confirmed to be compatible with 1.42 since stable 4.39.1
More info: https://tweeki.kollabor.at/wiki/Installation#Compatibility
> Re-enable Tweeki skin

- LocalSettings.php
Have CodeMirror be activated by default on Abyssal Wiki
> CodeMirror configuaration for abyssalwiki

- GlobalExtensions.php
Wikia patched MW core here https://github.com/Wikia/mediawiki/commit/026bf08a8f8d75a4051360833cbae75fedec7f45#diff-d7164aa57d47793e3b563b5d4d90b7b5cd9909bd53b5fdb5b22bb7d6e45d75d7R998 to get it working.
Lets disable this.
> Remove MessageCachePerformance

- LocalWiki.php
Per T12767: Added a check to see if the `SocialProfile` extension is active before requiring the `EditCount.php` file.
> lhmnwiki: Check for active extension before calling EC.php

- LocalSettings.php
This was changed in https://github.com/wikimedia/mediawiki-extensions-TitleKey/commit/a37af77932c71fb32311f73f99a19ba23f18cacc#diff-6a6295f752062fb0eec4a9df4e87c164b8d8d3b48023a54a1e682671296eb8a3R56
> Fix class used for TitleKey in wgSearchType

- GlobalSettings.php
We don't use the MessageCachePerformance extension anymore
> Remove $mcpMessageCachePerformanceMsgPrefixes

- GlobalCache.php
Not sure if us setting this to 1 day without using kask etc is causing us issues. Lets just unset this for now.
> Unset wgObjectCacheSessionExpiry

- Database.php
- LocalWiki.php
- rpc/RunJobs.php
It appears that this is the default here https://github.com/wikimedia/mediawiki/blob/4bd27f449569c211f6e74fa48e4e6ed6506d4a27/includes/libs/rdbms/lbfactory/LBFactoryMulti.php#L159
But we want to set maxConnCount I think, as some times we have an issue where a db server goes down it gets overloaded when it is back online. It's basically the same fix as https://phabricator.wikimedia.org/T360930
> Set LoadMonitor

- LocalWiki.php
It can only be three types: https://github.com/wikimedia/mediawiki-extensions-UploadWizard/blob/a3a6ee9120ac506a1701f4d9d32667b08eaca2a4/includes/Specials/SpecialUploadWizard.php#L228
Bug: T12965
> Fix ownWorkDefault for lhmnwiki

- LocalWiki.php
I believe this is allowed because of the existence of these:
* https://github.com/miraheze/mw-config/blob/22aa68fe1d053ed038ee42129a90930e3973e741/LocalWiki.php#L52
* https://github.com/miraheze/mw-config/blob/22aa68fe1d053ed038ee42129a90930e3973e741/LocalWiki.php#L583-L584
Closes T12963
> T12963: Raise DPL limits for gui7814sgtafanonwiki

- LocalWiki.php
> T12969: Add requested hook for acuralegendwiki

- LocalSettings.php
Ticket (https://issue-tracker.miraheze.org/T13125) claims the protection doesn't work. b4803e5 added both protection level as well as the right, however protection level name had a typo in it. [$wgRestrictionLevels](https://www.mediawiki.org/wiki/Manual:$wgRestrictionLevels) requires a "list of permission keys that can be selected for each [restriction type](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:$wgRestrictionTypes)" which means that the key is likely not found and the protection doesn't appear to be working.
> T13125: Fix typo in protection level name for googlewiki

- LocalSettings.php
Get interwiki links to open in a new tab for the Popular Music Studies Wiki.
> Open interwiki links in new tab

- LocalSettings.php
Addressing https://issue-tracker.miraheze.org/T13205 by adding license from forked from wiki (https://animalroyale.fandom.com/zh/wiki/Super_Animal_Royale_Wiki:%E7%89%88%E6%9D%83 https://meta.miraheze.org/wiki/Special:RequestWikiQueue/54687) as well as fixing an issue with lacking link for animalroyale wiki since a proper DB name wasn't used (there is currently no link).
> T13205: Changing license for animalroyalezhwiki and fixing license link for animalroyalewiki

- LocalWiki.php
No issue tracker tasks are required.
Forms:
* Default (for any other inquiries) - send to `hotro@lophocmatngu.wiki`
* Copyright removal handling (through Viet Nam's copyright laws) - send to `banquyen@lophocmatngu.wiki`
More technical details on what I changed:
https://www.mediawiki.org/wiki/Extension:ContactPage
https://gerrit.wikimedia.org/g/mediawiki/extensions/ContactPage/+/HEAD/README
https://www.mediawiki.org/wiki/HTMLForm
> Configure custom contact forms for lhmnwiki

- LocalSettings.php
Address T12977. Not sure if the issue will be completely fixed, but this config seems to be the culprit.
> Remove 2880 as a candidate MultimediaViewer thumbnail size for Strinova Wiki

- LocalSettings.php
Should ideally fix issues where empty elements with this class show up in parsing and cause extract extracts to return nothing/"." as the text.
> Add mw-empty-elt class to wgExtractsRemoveClasses

- LocalSettings.php
Since the default tile server is `tile.openstreetmap.org` and that server only supports 1x tiles, it makes sense for the default `$wgKartographerSrcsetScales` to be an empty array which, according to the Kartographer docs, will implicitly include `1`. There shouldn't be overrides for individual wikis unless they use a different tile server which supports tile scaling.
> Doesn't need to start with 1, this happens automatically. Note that most tile servers don't support this at all and thus require setting this to an empty array.
— [Kartographer docs](https://www.mediawiki.org/wiki/Extension:Kartographer#Configuration)
> Set default `$wgKartographerSrcsetScales` to empty array

- LocalWiki.php
It was reported to not really work on Discord... Maybe going alerts would be better?
https://issue-tracker.miraheze.org/T13303#266801
<https://wm-bot.wmcloud.org/browser/index.php?start=03%2F05%2F2025&end=03%2F05%2F2025&display=%23miraheze-tech>:
```
[05/03/2025 15:40] <MirahezeRelay> <theoneandonlylegroom> can you make the other way round
[05/03/2025 15:40] <MirahezeRelay> <theoneandonlylegroom> notifs to alerts
```
> T13303: Make every Echo event an alert on softcellwiki

- LocalSettings.php
- ManageWikiNamespaces.php
Adding the `$wgRPRatingAllowedNamespaces` namespace configuration variable for RatePage per [T13145](https://issue-tracker.miraheze.org/T13145).
> Updating RatePage configuration options

- LocalSettings.php
Currently the badge shows inappropriate license that doesn't correspond to the license that we have set on the wiki (let me know if I need to make a ticket)
> Update Super Animal Royale license badge

- LocalSettings.php
- ManageWikiExtensions.php
Per [T13411](https://issue-tracker.miraheze.org/T13411), [Skin:Eveskin](https://www.mediawiki.org/wiki/Skin:Eveskin) was archived on March 25th as it hasn't been updated to work with MediaWiki 1.42 and the repository for the skin was archived by the creator, therefore it needs to be removed, and as it is already in a disabled state on Miraheze there is no need to globally disable it as an enabled skin on wikis as that has already been done.
> Undeploy Skin:Eveskin per T13411

- LocalWiki.php
Configuration change for the Constant Noble Wiki to raise maxCategoryResults from the default of 4 to 100 per [T13482](https://issue-tracker.miraheze.org/T13482).
> Configuration change per T13482

- LocalWiki.php
Adding the `$smwgDVFeatures` global variable and defining all the default values along with adding `SMW_DV_PVUC` at the end to enable the ["Special property has uniqueness constraint"](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Has_uniqueness_constraint) option per [T13503](https://issue-tracker.miraheze.org/T13503).
> Updating LocalWiki.php settings for Constantnoblewiki per T13503

- SemanticMediaWiki.php
Adding the `$smwgDVFeatures` global variable and defining all the default values along with adding `SMW_DV_PVUC` at the end to enable the ["Special property has uniqueness constraint"](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Has_uniqueness_constraint) option per [T13503](https://issue-tracker.miraheze.org/T13503).
This time, this PR shouldn't break their wiki like it did when defined through `LocalSettings.php`.
> Updating SemanticMediaWiki.php settings for Constantnoblewiki per T13503

- LocalSettings.php
While updating footer icon with appropriate license in my previous commit, apparently it overwrote a default resulting in Miraheze logo disappearing from the footer. This commit is to correct this grave mistake.
> Fixed overwrite of default from 86d3e0c

- LocalSettings.php
This change grants `securepoll-edit-poll` permission to the `electionadmin` group on metawiki.
Without this permission, they will be unable to edit poll settings or correct issues in the configuration via the SecurePoll. As the Community Directors Elections are scheduled to begin in 2 days, it would be greatly appreciated if this change could be reviewed and deployed in a timely manner to ensure everything is ready in advance.
Thanks in advance for your support!
> Add securepoll-edit-poll perm to electionadmin on metawiki

- LocalSettings.php
Updating requestwiki to enforce 1 request created within 72 hours 
Users are currently gaming the system by resubmitting near-duplicate requests to get an AI re-review, increasing strictness of requestwiki behaviors further prevents bulk-spamming/frivolous requests.
> Update LocalSettings.php  > RW 1 req per 72h

- LocalSettings.php
- ManageWikiSettings.php
Adds all three settings ([docs](https://www.mediawiki.org/wiki/Extension:NewUserMessage#Configuration)) of the extension to ManageWiki which resolves https://issue-tracker.miraheze.org/T13612 (`$wgNewUserMessageOnAutoCreate` was requested, I added the other two ones as well since they weren't in ManageWiki either).
`$wgNewUserMessageOnAutoCreate` will have to be set to true for `nmfwikiwiki` via ManageWiki when this is merged since this was specified in LocalSettings before this change.
> T13612: Add settings for NewUserMessage

- ManageWikiExtensions.php
This user right has been added to Translate [a while ago](http://phabricator.wikimedia.org/T49177) and is required for translations to be marked as no longer outdated.
This fixes tasks like T13297 and T13523.
Translate grants this permission by default as well: https://github.com/wikimedia/mediawiki-extensions-Translate/blob/master/extension.json#L1524
> Grant 'unfuzzy' right of Ext:Translate to *

- SemanticMediaWiki.php
Now that I fixed race conditions in running install scripts in ManageWiki, this *should* no longer be necessary as scripts now run properly after extension has already been loaded.
> Remove SMW hack

- LocalSettings.php
Removing `w` from [$wgExtraInterlanguageLinkPrefixes](https://www.mediawiki.org/wiki/Manual:$wgExtraInterlanguageLinkPrefixes) on commonswiki since
* it breaks interwiki links using the `w` prefix for linking to Wikipedia (by moving the links to the language selector, while they are supposed to be in the text)
* not a single page appears to be using `w` as an interlanguage link intentionally (while the others like `eswiki` are used as interlanguage links), leading to many descriptions and templates missing these links in their text
* ULS does not even display a label for interlanguage links using this prefix, thus making them dysfunctional on Vector 2022, the default skin on commonswiki
Task: https://issue-tracker.miraheze.org/T13467
> T13467: Remove 'w' from wgExtraInterlanguageLinkPrefixes for commonswiki

- LocalSettings.php
- ManageWikiSettings.php
This feature was added in citizen 3.1.0: https://github.com/StarCitizenTools/mediawiki-skins-Citizen/releases/tag/v3.1.0
Creating this as a draft since citizen hasn't been updated to 3.1.0 yet
> Add $wgCitizenEnableCommandPalette

- ManageWikiExtensions.php
I noticed this while having a script try to identify the wikibase namespace on miraheze wikibases
The content model was wrong, so hard to figure
out automatically, unless just looking at the text name>
Example of correct defaults
https://addshore-alpha.wikibase.cloud/w/api.php?action=query&meta=siteinfo&siprop=namespaces|statistics&format=json
Example of currently pre merge bad defaults
https://ortaturk.miraheze.org/w/api.php?action=query&meta=siteinfo&siprop=namespaces|statistics&format=json
> Fix wikibase namespace contentmodels

- LocalSettings.php
Set $wgCategoryCollation to 'uca-es' for rapanuidictionaryprojectwiki.
https://issue-tracker.miraheze.org/T13750
> T13750: set $wgCategoryCollation for rapanuidictionaryprojectwiki

- LocalSettings.php
- ManageWikiSettings.php
Added:
- `wgTabberNeueAddTabPrefix` to LocalSettings and ManageWiki
- `wgTabberNeueParseTabName` to LocalSettings and ManageWiki
Removed:
- `wgTabberNeueEnableMD5Hash` (unused by TabberNeue)
Other changes:
- Moved `wgEnableProtectionIndicators` from TabberNeue section
Resolves [T13882](https://issue-tracker.miraheze.org/T13882).
https://www.mediawiki.org/wiki/Extension:TabberNeue#Configuration
> Add TabberNeue configuration options to LocalSettings and ManageWiki

- ManageWikiSettings.php
- Sitenotice.php
"descritption" -> "description"
End comment at L53 of Sitenotice.php instead of starting a new one.
> Fix: typo in wgShortDescriptionEnableTagline/help; Sitenotice.php comment

- LocalSettings.php
Rename protection level and define order for cgwiki
> cgwiki: Protection level fix

- LocalSettings.php
Adds `editinterfaceadminprotected` for starstruckwiki to:
- wgRestrictionLevels
- wgAvailableRights
Resolves [T13958](https://issue-tracker.miraheze.org/T13958).
> T13958: Add editinterfaceadminprotected for starstruckwiki

- ManageWikiExtensions.php
Backtrace:
```
[121f735b012f0a66102a7db3] /wiki/Special:PageTranslation Wikimedia\Rdbms\DBQueryError: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading or after adding a new extension?
Please see https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:Upgrading and https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:How_to_debug for more information.
Error 1146: Table 'exttestwikibeta.translate_message_group_subscriptions' doesn't exist
Function: MediaWiki\Extension\Translate\MessageGroupProcessing\MessageGroupSubscriptionStore::getSubscriptions
Query: SELECT tmgs_group,tmgs_user_id FROM `translate_message_group_subscriptions` WHERE tmgs_group = 'page-Translate'
Backtrace:
from …
```
> Add missing sql table for Extension:Translate

- LocalSettings.php
I apparently did a mistake when requesting on Phorge. This swaps $2 and $1 in the URL
> Fixes my mistake on T14052

- LocalSettings.php
- ManageWikiNamespaces.php
- ManageWikiSettings.php
Found with PHPStorm.
I've removed the first occurrences of the duplicated keys, so there shouldn't be any behavioural changes as the second value overrides the first one anyways.
> Remove duplicated settings and array keys

- Wikibase.php
The default was changed on MediaWiki 1.44 breaking adding new items and other stuff as it creates 2 namespaces of the same name with different IDs (860 and 120) because it makes Wikibase use 120 but our setup in ManageWikiExtensions uses 860. This can be migrated to 120 at a later time.
> Wikibase: set defaultEntityNamespaces to false

- ManageWikiSettings.php
There is a dedicated page for changing logos, so use that instead of directing users to a hidden text box on the ManageWiki page.
Translations are not an issue because [[ManageWiki]] was unmarked for translation a long time ago.
> Update help text for $wgLogo in ManageWikiSettings.php
