- LocalExtensions.php
- LocalSettings.php
- ManageWikiSettings.php
Adding CommentStream extension settings in ManageWiki 
It needs to be **revised**.
> Adding CommentStream settings in ManageWiki

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
Enable an extension per Phabricator item T5204.
> Enable Mermaid extension

- ManageWikiSettings.php
seems to be fine to allow it now
> unrestrict wgMaxImageArea

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
It has not worked since we migrated to actor.
The extension is incompatible with actor.
> Remove the news extension

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
> Add TemplateData as a standalone extension

- LocalSettings.php
Contributors are only requesters.
> Change license for airforcewiki and armywiki per T5738

- LocalSettings.php
A participant in the annual survey suggested this, and I don't think it's a bad idea, I have seen quite a few wikis related to politics and/or elections. @paladox @JohnFLewis any objections?
> add politics as a wiki category

- ManageWikiSettings.php
> + 60 and 90 to RC Link days

- Database.php
> Switch to db7

- LocalSettings.php
> Remove wgWikiDiscoverClosedList, wgWikiDiscoverInactiveListand wgWikiDiscoverPrivateList

- LocalSettings.php
Adding rule per the request of @RhinosF1 who I assume will comment with more regarding the reason for this request.
> Add '.*scratch' to rw blacklist

- LocalSettings.php
There is no change except by the author.
> Change license for wikigrowthwiki per T5872

- LocalWiki.php
Add Japanese Main page for my wiki.
> Add $wgWhitelistRead for swiki

- LocalSettings.php
Values can only be https://www.w3.org/TR/referrer-policy/#referrer-policies
> Fix wgReferrerPolicy

- LocalSettings.php
Reverts miraheze/mw-config#3173
> Revert "Disable createwiki temporarily"

- LocalSettings.php
This will allow CW to create on either db11/12.
> Add 'c2' to wgCreateWikiDatabaseClusters

- LocalSettings.php
It's causing unexpected issues.
Bug: T5931
> Disable wgEnableSidebarCache

- LocalSettings.php
> wmgTranslateDocumentationLanguageCode to qqq on metawiki

- Sitenotice.php
> rm anniversary sitenotice

- .travis.yml
See https://phabricator.wikimedia.org/T257879, will merge when we switch to 1.35
If that gets confirmed, I'll go and do the same on all other repos.
> Drop PHP 7.2 Check

- LocalSettings.php
> block indexing of NS_SPECIAL

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
Installing GlobalUsage extension per Phabricator item T4990
> Installing GlobalUsage extension

- ManageWikiExtensions.php
> restrict score extension

- LocalSettings.php
> add wikiapiary footer for circleyversewiki per req

- LocalSettings.php
> Correct prefix

- LocalSettings.php
i added a few wikis to wikiapiary
> Add monitored by wikiapiary links for 2 sites

- MissingWiki.php
> missing-wiki: add archive.org link

- LocalSettings.php
Adding a useful media/journalism category as we do have a number of other wikis which may appreciate this category, and per wiki request # 14221
> Adding media/journalism category to CreateWiki categories in LocalSettings.php

- ManageWikiSettings.php
Sorry, in my last PR, I did the wrong case, this is to fix that
> fix case for previous configs

- LocalSettings.php
Adding one of the major liberal arts/humanities academic disciplines, History, as a common sense category with lots of potential use
> Add common sense History category to CreateWiki

- GlobalExtensions.php
- LocalExtensions.php
- LocalSettings.php
- extension-list
for used on the ldapwiki only.
> Install LDAP extensions

- Sitenotice.php
> Remove site notice

- ManageWikiExtensions.php
https://phabricator.miraheze.org/T5863#123688
> MWE: add Score note

- LocalSettings.php
- LocalWiki.php
- ManageWikiSettings.php
Originally started by RhinosF1 at #3209 and redone by Reception123 at #3341
> Migrate Wikiapiary footer icons to ManageWiki.

- LocalSettings.php
Reverts miraheze/mw-config#3381
> Revert "Add $wgNewUserMessageOnAutoCreate for nmfwikiwiki (T6416)"

- LocalExtensions.php
- LocalSettings.php
- ManageWikiSettings.php
This comes after I added the skins type to ManageWiki (miraheze:managewiki[#192](https://github.com/miraheze/ManageWiki/pull/192)).
Should not be merged until @JohnFLewis finishes what is doing in CreateWiki/ManageWiki and updates ManageWiki in miraheze:mediawiki!
> Change type for $wgDefaultSkin to "skins"

- LocalSettings.php
https://github.com/wikimedia/mediawiki/blob/7e5f025690b39230c99be768880149410e411876/includes/Setup.php#L303
> Add default value for $wgGalleryOptions

- LocalSettings.php
- ManageWikiSettings.php
Reverts miraheze/mw-config#3401
Per John's comment.
> Revert "Migrate $wgSkipSkins to ManageWikiSettings"

- LocalExtensions.php
- LocalSettings.php
- ManageWikiNamespaces.php
miraheze/ManageWiki#200, miraheze/ManageWiki#201, #3410, and #3412 should be merged first.
> Move $wgManageWikiNamespacesAdditional to own file

- LocalSettings.php
Reverts miraheze/mw-config#3414
> Revert "Fix attempt for duplicate image categories"

- LocalWiki.php
Per https://github.com/wikimedia/mediawiki-extensions-RelatedArticles/blob/ec87247ad843d58d4dba41397af35e8954e6cb74/extension.json#L144
> Remove config that does not even exist

- ManageWikiNamespaces.php
Should not be merged until after miraheze/ManageWiki#200 is merged, and ManageWiki is updated in the mediawiki repository.
> Add $wgPreloaderSource to ManageWikiNamespaces (T4943)

- LocalWiki.php
arr.png no longer is in mediawiki core so let's link to the one uploaded to wikimedia.
> Fix link to "All Rights Reserved"

- LocalWiki.php
Add Main pages for some languages ​​and some special pages to the allow list.
> Add some pages to allowlist (whitelist) for swiki

- LocalExtensions.php
- ManageWikiExtensions.php
Reverts miraheze/mw-config#3483
> Revert "TemplateWizard requires TemplateData"

- LocalExtensions.php
- ManageWikiExtensions.php
Reverts miraheze/mw-config#3482
> Revert "Translate requires UniversalLanguageSelector"

- LocalExtensions.php
- ManageWikiExtensions.php
Reverts miraheze/mw-config#3484
> TemplateWizard requires TemplateData

- LocalExtensions.php
- ManageWikiExtensions.php
Reverts miraheze/mw-config#3485
> Translate requires UniversalLanguageSelector

- LocalSettings.php
Removes useless comment for something automatically done on wiki creation
> remove unnecessary comment

- LocalSettings.php
It's posting too much so let's slow it down.
Also tweak GlobalTitleFail so it's 1000 not 10000.
> Logging: Sample wfDebug channel

- LocalSettings.php
Per miraheze/MirahezeMagic#166
> remove SkinAddFooterLinks hook

- LocalExtensions.php
> LE: Remove Parsoid/JS config for VE (T6528)

- LocalExtensions.php
> LE: Remove Parsoid/JS config (T6528)

- LocalExtensions.php
Reverts miraheze/mw-config#3529
> Revert "LE: Remove Parsoid/JS config (T6528)"

- LocalSettings.php
Per https://github.com/wikimedia/mediawiki-extensions-MobileFrontend/blob/1421405c1fe4f3dbafe0cd18f43aa9054b974c4e/extension.json#L911
> set $wgMFAutodetectMobileView['default'] to true (hopefully will fix T6362)

- LocalSettings.php
Reverts miraheze/mw-config#3556
> Revert "set $wgMFAutodetectMobileView['default'] to true (hopefully will fix T6362)"

- LocalExtensions.php
Reverts miraheze/mw-config#3549
> Revert " set $wgGenerateThumbnailOnParse to true if PdfHandler is enabled (to fix T6469)"

- Redis.php
I want to experiment to see if this boost performance. Already tested on test2 to confirm that there wont be any bad side affects.
> Cache: Set some configs to use redis-central

- LocalSettings.php
I ve fixed it per manual on mw.org, this should work.
> fix import sources for mrjaroslavikwiki

- LocalWiki.php
It still sucks. Why was it undid after all?
Ref: #2557
> Redo #2557

- LocalWiki.php
Reverts miraheze/mw-config#3570
> Revert "Redo #2557"

- LocalSettings.php
> wgDefaultUserOptions: Set rcenhancedfilters-disable to 1 for reviwikiwiki

- LocalSettings.php
- LocalWiki.php
This adds two interwiki import sources and one page to the read whitelist for r4356thwiki (a private wiki). Thank you.
> Configuration Changes for r4356thwiki

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
Reverts miraheze/mw-config#3596
> Revert "Add Validator extension (T6613)"

- Sitenotice.php
@Reception123 and I talked about removing this last night some time today, and it looks like he might've just forgotten, so doing for him
> Remove sitenotice re: Widgets extension

- LocalWiki.php
Reverts miraheze/mw-config#3607
> Revert "remove editwidgets from metawiki"

- LocalSettings.php
Reverts miraheze/mw-config#3620
Should be needed locally also.
> Revert "Stop installing globalblocking sql for each wiki"

- LocalSettings.php
Adds import sources for batfamilywiki, batmanwiki and snapwikiwiki. I am a bureaucrat on all these wikis.
> Add Import Sources for batfamilywiki, batmanwiki and snapwikiwiki

- LocalSettings.php
- Wikibase.php
Reverts miraheze/mw-config#3553
> Revert "Update configs to modern wikibase; re-format Wikibase.php"

- ManageWikiExtensions.php
Reverts miraheze/mw-config#3629
Update finished
> Revert "temporarily make translate extension managewiki-restricted for extension update"

- LocalSettings.php
Copied from `mrjaroslavikwiki`.
> Add transimport source for reviwikiwiki

- ManageWikiExtensions.php
Seems to be resolved from T4542.
> Remove note about mobile view with Tweeki

- Sitenotice.php
As per the previous sitenotice's length of time (approximately 24 hours) that @Reception123 and I discussed on Discord
> Removing system sitenotice

- ManageWikiNamespaces.php
See https://meta.miraheze.org/w/index.php?title=Community_noticeboard&oldid=156690#Problem_with_ArticleRatings_extension for extra details
> add wgARENamespaces to ManageWikiNamespaces

- ManageWikiExtensions.php
Reverts miraheze/mw-config#3673
> Revert "DynamicPageList3: run CreateTemplateUpdateMaintenance on install"

- .github/workflows/continuousIntegration.yml
MediaWiki isn't far off support. No harm to see if this works.
> Add lint check for php 8

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
Adds LogoFunctions per T6766. This should be merged with miraheze/mediawiki#1092.
> Add LogoFunctions (T6766)

- LocalWiki.php
Adds Naver site verification key for linkwikiwiki per T6764. The wiki is private so I had to copy the DB name from a custom domain request.
> Add Naver site verification key for linkwikiwiki (T6764)

- Sitenotice.php
> Add sitenotice regarding gluster migration

- Sitenotice.php
Removes redundant phrasing, improves grammar, and adds clarity and detail (i.e., "new, upgraded infrastructure") so customers see benefits.
> Correct grammar, improve phrasing, and add detail

- LocalWiki.php
/mnt/mediawiki-static uses the new file storage.
> Remove use of /mnt/mediawiki-static-new

- LocalSettings.php
Per reasonable request on the Administrators' noticeboard on Meta by Sabelöga.
> Use Special:MyLanguage for wgCookieWarningMoreUrl

- ManageWikiExtensions.php
Reverts miraheze/mw-config#3711
> Revert "Remove namespaces that add content models, with extensions"

- LocalSettings.php
- ManageWikiNamespaces.php
Reverts miraheze/mw-config#3759
> Revert "Add wgNamespaceRobotPolicies to ManageWikiNamespaces"

- LocalSettings.php
- ManageWikiNamespaces.php
Originally forgot to migrate the old wiki configs.
> Add wgNamespaceRobotPolicies to ManageWikiNamespaces

- LocalSettings.php
- ManageWikiSettings.php
Per https://github.com/wikimedia/mediawiki-extensions-DisqusTag/blob/1be6946e97d9f2bd6c494eda23340ce65e978dfe/extension.json#L39
> Fix config name

- ManageWikiExtensions.php
Going off of [extension.json](https://github.com/JeroenDeDauw/Maps/blob/master/extension.json#L32).
> Install GeoJson namespace for Maps

- LocalExtensions.php
- LocalSettings.php
Due to my own mistake, these should not have been added the way they were, undoing.
Per conversation with John on IRC.
> Add configs back to LocalExtensions.php

- GlobalCache.php
- LocalSettings.php
Also rename wmgRedisSettings to wmgCacheSettings.
> Switch to using MemcachedPeclBagOStuff

- LocalSettings.php
We get a lot of requests for wikis related to song contests these days. A category dedicated to those would be great.
> Add new "Song Contest" category for CreateWiki

- ManageWikiExtensions.php
Please see T6987 for details. I tested the two on my private wiki to confirm this.
> Comments conflicts with ProtectionIndicator (T6987)

- LocalSettings.php
Per request of @Universal-Omega for @RhinosF1
> Remove `$`

- LocalSettings.php
This has caused outages before.
> LS: fix HTTP timeouts

- LocalSettings.php
> Add "author request" as a decline reason

- LocalSettings.php
https://www.mediawiki.org/wiki/Manual:$wgImageMagickConvertCommand
> Fix ImageMagick variable name

- LocalSettings.php
We have quite a few wikis that would benefit from this category.
> Adding Business & Finance category

- LocalSettings.php
requester is sole editor on wiki
> CC BY-SA 3.0 for cvswiki per T7082

- ManageWikiSettings.php
Per miraheze/ManageWiki#263
Do not merge before that is merged and ManageWiki is updated.
> Remove whitelistSkipSkins from wgSkipSkins

- LocalSettings.php
This is my first pull request. Adds configuration for LinkTitles and some user right configuration per [T7094](https://phabricator.miraheze.org/T7094)
> Add simulatorwiki configs (T7094)

- LocalSettings.php
Reverts miraheze/mw-config#3818
> Revert "deploy future of flagged revs to test3wiki"

- ManageWikiExtensions.php
reported in T7104, upstream https://phabricator.wikimedia.org/T279617
> add conflict for myvariables and approvedrevs

- LocalSettings.php
I am a bureaucrat on all of those wikis and would like to import Wikibase items and properties from Wikidata.
> Add new import source for snapwikiwiki, batmanwiki and batfamilywiki

- ManageWikiExtensions.php
For [T7125](https://phabricator.miraheze.org/T7125#141452)
> Add extension categories (T7125)

- LocalSettings.php
Requested to me personally via Discord.
> Update wgGalleryOptions for a wiki

- LocalWiki.php
> Header modifications for pokemundowiki (T7146)

- LocalExtensions.php
- extension-list
Reverts miraheze/mw-config#3839
> Revert "Convert SimpleTooltip to use ExtensionRegistry"

- LocalExtensions.php
- extension-list
Per https://gerrit.wikimedia.org/r/c/mediawiki/extensions/LanguageSelector/+/681162
And https://gerrit.wikimedia.org/r/c/mediawiki/extensions/CategorySortHeaders/+/681370
> Convert LanguageSelector and CategorySortHeaders to ExtensionRegistry

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
This is the `mw-config` portion related to this Phabricator request, [T7180](https://phabricator.miraheze.org/T7180). @Reception123  to complete the Git portion, described [here](https://meta.miraheze.org/wiki/Tech:Adding_a_new_extension)
> Add PageAssessments extension #T7180

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
> Remove Validator

- LocalWiki.php
Reverts 71ea281a1b3fa66f15f79756cee1c74c8ba39190
> Re-enable ManageWiki API

- LocalSettings.php
This was for now-completed testing and should be removed.
> Remove wgMFSiteStylesRenderBlocking

- LocalSettings.php
> Remove John’s access to staffwiki

- LocalSettings.php
Hi! I'm new to this, so my apologies if I'm doing anything wrong. I made a simple edit to configure the "Highlight Links In Category" extension for my wiki.
> Configured "HighlightLinksInCategory" Extension for my wiki

- LocalSettings.php
`editarchiveprotected` and `editofficialprotected` per request (https://meta.miraheze.org/w/index.php?title=Community_noticeboard&oldid=174936#Protection)
> Add protection levels to naasgamelandwiki

- LocalSettings.php
[#7258](https://phabricator.miraheze.org/T7258)
> Add protection levels to memeswiki

- LocalSettings.php
I am a bureaucrat there and can confirm that we want to be able to import Wikibase items from Wikidata. Thank you.
> Add Wikidata as an import source for snapdatawiki

- GlobalLogging.php
> add db server recorder for logging (T7248)

- LocalSettings.php
Was removed in https://github.com/miraheze/ManageWiki/commit/f914eb5
> Remove wgManageWikiCDBDirectory

- LocalWiki.php
Adds viewport on all pages for snapwikiwiki.
> Header modification for snapwikiwiki

- LocalSettings.php
Addition of Meta Wikimedia for imports
> Add Wikimedia Meta to import sources

- LocalSettings.php
Reverts miraheze/mw-config#3902
> Revert "Switch GlobalWatchlist to loginwiki"

- LocalSettings.php
- ManageWikiSettings.php
- Wikibase.php
Per request at https://meta.miraheze.org/m/5tE
> Add Wikibase configs for documentcontrolwiki

- LocalSettings.php
> LS: enable wgCheckUserEnableSpecialInvestigate

- LocalSettings.php
As the title says. Also, this option has not been implemented into managewiki (mp4 has), so this is the only way for me to enable this setting. Maybe consider adding it to managewiki?
> Enable MP3 for my site using TimedMediaHandler

- LocalSettings.php
Allow Hypixel Fandom to be imported to Hypixel Wiki
> Allow Hypixel Fandom to be imported to Hypixel Wiki

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
> Add CountDownClock

- LocalSettings.php
per https://staff.miraheze.org/wiki/Special:ApiSandbox#action=query&format=json&list=globalallusers&agufrom=Samuel%20(Miraheze)&aguto=Samuel%20(Miraheze)
> Add my Staff account

- Sitenotice.php
per discussed day and time in -sre
> 1.36 sitenotice

- LocalSettings.php
> disable readonly

- Sitenotice.php
https://github.com/miraheze/mw-config/pull/3956/commits/95b8dd1345c2ba8b40f963555171a514f8a9f2c7
> Merge in and revise this PR's commit

- LocalSettings.php
- ManageWikiSettings.php
Reverts miraheze/mw-config#3926
Per the comments on the original task it is best to revert this for the time being until there is a discussion. Before doing this again please ask me.
> Revert "Set WebChat to default to Libera; remove freenodeChat"

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
> Add WikibaseLocalMedia (T7294)

- LocalSettings.php
> Disable CosmosRail on softcellwiki

- LocalSettings.php
Configures Vue.js-based search for ``snapwikiwiki``.
> Vector WVUI Search Configuration For snapwikiwiki

- LocalSettings.php
> Add WMF Commons as an Import Source for snapdatawiki

- LocalSettings.php
Configures ``wgSnapwikiskinWvuiSearchOptions``.
> Configure ``wgSnapwikiskinWvuiSearchOptions``

- LocalSettings.php
- ManageWikiSettings.php
remove freenode
See https://meta.miraheze.org/wiki/IRC/Replacement_of_default_chat_platform_in_WebChat_extension
> make Libera default for wgWebChatClient

- LocalSettings.php
I added in a configuration option for MultiBoilerplate that wasn't already there (maybe add it to managewiki?). Also, there seemed to be duplicate configurations as well as some formatting oddities, so I changed them to be a bit more uniform.
> Added a setting for MultiBoilerplate

- LocalSettings.php
Added namespaces for PageImages to display images in page previews for more namespaces in my wiki. The setting wasn't already there, so I tried to add it in. I may have done it incorrectly, though...
> Adding PageImages Namespaces to my Wiki

- LocalExtensions.php
- LocalSettings.php
- ManageWikiExtensions.php
- extension-list
> T7570: Install SkinPerPage

- LocalSettings.php
Reverts miraheze/mw-config#4008
> Revert "Set wgCreateWikiPersistentModelFile to false"

- LocalSettings.php
> set up egChameleonLayoutFile for lakehubwiki

- LocalWiki.php
Found another wiki with the same changes so I copied them and replaced the wiki name
> Custom DPL3 Settings for my wiki

- LocalSettings.php
> r4356thwiki -> redminwiki

- LocalSettings.php
We're quite borderline. Not merging yet as there's some leeway but leaving in case needed.
> [EMERGENCY] Up threshold even further

- LocalSettings.php
> Update WVUI search configuration for snapwikiwiki for Vector and Snap!

- LocalSettings.php
> Add wgReCaptchaSiteKey

- Sitenotice.php
Fixing typos in the Sitenotice
> Fixing typos in Sitenotice

- LocalWiki.php
Reverts miraheze/mw-config#4068
> Revert "T7698: Set apiThumbCacheExpiry for InstantCommons"

- LocalSettings.php
Limits to 1 account per 5 minutes, and 5 accounts per 24 hours.
> Correctly set `$wgAccountCreationThrottle`

- LocalWiki.php
Requested on Discord; added 2 wikis to polcomwiki's image repo
> Adding wikis to image repository

- LocalSettings.php
Disables JQMigrate on `snapwikiwiki`.
> Disable JQMigrate on snapwikiwiki

- extension-list
For `parserhooks-desc` in Special:Version
> Add ParserHooks to `extension-list`

- LocalWiki.php
Requested on Discord; adding additional wikis to polcomwiki shared repository.
> Adding wikis to shared repository

- Defines.php
Reverts miraheze/mw-config#4121
> Revert "set $wgDplSettings['functionalRichness'] = 0; temporarily"

- Defines.php
- LocalSettings.php
- ManageWikiExtensions.php
- ManageWikiSettings.php
* Should be deployed at the same time as miraheze/CreateWiki#245.
> do `$wgConf->extractAllGlobals()` inside MediaWikiServices hook

- Wikibase.php
Reverts miraheze/mw-config#4191
> Revert "Set otherProjectsLinks for famepediawiki and famedatawiki"

- LocalSettings.php
> Add memedatawiki to wgImportSources

- LocalSettings.php
Reverts miraheze/mw-config#4210
> Revert "Update poweredby"

- LocalSettings.php
Reverts miraheze/mw-config#4213
> Revert "T8270: set `$wgCargoPageDataColumns` for dmlwikiwiki"

- LocalSettings.php
Reverts miraheze/mw-config#4214
> Revert "Revert "T8270: set `$wgCargoPageDataColumns` for dmlwikiwiki""

- LocalSettings.php
- ManageWikiSettings.php
> Add wgCommentStreamsEnableSearch to ManageWikiSettings

- Wikibase.php
Please review as appropriately for merging :)
> Statement sections and repoSiteName for GD & GP

- LocalSettings.php
Please review codes and merge appropriately, ;)
> TE and XCON protection levels on GP

- LocalSettings.php
Please review and merge if willing, thank you.
> hypotheticalhurricaneswiki protection levels

- LocalSettings.php
to `bnwikiwiki` per https://phabricator.miraheze.org/T8316
> #T8316 - add Bengali Wikipedia as transwiki import source

- Database.php
Reverts miraheze/mw-config#4232
> Revert "Set `beta` cluster to c3 / db12, where `test3wiki` is located"

- Database.php
Reverts miraheze/mw-config#4233
> Revert "Revert "Set `beta` cluster to c3 / db12, where `test3wiki` is located""

- LocalSettings.php
Please review code and merge appropriately, thank you.
> Template Editor level per T8353

- LocalSettings.php
Reverts miraheze/mw-config#4235
> Revert "temporarily switch ReCaptcha back to v2 due to persistent errors (T8335)"

- Sitenotice.php
CN link to be added before push. Do not merge, waiting for @Agent-Isai to approve
> Liberty removal sitenotice for wikis with the skin enabled

- LocalSettings.php
> T8380: disable Cosmos recent changes rail for devilmanwiki

- LocalSettings.php
Reverts miraheze/mw-config#4245
> Revert "set all wikis to readonly (MW 1.37 upgrade)"

- LocalSettings.php
- ManageWikiSettings.php
This will need ran:
```sql
UPDATE mw_settings SET s_settings = REPLACE(s_settings,'wgRelatedArticlesFooterWhitelistedSkins', 'wgRelatedArticlesFooterAllowedSkins');
```
> Fix config naming for 1.37

- extension-list
Reverts miraheze/mw-config#4266
> Revert "Remove maps from extension-list"

- LocalSettings.php
Add 5 more import sources for zealandiawiki, all Fandom wikis.
> Add 5 more import sources for zealandiawiki

- LocalSettings.php
Per [T8032](https://phabricator.miraheze.org/T8032)
* miraheze/puppet#2142 should be deployed with this.
> Update to new paths for `$wgMathoidCli` and `$wg3dProcessor`

- LocalSettings.php
- Sitenotice.php
Reverts miraheze/mw-config#4280
> Revert "Disable 3D and Math temporarily"

- LocalSettings.php
> LS: setup betawiki

- Defines.php
- LocalWiki.php
1) remove JQuery, no one raised issues so this can go to prod
2) <s>Enable new media structure on all wikis but with cache so parser cache doesn't need killing</s>
3) Use new image metadata config on experimental
> Experimental: update for 1.37

- LocalSettings.php
* miraheze/CreateWiki#268 should add support for this.
> Configure betaheze realm for SiteConfiguration tag

- LocalSettings.php
* Not to be merged before #4293 and miraheze/CreateWiki#268
> Drop test3wiki from config + configure betaheze

- LocalSettings.php
Reverts miraheze/mw-config#4299
> Revert "betaheze: RO for CA migration"

- Defines.php
Reverts miraheze/mw-config#4302
> Revert "set ManageWikiNamespaces' variable defaults"

- LocalSettings.php
> On hold reason

- ManageWikiSettings.php
> Add `$wgFlaggedRevsOverride` to ManageWikiSettings

- LocalSettings.php
- ManageWikiSettings.php
> Add `$wgMaxTocLevel` to ManageWikiSettings

- LocalSettings.php
- ManageWikiSettings.php
> Add `$wgContribScoreIgnoreBots` to ManageWikiSettings

- LocalSettings.php
> Add 3 wiki configs for `$wmgDefaultUserOptions`

- LocalSettings.php
- ManageWikiSettings.php
> Add `$wgAmericanDates` to ManageWikiSettings

- LocalSettings.php
- ManageWikiSettings.php
> Add `$wgMaxAnimatedGifArea` to ManageWikiSettings

- LocalSettings.php
Per https://meta.miraheze.org/wiki/Community_noticeboard#Request_for_Feedback:_Adding_new_default_extensions
> Enable Purge and WikiSEO in ManageWiki by default

- LocalSettings.php
Per long ago deletion and dropped database
> Remove rhinosf1wiki

- LocalSettings.php
> Remove RobLa

- Defines.php
* Should not be needed with miraheze/ManageWiki#323 done now
> Remove default override for $wgExemptFromUserRobotsControl

- Defines.php
- LocalSettings.php
Hopefully prevent some pages failing to load
> Shell: cap memoryLimit

- Defines.php
- LocalSettings.php
Reverts miraheze/mw-config#4349
> Revert "Shell: cap memoryLimit"

- ManageWikiExtensions.php
> Add StandardDialogs to ManageWikiExtensions

- ManageWikiExtensions.php
> Add Patroller to ManageWikiExtensions

- ManageWikiExtensions.php
Reverts miraheze/mw-config#4360
> Revert "Add Patroller to ManageWikiExtensions"

- Defines.php
Extensions and skins are updated weekly, so they dont need to have this ran.
> Only run LocalisationUpdate for MediaWiki core

- GlobalCache.php
* use memcached for parser cache by default,
* CACHE_ACCEL for betaheze,
* and lower expiry to 5 days.
> Use memcached for ParserCache

- Wikibase.php
I think it can be a default, anyway.
> Set WBRepo statement sections for horimiyawiki

- Defines.php
for use of control group to limit memory usage
> Set $wgShellCgroup

- .github/workflows/continuousIntegration.yml
Test runs:
- ✔️ Passed for this PR (https://github.com/lens0021/mw-config/actions/runs/1722018323)
- After breaking the order ([commit](https://github.com/lens0021/mw-config/commit/9b1b2ac15f9b81b419e5b30cb3ba9398b01a53c4)) → ❌ Failed as expected (https://github.com/lens0021/mw-config/actions/runs/1722021109)
I was not sure it should be added as a new job or a new step. Feel free to request me a change if the current state is not suitable.
> test: Check if extension-list is ordered alphabetically

- GlobalCache.php
Reverts miraheze/mw-config#4419
> Revert "depool mem101"

- GlobalCache.php
Reverts miraheze/mw-config#4421
> Revert "depool mem121"

- ManageWikiExtensions.php
- extension-list
Requested from [T8637](https://phabricator.miraheze.org/T8637)
> Add PropertySuggester to ManageWikiExtensions

- Wikibase.php
Request: https://phabricator.miraheze.org/T8637
Thank you!
> Set PropertySuggesterInitialSuggestions for horimiyawiki

- LocalSettings.php
- ManageWikiSettings.php
> Add wgWikiSeoDefaultImage

- extension-list
Reverts miraheze/mw-config#4435
> Revert "ext-list: register ES extensions"

- LocalSettings.php
> Setup CreateWiki on betaheze

- ManageWikiNamespaces.php
'blacklisted' and 'whitelisted' will be renamed.
> ManageWikiNamespaces: set 'excluded' and 'only'

- LocalSettings.php
Please review and merge appropriately.
> T8712: Extented confirmed protection NPWiki

- Defines.php
- GlobalExtensions.php
> GlobalBlocking: disable on non-global wikis

- LocalSettings.php
@Reception123 please review the code and merge; if this is the right place to even request it in the first place, I might just be a dumbass :)
> T8818: Update Settings with ArticlePlaceholder params for gratispaideiawiki

- LocalSettings.php
please review and merge appropriately if everything is rightly placed.
> T8867:Update with missing WikiSEO params for GP&GD

- Wikibase.php
All configs for per wiki should better go into one section, instead of having duplicated or replicated sections.
Please review and merge if you think the same too :)
> WikiBase: combine single wiki config

- LocalSettings.php
Reverts miraheze/mw-config#4503
> Revert "PropertySuggester/APH configs for GD/GP"

- LocalSettings.php
I wonder why it scattered anyway
> Fixing arrangement of this config

- LocalSettings.php
Required for transwiki imports on Loginwiki
> Add testwikiwiki to loginwiki's import sources

- initialise/MirahezeFunctions.php
* miraheze/CreateWiki#297 should add support for this.
> Utilise hook for beta database list support

- Defines.php
Reverts miraheze/mw-config#4531
> Revert "Try changing parsoid url to localhost"

- LocalSettings.php
Reverts miraheze/mw-config#4542
> Revert "temporarily disable babel until T9011 is figured out"

- LocalSettings.php
Reverts miraheze/mw-config#4559
> Revert "Set all wikis into read only"

- Sitenotice.php
Reverts miraheze/mw-config#4553
> Revert "Add site notice for emergency database maintenance"

- ManageWikiNamespaces.php
Per suggestion at https://github.com/miraheze/mw-config/pull/4547#discussion_r843392254 which makes more sense
> T9025: Add wgCosmosRailBlacklistedNamespaces to ManageWiki/namespaces

- tests/ManageWiki/ExtensionsTest.php
- tests/ManageWiki/ManageWikiTestCase.php
- tests/ManageWiki/SettingsTest.php
Validates `$wgManageWikiExtensions` defined in ManageWikiExtensions.php
> Add ExtensionsTest.php

- ManageWikiSettings.php
- tests/ManageWiki/ExtensionsTest.php
- tests/ManageWiki/ManageWikiTestCase.php
- tests/ManageWiki/SettingsTest.php
> Add missing schema and copy the descriptions

- extension-list
Reverts miraheze/mw-config#4590
> Revert "Add CreatedPagesList to extension-list"

- LocalSettings.php
- LocalWiki.php
- SemanticMediaWiki.php
Per [T7000](https://phabricator.miraheze.org/T7000)
> Enable SemanticMediaWiki on smwwikibeta

- LocalSettings.php
- ManageWikiSettings.php
This depends on https://github.com/miraheze/mediawiki/pull/6303
Thank you.
> Add `$wgPortableInfoboxResponsiblyOpenCollapsed` to ManageWikiSettings.php

- LocalSettings.php
- SemanticMediaWiki.php
This reverts commit eafe6999195702211744293b816b7c0d536d9beb.
> Revert "Manually load SMW (#4603)"

- ManageWikiExtensions.php
Per discussion with @Universal-Omega on IRC
> Tweak wording of SMW help page

- Wikibase.php
gpcommons:
Set repoSiteName and pageSchemaNamespaces
gratispaideia:
removed Project and Category namespaces from pageSchemaNamespaces
gratisdata:
Set localClientDatabases
benpedia:
add it to the localClientDatabases for gratisdatawiki
> Add Wikibase configuration for gratisdatawiki, gratispaideiawiki, gpcommonswiki, benpediawiki

- LocalWiki.php
Discussed with @Reception123 who approved the removal of the unnecessary meta tags and of the unneeded hardcoded Donation link on Meta.
> Remove metawiki configurations

- LocalSettings.php
* crocwiki
* dragonquest2wiki
* metroidwiki
* nintendowiki
* pokemon2wiki
* smashbroswiki
* squareenixwiki
> T9137: set wgDefaultUserOptions['thumbsize'] to "3" on the following wikis

- Wikibase.php
Reverts miraheze/mw-config#4643
> Revert "set localEntitySourceName for gratisdatawiki and gpcommonswiki"

- Wikibase.php
Reverts miraheze/mw-config#4641
> Revert "setting up entitysource for gratispaideiawiki, gpcommonswiki, gratisd…"

- LocalSettings.php
Reverts miraheze/mw-config#4595
> Revert "revert unauthorized changes made without consensus" per passed proposal

- Wikibase.php
This config currently throws exceptions on some pages eg, special pages, and some other
> remove disabledDataTypes from gratispaideia and co

- LocalSettings.php
Reverts miraheze/mw-config#4667
> Revert "Re-enable Maps on 1.38"

- LocalWiki.php
> Set meta tags on entity pages gratisdatawiki

- LocalWiki.php
Reverts miraheze/mw-config#4689
User reported it didn't work for what they wanted.
> Revert "Set meta tags on entity pages gratisdatawiki"

- LocalSettings.php
Reverts miraheze/mw-config#4693
> Revert "PageImages: make MediaWiki:Pageimages-denylist work everywhere"

- LocalSettings.php
Reverts miraheze/mw-config#4695
> Revert "Revert "PageImages: make MediaWiki:Pageimages-denylist work everywhere""

- GlobalExtensions.php
- GlobalSettings.php
- extension-list
Per [T9249](https://phabricator.miraheze.org/T9249)
> Remove LocalisationUpdate

- LocalSettings.php
- ManageWikiExtensions.php
Per [T9246](https://phabricator.miraheze.org/T9246)
> Add ExternalData to ManageWikiExtensions

- LocalSettings.php
Reverts miraheze/mw-config#4714
> Revert "add gratispaideia.miraheze.org as wgCrossSiteAJAXdomains for gratisdatawiki"

- LocalSettings.php
Reverts miraheze/mw-config#4713
> Revert "add gratisdata.miraheze.org as wgCrossSiteAJAXdomains on gratispaideiawiki"

- LocalSettings.php
- initialise/MirahezeFunctions.php
For rebuildVersionCache.php to succeed.
> Allow ManageWikiExtensions.php to properly load in staging

- Sitenotice.php
Per discussion with Agent and Reception123
> Add extensions removal site notice

- ManageWikiExtensions.php
- extension-list
Replaced with TabberNeue, which has the exact same behavior.
> Remove Tabber (T8899)

- LocalSettings.php
Reverts miraheze/mw-config#4737
> Revert "Set wgPasswordHash to []"

- LocalSettings.php
Logs non sensitive information for ldap extension.
> Set wgLDAPDebug to 1

- Sitenotice.php
This changes the sitenotices style to match the CN/general Meta style
> Change design of sitenotices

- LocalSettings.php
Reverts miraheze/mw-config#4750
> Revert "See if Maps works on 1.38, with egMapsAvailableServices as the default"

- LocalSettings.php
This is for testing of the annual survey
> Enable MirahezeSurvey on betawiki only

- Wikibase.php
since this can be enabled via $wmgAllowEntityImport on ManageWiki
> remove separate allowEntityImport from gratisdatawiki

- LocalSettings.php
Reverts miraheze/mw-config#4754
> Revert "Set all wikis read-only for MediaWiki 1.38 upgrade"

- GlobalSettings.php
- LocalSettings.php
Reverts miraheze/mw-config#4764
> Revert "Fix licensing"

- LocalSettings.php
defaults confirmed from skin.json
> T9328: set base of wgMinervaShowCategories to true for criticalrolewiki

- Wikibase.php
Reverts miraheze/mw-config#4678
> Revert "setup entitySources for gratisdatawiki and co"

- LocalSettings.php
- ManageWikiSettings.php
wgKartographerStaticMapframe and wgKartographerEnableMapFrame
> add Kartographer config to ManageWiki

- LocalSettings.php
Per [T8982](https://phabricator.miraheze.org/T8982).
> Start actor table schema migration on beta

- initialise/MirahezeFunctions.php
Prevent unnecessary json decoding every time.
> Return current set servers if already set in SIteConfiguration

- GlobalExtensions.php
To be done once MobileDetect is updated.
Per https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MobileDetect/+/815735.
> Use ExtensionRegistry for MobileDetect

- LocalSettings.php
To-be done once UserFunctions is updated.
Per https://gerrit.wikimedia.org/r/c/mediawiki/extensions/UserFunctions/+/683402.
> Rename and document `$wgUFEnablePersonalDataFunctions`

- GlobalCache.php
Also replicates to the db to support fallback.
> cache: support using memcache for parsoid cache

- Database.php
- LocalSettings.php
Reverts miraheze/mw-config#4844
> Revert "Add db131/db141"

- LocalWiki.php
Creates the 'requestaccount' ContactPage form on Meta
> Add ContactPage configuration for Meta

- LocalSettings.php
At least for now, until it can be fixed.
> T9442: disable HitCounters

- Sitenotice.php
I presume this is how it should look originally?
> fix sitenotice

- Database.php
Reverts miraheze/mw-config#4882
> Revert "MAINT: Put all wikis into read-only"

- LocalSettings.php
Reverts miraheze/mw-config#4716
> Revert "Revert "add gratisdata.miraheze.org as wgCrossSiteAJAXdomains on gratispaideiawiki""

- LocalSettings.php
- wgMinervaApplyKnownTemplateHacks removes bad template styles
- wgMinervaShowCategories shows categories to everyone
> Change Minerva variables for isvwiki

- ManageWikiExtensions.php
Requires https://github.com/miraheze/mediawiki/pull/9336
> Support PageProperties 1.1.0

- LocalSettings.php
> Bump wgAuthenticationTokenVersion

- FileBackend.php
- LocalSettings.php
Reverts miraheze/mw-config#4932
> Revert "Support container per directory per wiki"

- FileBackend.php
Sets abbrvThreshold and directly set hashLevels, no need to check config
> Update $wgLocalFileRepo for Swift

- LocalSettings.php
- ManageWikiSettings.php
Reverts miraheze/mw-config#4942
> Revert "Use static.miraheze.org for default $wgLogo"

- GlobalSettings.php
Follows up #4959 which I set the values wrongly.
> Fix $wgMaxShellFileSize and $wgMaxShellMemory

- LocalSettings.php
See discussion here: https://meta.miraheze.org/wiki/Community_noticeboard/Archive_31#Babel_-_change_of_configuration_(proposal)
> T9850: Setup babel cats globally

- FileBackend.php
- LocalSettings.php
Reverts miraheze/mw-config#4981
> Revert "Only set `$wgThumbPath` if not using Swift"

- Database.php
- LocalSettings.php
Reverts miraheze/mw-config#4988
> Revert "Pool db141 back in as c6"

- Database.php
- LocalSettings.php
Reverts miraheze/mw-config#4993
> Revert "Revert "Pool db141 back in as c6""

- LocalSettings.php
> Add line break

- GlobalSettings.php
* Not to be merged before miraheze/DataDump#53 is merged and the extension is updated.
> Re-enable DataDump XML dumps

- GlobalCache.php
Reverts miraheze/mw-config#5024
> Revert "Temporarily use mem141 for all caching"

- LocalSettings.php
* Unused now with miraheze/MirahezeMagic#381.
> Remove `$wgMirahezeMagicLogEmailConditions`

- LocalSettings.php
Change requested in Phabricator: https://phabricator.miraheze.org/T10184.
> T10184: Disable enhanced filters in watchlists by default for luigismansionwiki

- GlobalSettings.php
This is a little experiment to see how things go.
> Increase resources for wgMaxShellFileSize and wgMaxShellMemory

- LocalSettings.php
Requested on Phabricator: https://phabricator.miraheze.org/T10257
> T10257: set wgUrlProtocols for 100acgwiki

- LocalSettings.php
Requested at Phabricator: https://phabricator.miraheze.org/T10256
> T10256: Add wgCategoryTreeMaxDepth and set a custom value for acg100wiki

- ManageWikiExtensions.php
> Restrict SlackNotifications and PdfBook

- GlobalSettings.php
> Unset no-ipinfo

- LocalSettings.php
- ManageWikiSettings.php
Adds wgWikiEditorRealtimePreview to ManageWiki/settings
> Add wgWikiEditorRealtimePreview

- GlobalSettings.php
Reverts miraheze/mw-config#5092
Per UO's comment
> Revert "Unset no-ipinfo"

- LocalSettings.php
Reverts miraheze/mw-config#5095
> Revert "Temporarily disable approving wikis"

- LocalWiki.php
See https://phabricator.miraheze.org/T10329#208701.
> T10329: Change comprehensiblewiki to comprehensibleinputwiki

- LocalSettings.php
Requested on Phabricator: https://phabricator.miraheze.org/T10352
> T10352: add wgEmbedVideoFetchExternalThumbnails

- ManageWikiSettings.php
Per T10352. This does not set the default in LocalSettings.php as https://github.com/miraheze/mw-config/pull/5090 will.
> T10352: Add wgEmbedVideoFetchExternalThumbnails to ManageWiki

- Sitenotice.php
cc @Agent-Isai but I think 5 days is probably enough, otherwise users will likely find their way to report bugs anyway
> remove post upgrade sitenotice

- LocalSettings.php
Requested at Phabricator, see https://phabricator.miraheze.org/T10430 and https://phabricator.miraheze.org/T10430#210082.
> T10430: Add wgKartographerSimpleStyleMarkers and set a custom value for leborkwiki

- GlobalExtensions.php
> Enable StopForumSpam globally

- GlobalCache.php
Reverts miraheze/mw-config#5118
> Revert "Set `$wgMainCacheType` to mem141"

- ManageWikiExtensions.php
Fixes the path to the sql file.
> Fix creating Flow sql tables

- LocalSettings.php
* Can be merged when Universal-Omega/DiscordNotifications#66 and Universal-Omega/DiscordNotifications#67 are deployed on Miraheze.
> Configure `$wgDiscordExcludeConditions`

- Database.php
Reverts miraheze/mw-config#5132
> Revert "Set db101 into read-only"

- LocalWiki.php
Adds a link to Draft:Portal for paneidoversewiki
> T10323: Add a link to Draft:Portal

- GlobalCache.php
- SemanticMediaWiki.php
Reverts miraheze/mw-config#5148
> Revert "Switch main cache to mem141"

- GlobalCache.php
Reverts miraheze/mw-config#5153
> Revert "Move main cache and message cache to memcached-mem-1"

- GlobalCache.php
Reverts miraheze/mw-config#5158
> Revert "Set session cache to CACHE_DB"

- GlobalCache.php
Reverts miraheze/mw-config#5157
> Revert "Revert "Move main cache and message cache to memcached-mem-1""

- extension-list
> T9853: Add Skin:Splash to extension-list

- LocalSettings.php
Requested on Phabricator: https://phabricator.miraheze.org/T10640.
> T10640: Set some wgDefaultUserOptions values on landarwiki

- LocalWiki.php
Requested on Phabricator: https://phabricator.miraheze.org/T10440.
> T10440: Add Pivot settings for wanderingstarswiki

- ManageWikiSettings.php
Reverts miraheze/mw-config#5110
Didn't work per T10440
> Revert "T10440: Add some Pivot settings to ManageWiki"

- ManageWikiExtensions.php
- extension-list
Part of https://github.com/miraheze/mediawiki/pull/13956
> Add NearbyPages to ManageWikiExtensions

- LocalWiki.php
See https://phabricator.miraheze.org/T10660#215368.
This reverts commit 0cff04447d9ce48bfebcb1afc5b30abe277bef33.
> Revert "T10657: Configure $wgPageImagesScores for buttonmenwiki (#5170)"

- Sitenotice.php
Sitenotice explain alert that Cargo is disabled
> Sitenotice for Cargo being disabled

- Sitenotice.php
> Disable sitenotice for session reset

- GlobalSettings.php
setContainerAccess.php finished so we can probably safely re-enable this on most wikis
> Re-enable file uploads

- GlobalSettings.php
> Set wgThumbnailEpoch

- LocalWiki.php
> Add requestbetaaccount ContactPage form on Meta

- initialise/MirahezeFunctions.php
- initialise/entrypoints/api.php
- initialise/entrypoints/img_auth.php
- initialise/entrypoints/index.php
- initialise/entrypoints/load.php
- initialise/entrypoints/opensearch_desc.php
- initialise/entrypoints/rest.php
- initialise/entrypoints/thumb.php
- initialise/entrypoints/thumb_handler.php
This doesn't do anything by itself.
> Initial multiversion support

- initialise/MirahezeFunctions.php
Uncomments per-version DB lists, version property, and SiteConfiguration version tags.
> Enable some multiversion functionality

- LocalWiki.php
> Userrights config for nycsubwaywiki

- GlobalSettings.php
Reverts miraheze/mw-config#5238
> Revert "T10794: Add OOJSPlus"

- LocalSettings.php
Please only approve and merge once a formal statement of intent to resign has been submitted in the appropriate venues.
> rm Agent Isai and Universal Omega from MirahezeStaffAccessIDs per resignations

- LocalSettings.php
Bug: [T11025](https://phabricator.miraheze.org/T11025)
> LocalSettings: Add wgNearbyPagesUrl default

- LocalSettings.php
The fix is from https://github.com/WikiForge/mw-config/commit/ef1b692cfff22bee61d5829f2d86b63ad48b8134
> Fix loading SocialProfile under MW 1.40

- GlobalExtensions.php
- GlobalSettings.php
Originally done in #5243.
Also up wgFlowParsoidTimeout to 50.
> Re-apply "Enable the Parsoid extension on all wikis"

- initialise/MirahezeFunctions.php
Only get this on beta cluster (or maybe mw 1.40?)
Proposed by "Original Authority".
> Fix "Notice: Undefined index: globals" in onMediaWikiServices

- GlobalExtensions.php
Causing performance degradation.
> Temporarily disable StopForumSpam

- GlobalCache.php
Reverts miraheze/mw-config#5311
> Revert "Use redis for sessions"

- LocalSettings.php
> Disable MixedNamespaceSearchSuggestions on mw 1.40+

- LocalSettings.php
I believe this is how you do it. Tasks are https://phabricator.miraheze.org/T11084, https://phabricator.miraheze.org/T11101, https://phabricator.miraheze.org/T11102.
> Multiple tasks: Configure LinkTargetParentClass for some wikis

- GlobalSettings.php
Only allows those with a global account to login.
> Set wgCentralAuthStrict to true

- LocalSettings.php
Allows use of Mobile.css and Mobile.js.
> Set wgMFCustomSiteModules to true

- LocalSettings.php
We don't use a translation service at the moment.
> Set wgTranslateTranslationDefaultService to false

- GlobalCache.php
This reverts commit 007f98428d83350c0eb60b6b36156af72a288615.
> Revert "Unset wgUseLocalMessageCache (#5296)"

- LocalSettings.php
> Set wgCdnMaxAge to 5 days

- GlobalCache.php
> memcache: use sockets for nutcracker

- GlobalCache.php
Reverts miraheze/mw-config#5382
> Revert "Set mcpMessageCachePerformanceMsgPrefixes"

- SemanticMediaWiki.php
> Fix $smwgMainCacheType for new nutcracker config

- GlobalCache.php
> Remove $wgWANObjectCache

- initialise/MirahezeFunctions.php
Reverts miraheze/mw-config#5405
> Revert "Set $wgExtensionInfoMTime to use confActualMtime in MirahezeFunctions"

- LocalWiki.php
As previously mentioned in [T11314](https://phabricator.miraheze.org/T11314), I need to add these configurations for my wiki to setup system translation.
> Setup dlfmwiki for system messages' translation.

- LocalSettings.php
Allow meta sysadmins to add/remove sysadmins
> Allow meta sysadmins to add/remove sysadmins

- ManageWikiSettings.php
Requested on https://phabricator.miraheze.org/T11069. I think the seo category is the most adecuate for this one.
> T11069: Add $wgPageImagesLeadSectionOnly to ManageWikiSettings

- LocalSettings.php
Requested on https://phabricator.miraheze.org/T11506.
> T11506: Setup extendedconfirmed protection for mypediawiki

- LocalSettings.php
See https://phabricator.miraheze.org/T11711
> T11711: Update default value for wgExtractsRemoveClasses

- ManageWikiExtensions.php
The skins repo has been removed.
> Remove flatbox

- LocalSettings.php
- ManageWikiExtensions.php
> Remove MixedNamespaceSearchSuggestions

- ManageWikiExtensions.php
> Remove AddHTMLMetaAndTitle

- LocalSettings.php
> Re-enable AuthorProtect

- LocalSettings.php
> Re-enable RatePage

- LocalSettings.php
Fix regex (use spaces instead of underscores in namespace)
I goofed when making the regex, but hopefully should be fine with this
> $wgWhitelistReadRegexp for kanrikyarawiki (T11856)

- GlobalExtensions.php
- LocalWiki.php
* Required for miraheze/ImportDump#66
> Enable ImportDump globally

- LocalSettings.php
> Configure ImportDump automation

- robots.txt
1. Add pattern matching for crawlers that support it to block the indexing of special pages
2. Remove duplicate comments
3. Fix grammatical error
4. Move Crawl-Delay to the bottom to prevent breaking bots that don't support it. See https://github.com/otwcode/otwarchive/pull/4411#discussion_r1044351129
> Fix multiple issues in robots.txt

- LocalSettings.php
This might fix [T11940](https://issue-tracker.miraheze.org/T11940)
> Force IPv6 for smtp connection

- LocalSettings.php
This is a feature introduced in MW 1.41
https://www.mediawiki.org/wiki/Manual:$wgPrivilegedGroups
> Setup wgPrivilegedGroups

- LocalSettings.php
- ManageWikiSettings.php
Allow the uses of Statements parser.
> Adding function for UnlinkedWikibase

- GlobalSettings.php
Reverts miraheze/mw-config#5515
> Revert "T11999: Disable RequestWikiQueue outside of the meta wikis"

- GlobalSettings.php
Reverts miraheze/mw-config#5518
> Revert "T11999: Disable Special:RequestWikiQueue outside of metawiki"

- EventBus.php
See https://issue-tracker.miraheze.org/T12022#240905
> add setContainersAccessJob to the Redis JobQueue

- LocalSettings.php
https://issue-tracker.miraheze.org/T11982
> T11982: Create edittrusteduserprotected protection level in phightingwiki

- LocalWiki.php
It turns core namespaces names lowercase. I tested this on a test wiki and it seems to work.
> Add configs for spacewiki

- LocalWiki.php
Didn't realize that two entries existed for genshinimpactwiki
> Merge duplicate entries together

- robots.txt
See the reasoning provided in the commit
> Changes to how special pages are treated

- LocalSettings.php
Reverts miraheze/mw-config#5574
> Revert "mark c1 as down"

- LocalSettings.php
https://issue-tracker.miraheze.org/T11421
Just a temporary solution, this config will be migrated to ManageWiki in the future
> T11421: Prevent categories from showing up on Special:ShortPages for tuscriaturaswiki

- LocalSettings.php
Adding new footer icons (StarCitizenTools style)
> Adding new footer icons (StarCitizenTools style) to lhmnwiki and sister projects

- LocalSettings.php
was scruffywiki is now scruffwiki
and
was simpleelectronicswiki is now simpleelectronicswikiwiki
> Change a couple of wiki names

- ManageWikiExtensions.php
https://issue-tracker.miraheze.org/T12225
> T12225: Remove listings

- LocalSettings.php
so that this will fit the mobile Citizen skin
> Update footer icon settings for lhmnwiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T12140
> Modify password policies to account for SRE group rename

- LocalSettings.php
https://issue-tracker.miraheze.org/T12042#245374
> Change schema location of UrlShortener in 1.42

- initialise/entrypoints/index.php
> T12263: Fix editing main pages of wikis that use /$1 and root as main page

- initialise/MirahezeFunctions.php
https://issue-tracker.miraheze.org/T12041
> Mark 1.42 as the stable version in MirahezeFunctions

- LocalSettings.php
> Disable RightFunctions

- LocalSettings.php
https://issue-tracker.miraheze.org/T12344
> T12344: Disable RatePage

- LocalSettings.php
- LocalWiki.php
> T12484: Re-enable RightFunctions

- ManageWikiExtensions.php
https://phabricator.wikimedia.org/T371081
> Add incompatibility warning for HeaderTabs

- ManageWikiExtensions.php
https://meta.miraheze.org/wiki/Tech:Noticeboard?oldid=414759#The_state_of_the_ReplaceText_extension
> Add a warning for Wiki Mechanics and Stewards about ReplaceText

- LocalWiki.php
Hello. This is my first PR in this project, so if I had any mistake please let me know them gently :-)
- Add some licenses we needed (2 Rights Statements options).
- Add Japanese in language setting.
Our wiki is https://kagaga.jp/.
> Add UploadWizard configurations for kagagawiki in LocalWiki.php

- initialise/entrypoints/index.php
> T12214: Avoid redirects if action=raw is set

- LocalSettings.php
https://issue-tracker.miraheze.org/T12553
> T12553: Add edittemplateprotected to cricketnepalwiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T12556
> T12556: Set some image thumbnail settings for dominionstrategywiki

- LocalSettings.php
- ManageWikiSettings.php
https://issue-tracker.miraheze.org/T12565
> T12565: Add $wgEnableTranscode and .srt to ManageWiki

- ManageWikiNamespaces.php
https://issue-tracker.miraheze.org/T12628
> T12628: Add $wgCodeMirrorLineNumberingNamespaces

- ManageWikiExtensions.php
> T12653: Fix installing ExternalData

- GlobalCache.php
- LocalSettings.php
We are investigating an issue so lets move prod back to the old runner for now.
> Use old jobrunner for prod

- GlobalSettings.php
Avatar images do not show as expected on my site, 
The folder does not generate in the default image folder, as proven by the 404 Not Found errors
> Fix image storage backend for UserProfileV2

- LocalWiki.php
https://issue-tracker.miraheze.org/T12565
> T12565: Stinkily disable transcodes for hommwiki

- initialise/MirahezeFunctions.php
> Create public/private wiki list

- GlobalSettings.php
- LocalSettings.php
Increase threads for FFmpeg to 4 and tune other configs
> Set some TimedMediaHandler configs

- GlobalSettings.php
Rather than using robots.txt, the proper approach is to add noindex tags.
> Don't index special pages

- LocalWiki.php
> T12683: Add per-namespace logo links for tuscriaturaswiki

- GlobalLogging.php
See https://github.com/wikimedia/operations-mediawiki-config/commit/516faa3a395cd21de4cc86b3cd29e7d18c133b67
> Remove blackhole from logging config

- GlobalLogging.php
- LocalSettings.php
- LocalWiki.php
See https://github.com/wikimedia/operations-mediawiki-config/commit/36264f4edeaa4f0c015d671ac7577ba116f52ba0.
> Logging: Set default logging to error

- GlobalSettings.php
Reverts miraheze/mw-config#5736
> Revert "Temp disable creating accounts"

- GlobalCache.php
Also set wgDiscussionToolsTalkPageParserCacheExpiry to 10 days.
> Increase wgParserCacheExpireTime to 15 days

- LocalSettings.php
> Set wgPageLinksSchemaMigrationStage to SCHEMA_COMPAT_NEW

- GlobalSettings.php
- LocalSettings.php
Also set wgLoginNotifyUseCentralId if using CentralAuth
> Set wgVirtualDomainsMapping for LoginNotify

- LocalSettings.php
> Remove unused wgUseSameSiteLegacyCookies config

- Database.php
Reverts miraheze/mw-config#5764
> Revert "Update Database.php"

- LocalSettings.php
> T12992: Set custom footer images for aceistanwiki

- LocalSettings.php
> T12980: Set custom footer images for utgwiki

- ManageWikiExtensions.php
Was changed in https://github.com/edwardspec/mediawiki-moderation/commit/7df148fd2a6ec09aac76302b92be7003492b2539#diff-f5a6e1d9c81c45b12a84108c571134bdbe2eec14e75f4341ba9f8cf8567695e1
> Update Moderation sql file location

- LocalSettings.php
> T13072: Fix issues regarding copyright button on utgwiki and cafewiki

- LocalSettings.php
> T13051: Set custom footer icons for yonicversewiki

- LocalSettings.php
> T13008: Set different button images for aceistanwiki

- LocalSettings.php
- ManageWikiSettings.php
> T13058: Add $wgExportAllowListContributors to ManageWiki

- LocalSettings.php
> T13037: Set $wgParserEnableUserLanguage to true for utgwiki

- LocalWiki.php
> T13108: Set $wgMinervaNightMode for roguetown2ewiki

- LocalSettings.php
Replaced default footer icons with custom ones.
> Updated footer icons for jbcstudios

- GlobalSettings.php
Only takes effect if wgLogo is unset or set to false.
> Set wgTimelessLogo to wgLogo

- GlobalSettings.php
Reverts miraheze/mw-config#5799
> Revert "Make $wgLogos['icon'] fallback to wgLogo if wgIcon not set"

- LocalSettings.php
> T13130: Set some default options for ssbuniversewiki

- LocalWiki.php
> T13129: Set $wgVectorNightMode for roguetown2ewiki

- LocalWiki.php
> T13147: Set $wgLogRestrictions for fischwiki

- LocalSettings.php
As per request https://issue-tracker.miraheze.org/T13218
> T13218: Change footer icons for Outlaster Wiki (outlasterwiki)

- LocalSettings.php
Adding RobloxURI to wgUrlProtocols as per T13215
> Adding RobloxURI to cafewiki allowed protocols - T13215

- LocalSettings.php
- LocalWiki.php
> T13222: Set Vector dark mode settings for combatinitiationwiki

- LocalSettings.php
> T13233: Add custom footer icons for fraudulentfronterawiki

- LocalSettings.php
> Remove wgPageLinksSchemaMigrationStage

- LocalWiki.php
Updated configs for:
- ~~`$wgEnableProtectionIndicators` to `true` (cannot be set from ManageWiki for some weird a** reason)~~ Fixed
- Changed URL in the UW license set for `snxyz` to `//songngu.xyz/giayphep`
> Update lhmnwiki's configs

- LocalWiki.php
> T13250: Use Wikimedia Commons for JsonConfig on openfrontwiki

- ManageWikiExtensions.php
> T13298: Fix enabling ArticleFeedbackv5

- LocalWiki.php
> T13303: Force all Echo events to be a notice for softcellwiki

- LocalWiki.php
> T13307: Make all Echo events alerts on several wikis

- GlobalSettings.php
- ManageWikiExtensions.php
Needed for miraheze/MirahezeMagic#554
> Update MirahezeMagic maintenance scripts format

- extension-list
Maps extension has dropped it.
> Remove Validator from extension-list

- LocalSettings.php
> T13322: Add custom footer icons for ballgamewiki

- LocalWiki.php
> T13275: Add Data.JsonConfig to ftlmultiversewiki

- LocalSettings.php
Adding custom mh and mw icons for fisch
> Custom mh and mw icons for fisch

- LocalSettings.php
- ManageWikiExtensions.php
Adding Extension:EditSimilar from [T13286](https://issue-tracker.miraheze.org/T13286).
> install EditSimilar from T13286

- LocalWiki.php
> T13332: Set default night mode settings for dungeonrngwiki

- GlobalSettings.php
- LocalSettings.php
Presumably okay according to https://issue-tracker.miraheze.org/T13269#267487
Fixes T13269
> T13269: Enable ParserMigration on production

- ManageWikiExtensions.php
Installing Extension:RandomImageByCategory per [T12827](https://issue-tracker.miraheze.org/T12827).
> Install Extension:RandomImageByCategory

- LocalSettings.php
> re-enable DataTransfer

- ManageWikiExtensions.php
Adding [Extension:RefreshSpecial](https://www.mediawiki.org/wiki/Extension:RefreshSpecial) per [T12835](https://issue-tracker.miraheze.org/T12835).
> install RefreshSpecial per T12835

- ManageWikiExtensions.php
> Uninstall RefreshSpecial

- GlobalSettings.php
https://github.com/wikimedia/operations-mediawiki-config/commit/c6b7c290835585674aa7558276c8f9730317b1d4
> Increase wgFFmpegThreads to 8

- LocalSettings.php
Reverts miraheze/mw-config#5894
> Revert "Updating Cloudflare's IPs."

- LocalSettings.php
- LocalWiki.php
Removing a bunch of now closed wikis from LocalWiki.php and LocalSettings.php. Verified that each wiki is closed via looking up their dbnames through ManageWiki on the Miraheze Meta Wiki.
> Removing closed wikis from local wiki PHP files

- LocalWiki.php
Adding custom footer links for the STOPXWiki per [T13440](https://issue-tracker.miraheze.org/T13440).
> Adding footer links for the STOPXWiki

- LocalWiki.php
Reverts miraheze/mw-config#5902, something went wrong....
> Revert "Updating LocalWiki.php settings for Constantnoblewiki per T13503"

- LocalWiki.php
Testing if `$wgDisableLangConversion` is causing templating issues or not.
> Updating LocalWiki.php settings for NamuWitch Wiki per T13513

- LocalSettings.php
Updating the `LocalSettings.php` entry for the Animal Crossing Wiki per [T13546](https://issue-tracker.miraheze.org/T13546).
> Updating LocalSettings.php for the Animal Crossing Wiki per T13546

- LocalSettings.php
- LocalWiki.php
Updating the `LocalWiki.php` settings for the Kaiserreich Wiki per [T13504](https://issue-tracker.miraheze.org/T13504).
> Updating LocalWiki.php settings for Kaiserreich Wiki per T13504

- LocalWiki.php
- initialise/MirahezeFunctions.php
Will be migrated to CreateWiki's new built in extra field data system.
> Stop saving changes to primary-domain and mediawiki-version for now

- LocalSettings.php
Wiki has been renamed (T13516, from swordartonline.miraheze.org to saozh.miraheze.org).
Change the Settings of T13091 and T13090.
> Adaptive changes due to the renaming of wiki

- GlobalExtensions.php
- LocalSettings.php
Also set wgSVGNativeRendering to true.
Bug: T13610
> Undeploy NativeSvgHandler

- LocalSettings.php
We already set it. Remove the duplicate.
> Remove duplicate wgSVGNativeRendering

- LocalSettings.php
Task: https://issue-tracker.miraheze.org/T13621
> T13621: Add protection levels for codinghutwiki

- LocalSettings.php
- ManageWikiSettings.php
Documentation: https://www.mediawiki.org/wiki/Extension:DynamicSidebar#Configuration
Adding this to ManageWiki as I believe that enabling this feature can be useful for extension users.
> T13622: Add $wgDynamicSidebarUsePageCategories

- LocalWiki.php
Change-Id: Ia052102df225215b2e3e1db0b9b71603a9f6f3dc
> Add $wgHooks for TKU Wiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T13595
> T13595: set $wgCategoryCollation to 'uca-cs' on historikawiki

- LocalSettings.php
- LocalWiki.php
While I deploy a change to prevent and saves to it temporarily so it doesn't mess up the data store.
> Temp disable core module

- LocalSettings.php
- LocalWiki.php
Reverts miraheze/mw-config#5940
> Revert "Temp disable core module"

- LocalSettings.php
For [T13591](https://issue-tracker.miraheze.org/T13591), changes Miraheze and MediaWiki footer icons for [damnationwiki](https://damnation.miraheze.org/wiki/Main_Page)
> T13591: Change footer icons for damnationwiki

- LocalSettings.php
Reverts miraheze/mw-config#5944
> Revert "Update LocalSettings.php"

- LocalSettings.php
https://issue-tracker.miraheze.org/T13636
> T13636: Change footer icons for noobsincombatcoldfrontwiki

- GlobalSettings.php
- LocalSettings.php
> Fix correct format for wgCentralAuthEnableSul3 under MW 1.43

- rpc/RunJobs.php
- rpc/RunSingleJob.php
Copies https://github.com/wikimedia/operations-mediawiki-config/commit/95692f396efe2eef7ff170e1384e3fd878d7f020
> roc: Update RunJobs files

- LocalWiki.php
https://issue-tracker.miraheze.org/T13620
> T13620: Show AbuseFilter edits in RC for constantnoblewiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T13672
> T13672: Update $wgDefaultUserOptions for banjokazooiewiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T13662
> T13662: Change footer icons for computerunionwiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T13564
> T13564: Changing of Footer Icons on Systems General Wiki

- LocalSettings.php
Reverts miraheze/mw-config#5912
> Revert "T13564: Changing of Footer Icons on Systems General Wiki"

- LocalSettings.php
https://issue-tracker.miraheze.org/T13657
> T13657: Change footer icons for toyboxfunhousewiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T13708
> T13708: Add founder protection level for constantnoblewiki

- Sitenotice.php
Reverts miraheze/mw-config#5968
> Revert "add notice for LE wikis"

- Sitenotice.php
Reverts miraheze/mw-config#5969
> Revert "Revert "add notice for LE wikis""

- initialise/MirahezeFunctions.php
Reverts miraheze/mw-config#5973
> Revert "Set ManageWiki settings variables to actual dbname"

- LocalSettings.php
> Rename restriction level

- ManageWikiExtensions.php
https://issue-tracker.miraheze.org/T13080
> T13080: Add Details extension to ManageWiki

- LocalWiki.php
This should allow JsonConfig to load data from Wikimedia Commons.
https://www.mediawiki.org/wiki/Extension:JsonConfig#Supporting_Wikimedia_templates
https://issue-tracker.miraheze.org/T13830
> T13830: Add configuration for shintowiki

- LocalSettings.php
- ManageWikiSettings.php
https://www.mediawiki.org/wiki/Extension:Details#Configuration
https://issue-tracker.miraheze.org/T13844
> T13844: Add wgDetailsMWCollapsibleCompatibility

- LocalWiki.php
The code is dysfunctional because it adds the links to the $footerlinks variable which is not defined.
> remove unused footer links code

- LocalSettings.php
- ManageWikiSettings.php
https://www.mediawiki.org/wiki/Extension:WikiSEO#Configuration
> Add wgNortonSiteVerificationKey to ManageWiki

- LocalSettings.php
Reverts miraheze/mw-config#6009
Icons broken due to CSP
> Revert "New icons for Alter Ego Wiki"

- LocalSettings.php
> Add IWF icon for lhmnwiki

- LocalWiki.php
Change-Id: I34bfff9649b36c19f063bb30484691c8311c1cf8
> Update $wgHooks for TKU Wiki

- LocalSettings.php
- LocalWiki.php
Warnings were added to the extension in https://github.com/miraheze/DiscordNotifications/commit/1f20d850cbcce5b15951c7c6127b87b927a5415e and should be monitored.
> Log warnings from DiscordNotifications

- LocalSettings.php
> Disallow temporary account-related CheckUser groups and right

- LocalSettings.php
> T14109: Footer icons for blockstarplanetwiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T14182
> T14182: Set $wgTranslateDisabledTargetLanguages for astralpartywiki

- LocalSettings.php
https://issue-tracker.miraheze.org/T14186
> T14186: set $wgAdvancedSearchDeepcatEnabled to false on all wikis

- FileBackend.php
- GlobalCache.php
- GlobalSettings.php
- LocalSettings.php
- initialise/MirahezeFunctions.php
> Add an isBeta() method to MirahezeFunctions

- SemanticMediaWiki.php
Add the Player, MapArt, Item and Location namespaces to $smwgNamespacesWithSemanticLinksi.
> T14192: Set $smwgNamespacesWithSemanticLinks for vanillaeuropawiki

- GlobalSettings.php
They are copied from https://github.com/wikimedia/operations-mediawiki-config/blob/5908b87cf325a91f5a22674eff9db1419506a4b5/wmf-config/ext-CirrusSearch.php which are selected based on what I think we need.
> Set some CirrusSearch configs

- LocalSettings.php
Reverts miraheze/mw-config#6120
> Revert "depool c3 for outage"

- LocalSettings.php
Disk is running a little low so adding it to wgCreateWikiDatabaseClustersInactive
> Add db161 (c2) to wgCreateWikiDatabaseClustersInactive

- LocalSettings.php
This skin should now work on MW 1.44.
> Remove Femiwiki from $disabledExtensions

- GlobalLogging.php
> Set 'context' on $wmgMonologProcessors

- ManageWikiSettings.php
https://phabricator.wikimedia.org/T405134
> Mark wgCodeMirrorV6 as experimental
